#!/usr/bin/env node
// Project Playwright's OWN declared Chromium OS dependencies into the house payload, for the pinned version.
//
// WHY: Chromium's system libraries used to be apt-installed by `playwright install --with-deps` in post-create, on
// EVERY rebuild. They now belong in the image's cached package layer (the web/js layers' `osPackages`), which needs
// the list at GENERATION time — and the only source of truth for it is Playwright's own `install-deps` table for the
// version the house pins (`PLAYWRIGHT_VERSION`). So it is projected from that table, never typed by hand, and a test
// (tools/test-layers) fails when the pin moves without a re-projection.
//
// THE PLATFORM is the house images' Debian (typescript-node and base:debian both float to Debian 13 / trixie). When
// they move to a new Debian, a renamed library fails the image BUILD loudly; re-project for the new platform here.
//
//   node tools/playwright-deps/project.mjs           check: the generated file matches the pinned version's table
//   node tools/playwright-deps/project.mjs --write   regenerate it (needs the network: `npm pack playwright-core@<v>`)
import { execFileSync } from 'node:child_process';
import { mkdtempSync, readFileSync, writeFileSync, rmSync, existsSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { runInNewContext } from 'node:vm';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..', '..');
const UTILS = join(ROOT, 'plugins/house/engine/nx-tools/src/generators/_utils');
const PIN = readFileSync(join(UTILS, 'versions.ts'), 'utf8').match(/PLAYWRIGHT_VERSION = '([^']+)'/)[1];
const OUT = join(UTILS, 'playwright-deps.ts');
const PLATFORM = 'debian13';

function table(version) {
  const dir = mkdtempSync(join(tmpdir(), 'pw-deps-'));
  try {
    execFileSync('npm', ['pack', '--silent', `playwright-core@${version}`], { cwd: dir, stdio: ['ignore', 'ignore', 'inherit'] });
    execFileSync('tar', ['xzf', `playwright-core-${version}.tgz`], { cwd: dir });
    // The table lives in nativeDeps.js on older releases and inside the bundle on newer ones — read whichever exists.
    const candidates = ['package/lib/server/registry/nativeDeps.js', 'package/lib/coreBundle.js'].map((file) => join(dir, file));
    const source = readFileSync(candidates.find(existsSync), 'utf8');
    const entry = (arch) => {
      const key = `"${PLATFORM}${arch}": {`;
      const start = source.indexOf(key);
      if (start === -1) throw new Error(`playwright-core@${version} declares no ${PLATFORM}${arch} dependencies`);
      let depth = 0;
      let at = start + key.length - 1;
      for (; at < source.length; at += 1) {
        if (source[at] === '{') depth += 1;
        if (source[at] === '}' && --depth === 0) break;
      }
      // Evaluated in an EMPTY context: it is text from a downloaded tarball, so it gets no globals, no process.
      return runInNewContext(`(${source.slice(start + key.length - 1, at + 1)})`, Object.create(null), { timeout: 1000 });
    };
    const x64 = entry('-x64');
    // arm64 is declared as a copy of x64 for these two lists; anything else means the projection needs an arch axis.
    const arm = source.slice(source.indexOf(`deps["${PLATFORM}-arm64"] = {`));
    for (const field of ['tools', 'chromium']) {
      if (!arm.startsWith(`deps["${PLATFORM}-arm64"]`) || !arm.slice(0, 400).includes(`${field}: [...deps["${PLATFORM}-x64"].${field}]`)) {
        throw new Error(`playwright-core@${version}: ${PLATFORM}-arm64 ${field} is not x64's — the projection needs an arch dimension`);
      }
    }
    const list = (deps) => [...new Set([...deps.tools, ...deps.chromium])];
    return list(x64);
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
}

function render(version, packages) {
  return `// GENERATED by tools/playwright-deps/project.mjs from playwright-core@${version}'s own \`install-deps\` table — never
// hand-edit; re-run it (with --write) whenever PLAYWRIGHT_VERSION or the house images' Debian moves.
//
// What \`playwright install-deps chromium\` installs on ${PLATFORM}: its tools (Xvfb, fonts) and Chromium's libraries —
// now one cached image layer (the web and js layers' osPackages) instead of an apt step on every rebuild.
export const CHROMIUM_OS_PACKAGES_VERSION = '${version}';
export const CHROMIUM_OS_PACKAGES_PLATFORM = '${PLATFORM}';
export const CHROMIUM_OS_PACKAGES: readonly string[] = [
${packages.map((name) => `  '${name}',`).join('\n')}
];
`;
}

const expected = render(PIN, table(PIN));
if (process.argv.includes('--write')) {
  writeFileSync(OUT, expected);
  console.log(`wrote ${OUT} (playwright-core@${PIN}, ${PLATFORM})`);
} else if (!existsSync(OUT) || readFileSync(OUT, 'utf8') !== expected) {
  console.error(`DRIFT: ${OUT} is not the projection of playwright-core@${PIN} — run: node tools/playwright-deps/project.mjs --write`);
  process.exit(1);
} else {
  console.log(`ok: Chromium OS packages match playwright-core@${PIN} (${PLATFORM})`);
}
