// GENERATED by tools/firebase-compat/project.mjs from the npm registry — never hand-edit; re-run it with --write
// (the scheduled check fails when npm has moved on: a new @angular/fire, or FIREBASE_TOOLS_VERSION moved).
//
// Read by the Angular adapter's Firebase client (@angular/fire + firebase follow the INSTALLED Angular major) and the
// functions manifest (engines.node must be a live Cloud Functions runtime). See the script for the derivation.
// Import-free on purpose: house.sh's probe loads it (with adapters/angular/angularfire-judge.ts) before any install.

/**
 * The date npm last said this — a project's installed toolkit carries a FROZEN copy, so every message that rests on
 * the table ("no stable @angular/fire for Angular 22") says "as of" this date, never "yet".
 */
export const ANGULARFIRE_TABLE_AS_OF = '2026-10-07';

/** One @angular/fire release, with what it requires. */
export interface AngularFireRelease {
  /** Exact: firebase below is THIS release's own range, so a floating @angular/fire would break the pairing. */
  angularfire: string;
  /** @angular/fire's own `dependencies.firebase` — the root declares exactly this, so the package manager keeps ONE SDK. */
  firebase: string;
  /** Its peer on @angular/core. */
  angularCore: string;
  /** The lowest @angular/core it accepts within the major. */
  minAngular: string;
  /** Its (optional) peer on firebase-tools, or null. */
  firebaseTools: string | null;
  /**
   * The firebase-tools a project on this release declares: the house's pin when that peer admits it, else the newest
   * stable firebase-tools inside the peer (npm refuses the install otherwise — ERESOLVE), else null (none exists).
   */
  firebaseToolsPin: string | null;
}

/** Per Angular major: the newest stable @angular/fire for it — or, when none exists, the newest prerelease (or null). */
export const ANGULARFIRE_BY_ANGULAR_MAJOR: Readonly<Record<number, { stable: AngularFireRelease | null; prerelease: AngularFireRelease | null }>> = {
  17: {
    stable: {
      "angularfire": "17.1.0",
      "firebase": "^10.12.0",
      "angularCore": "^17.0.0",
      "minAngular": "17.0.0",
      "firebaseTools": "^13.0.0",
      "firebaseToolsPin": "13.35.1"
    },
    prerelease: null,
  },
  18: {
    stable: {
      "angularfire": "18.0.1",
      "firebase": "^10.12.0",
      "angularCore": "^18.0.0",
      "minAngular": "18.0.0",
      "firebaseTools": "^13.0.0",
      "firebaseToolsPin": "13.35.1"
    },
    prerelease: null,
  },
  19: {
    stable: {
      "angularfire": "19.2.0",
      "firebase": "^11.8.0",
      "angularCore": "^19.0.0",
      "minAngular": "19.0.0",
      "firebaseTools": "^13.0.0",
      "firebaseToolsPin": "13.35.1"
    },
    prerelease: null,
  },
  20: {
    stable: {
      "angularfire": "20.1.0",
      "firebase": "^11.8.0",
      "angularCore": "^20.0.0",
      "minAngular": "20.0.0",
      "firebaseTools": "^14.0.0 || ^15.0.0",
      "firebaseToolsPin": "15.32.1"
    },
    prerelease: null,
  },
  21: {
    stable: null,
    prerelease: {
      "angularfire": "21.0.0-rc.1",
      "firebase": "^12.18.0",
      "angularCore": "^21.2.0",
      "minAngular": "21.2.0",
      "firebaseTools": "^14.0.0 || ^15.0.0",
      "firebaseToolsPin": "15.32.1"
    },
  },
  22: {
    stable: null,
    prerelease: null,
  },
};

/** The newest Angular major npm knew when this was projected — a newer one is a major this table has never seen. */
export const ANGULARFIRE_TABLE_NEWEST_ANGULAR = 22;

/** The firebase-tools these runtimes were read from (must equal FIREBASE_TOOLS_VERSION). */
export const FUNCTIONS_RUNTIMES_FROM_FIREBASE_TOOLS = '15.32.1';
/** The Node majors Cloud Functions runs as GA runtimes, oldest first. */
export const FUNCTIONS_NODE_RUNTIMES: readonly string[] = ['20', '22', '24'];
