// GENERATED by tools/firebase-compat/project.mjs from the npm registry — never hand-edit; re-run it with --write
// (the scheduled check fails when npm has moved on: a new @angular/fire or firebase, a new engines.node in firebase's
// dependency closure, or FIREBASE_TOOLS_VERSION moved).
//
// Read by the Angular adapter's Firebase client (@angular/fire + firebase follow the INSTALLED Angular major) and the
// functions manifest (engines.node must be a live Cloud Functions runtime). See the script for the derivation.
// Import-free on purpose: house.sh's probe loads it (with adapters/angular/angularfire-judge.ts) before any install.

/**
 * The date npm last said this — a project's installed toolkit carries a FROZEN copy, so every message that rests on
 * the table ("no stable @angular/fire for Angular 22") says "as of" this date, never "yet".
 */
export const ANGULARFIRE_TABLE_AS_OF = '2026-10-07';

/**
 * What a firebase spec installs, and what that install needs of Node: the `engines.node` of firebase's WHOLE dependency
 * closure (firebase declares none itself; its packages do — and yarn refuses an install on any other Node; npm and pnpm warn).
 */
export interface FirebaseResolution {
  /** The firebase release the spec resolves to on npm (the newest inside the range; `latest`'s target). */
  firebase: string;
  /** The Node majors (18–26) every package in that closure accepts. */
  nodeMajors: number[];
  /** Each distinct `engines.node` in the closure that excludes one of those majors: the majors it admits, who states it. */
  nodeNeeds: Array<{ range: string; nodeMajors: number[]; packages: string[] }>;
}

/** One @angular/fire release, with what it requires. */
export interface AngularFireRelease {
  /** Exact: firebase below is THIS release's own range, so a floating @angular/fire would break the pairing. */
  angularfire: string;
  /** @angular/fire's own `dependencies.firebase` — the root declares exactly this, so the package manager keeps ONE SDK. */
  firebase: string;
  /** What that range installs today, and the Node it needs — a release the project's Node cannot install is never chosen. */
  firebaseResolves: FirebaseResolution;
  /** Its peer on @angular/core. */
  angularCore: string;
  /** The lowest @angular/core it accepts within the major. */
  minAngular: string;
  /** Its (optional) peer on firebase-tools, or null. */
  firebaseTools: string | null;
  /**
   * The firebase-tools a project on this release declares: the house's pin when that peer admits it, else the newest
   * stable firebase-tools inside the peer (npm refuses the install otherwise — ERESOLVE), else null (none exists).
   */
  firebaseToolsPin: string | null;
}

/** Per Angular major: the newest stable @angular/fire for it — or, when none exists, the newest prerelease (or null). */
export const ANGULARFIRE_BY_ANGULAR_MAJOR: Readonly<Record<number, { stable: AngularFireRelease | null; prerelease: AngularFireRelease | null }>> = {
  17: {
    stable: {
      "angularfire": "17.1.0",
      "firebase": "^10.12.0",
      "firebaseResolves": {
        "firebase": "10.14.1",
        "nodeMajors": [18, 19, 20, 21, 22, 23, 24, 25, 26],
        "nodeNeeds": []
      },
      "angularCore": "^17.0.0",
      "minAngular": "17.0.0",
      "firebaseTools": "^13.0.0",
      "firebaseToolsPin": "13.35.1"
    },
    prerelease: null,
  },
  18: {
    stable: {
      "angularfire": "18.0.1",
      "firebase": "^10.12.0",
      "firebaseResolves": {
        "firebase": "10.14.1",
        "nodeMajors": [18, 19, 20, 21, 22, 23, 24, 25, 26],
        "nodeNeeds": []
      },
      "angularCore": "^18.0.0",
      "minAngular": "18.0.0",
      "firebaseTools": "^13.0.0",
      "firebaseToolsPin": "13.35.1"
    },
    prerelease: null,
  },
  19: {
    stable: {
      "angularfire": "19.2.0",
      "firebase": "^11.8.0",
      "firebaseResolves": {
        "firebase": "11.10.0",
        "nodeMajors": [18, 19, 20, 21, 22, 23, 24, 25, 26],
        "nodeNeeds": []
      },
      "angularCore": "^19.0.0",
      "minAngular": "19.0.0",
      "firebaseTools": "^13.0.0",
      "firebaseToolsPin": "13.35.1"
    },
    prerelease: null,
  },
  20: {
    stable: {
      "angularfire": "20.1.0",
      "firebase": "^11.8.0",
      "firebaseResolves": {
        "firebase": "11.10.0",
        "nodeMajors": [18, 19, 20, 21, 22, 23, 24, 25, 26],
        "nodeNeeds": []
      },
      "angularCore": "^20.0.0",
      "minAngular": "20.0.0",
      "firebaseTools": "^14.0.0 || ^15.0.0",
      "firebaseToolsPin": "15.32.1"
    },
    prerelease: null,
  },
  21: {
    stable: null,
    prerelease: {
      "angularfire": "21.0.0-rc.1",
      "firebase": "^12.18.0",
      "firebaseResolves": {
        "firebase": "12.19.0",
        "nodeMajors": [20, 21, 22, 23, 24, 25, 26],
        "nodeNeeds": [
          {
            "range": ">=20.0.0",
            "nodeMajors": [20, 21, 22, 23, 24, 25, 26],
            "packages": ["@firebase/ai@2.16.0", "@firebase/app-check-compat@0.4.7", "@firebase/app-check@0.13.1", "@firebase/app-compat@0.5.18", "@firebase/app@0.16.2", "@firebase/auth-compat@0.6.11", "@firebase/auth@1.13.6", "@firebase/component@0.7.5", "@firebase/database-compat@2.1.7", "@firebase/database@1.1.5", "@firebase/firestore-compat@0.4.14", "@firebase/firestore@4.17.2", "@firebase/functions-compat@0.5.0", "@firebase/functions@0.14.0", "@firebase/logger@0.5.2", "@firebase/storage-compat@0.4.5", "@firebase/storage@0.14.5", "@firebase/util@1.15.3"]
          }
        ]
      },
      "angularCore": "^21.2.0",
      "minAngular": "21.2.0",
      "firebaseTools": "^14.0.0 || ^15.0.0",
      "firebaseToolsPin": "15.32.1"
    },
  },
  22: {
    stable: null,
    prerelease: null,
  },
};

/** The newest Angular major npm knew when this was projected — a newer one is a major this table has never seen. */
export const ANGULARFIRE_TABLE_NEWEST_ANGULAR = 22;

/**
 * What a firebase declared by npm dist-tag installed as of this table — and the Node it needs. A floating tag moves with
 * no commit behind it, so the house never writes one; this is what it says to a project that still declares one.
 */
export const FIREBASE_BY_DIST_TAG: Readonly<Record<string, FirebaseResolution>> = {
  latest: {
    "firebase": "13.0.0",
    "nodeMajors": [24, 25, 26],
    "nodeNeeds": [
      {
        "range": ">=20.0.0",
        "nodeMajors": [20, 21, 22, 23, 24, 25, 26],
        "packages": ["@firebase/app-check-compat@0.4.7", "@firebase/app-check@0.13.1", "@firebase/component@0.7.5", "@firebase/database-compat@2.1.7", "@firebase/database@1.1.5", "@firebase/functions-compat@0.5.0", "@firebase/functions@0.14.0", "@firebase/logger@0.5.2", "@firebase/util@1.15.3"]
      },
      {
        "range": ">=24.12.0",
        "nodeMajors": [24, 25, 26],
        "packages": ["@firebase/ai@3.0.0", "@firebase/app-compat@0.5.19", "@firebase/app@0.16.3", "@firebase/auth-compat@0.6.12", "@firebase/auth@1.13.7", "@firebase/firestore-compat@0.4.15", "@firebase/firestore@4.18.0", "@firebase/storage-compat@0.4.6", "@firebase/storage@0.14.6"]
      }
    ]
  }
};

/**
 * Per Angular major: the TypeScript range its newest compiler-cli peers, and the TypeScript the house declares when it
 * CREATES a workspace on that major (create-nx-workspace installs Nx's newest, which an older compiler refuses).
 */
export const ANGULAR_TYPESCRIPT_BY_MAJOR: Readonly<Record<number, { range: string; pin: string }>> = {
  17: {
    "range": ">=5.2 <5.5",
    "pin": "~5.4.5"
  },
  18: {
    "range": ">=5.4 <5.6",
    "pin": "~5.5.4"
  },
  19: {
    "range": ">=5.5 <5.9",
    "pin": "~5.8.3"
  },
  20: {
    "range": ">=5.8 <6.0",
    "pin": "~5.9.3"
  },
  21: {
    "range": ">=5.9 <6.1",
    "pin": "~6.0.3"
  },
  22: {
    "range": ">=6.0 <6.1",
    "pin": "~6.0.3"
  }
};

/** The firebase-tools these runtimes were read from (must equal FIREBASE_TOOLS_VERSION). */
export const FUNCTIONS_RUNTIMES_FROM_FIREBASE_TOOLS = '15.32.1';
/** The Node majors Cloud Functions runs as GA runtimes, oldest first. */
export const FUNCTIONS_NODE_RUNTIMES: readonly string[] = ['20', '22', '24'];
