// GENERATED by tools/firebase-compat/project.mjs from Google's versioned gcloud archive — never hand-edit; move
// GCLOUD_CLI_VERSION (versions.ts) and re-run it with --write.

/** The Google Cloud CLI archive per architecture, for GCLOUD_CLI_VERSION, with the sha256 the installer checks. */
export const GCLOUD_CLI_ARCHIVE = {
  version: '588.0.0',
  downloads: {
    amd64: {
      url: 'https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-cli-588.0.0-linux-x86_64.tar.gz',
      sha256: 'e38ceac43022bb5a4d94d5a4a9c9c51f90f28c910b59a018ae07011e220c4412',
    },
    arm64: {
      url: 'https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-cli-588.0.0-linux-arm.tar.gz',
      sha256: '15d0365242d72caebda77647642ae73f68bde10b1f71338c8a704aea200d8ab1',
    },
  },
} as const;
