// GENERATED by tools/playwright-deps/project.mjs from playwright-core@1.63.0's own `install-deps` table — never
// hand-edit; re-run it (with --write) whenever PLAYWRIGHT_VERSION or the house images' Debian moves.
//
// What `playwright install-deps chromium` installs on debian13: its tools (Xvfb, fonts) and Chromium's libraries —
// now one cached image layer (the web and js layers' osPackages) instead of an apt step on every rebuild.
export const CHROMIUM_OS_PACKAGES_VERSION = '1.63.0';
export const CHROMIUM_OS_PACKAGES_PLATFORM = 'debian13';
export const CHROMIUM_OS_PACKAGES: readonly string[] = [
  'xvfb',
  'fonts-noto-color-emoji',
  'fonts-unifont',
  'libfontconfig1',
  'libfreetype6',
  'xfonts-scalable',
  'fonts-liberation',
  'fonts-ipafont-gothic',
  'fonts-wqy-zenhei',
  'fonts-tlwg-loma-otf',
  'fonts-freefont-ttf',
  'libasound2t64',
  'libatk-bridge2.0-0t64',
  'libatk1.0-0t64',
  'libatspi2.0-0t64',
  'libcairo2',
  'libcups2t64',
  'libdbus-1-3',
  'libdrm2',
  'libgbm1',
  'libglib2.0-0t64',
  'libnspr4',
  'libnss3',
  'libpango-1.0-0',
  'libx11-6',
  'libxcb1',
  'libxcomposite1',
  'libxdamage1',
  'libxext6',
  'libxfixes3',
  'libxkbcommon0',
  'libxrandr2',
];
