// THE VERSIONS THE HOUSE WRITES — every dependency version a generator puts into a project, in ONE place.
//
// WHY ONE PLACE. A generator that writes `latest` (or `*`, `next`, an unbounded `>=`) hands the project a version
// nobody chose: it moves with no commit behind it, and two packages that must agree (`@angular/fire` and the
// `firebase` it carries) each float to THEIR newest — which is how a house app ended up with two Firebase SDKs and
// "No Firebase App '[DEFAULT]'". 0.35.0 fixed one instance (`@playwright/test`); the class was never swept, so
// 0.50.0 sweeps it and closes it: every version is a deliberate value here, and every dependency write goes through
// `declareDependencies` (_utils/dependencies.ts), which REFUSES a floating spec. tools/test-generators fails on a
// generator that writes one any other way.
//
// WHAT LIVES WHERE:
//   - here: the house's own pins (hand-chosen, moved deliberately);
//   - firebase-compat.ts: what is DERIVED from npm (the Angular → @angular/fire → firebase table, Cloud Functions'
//     Node runtimes) — generated by tools/firebase-compat/project.mjs, never hand-edited;
//   - node-facts.ts: Node's LTS codenames and the typescript-node images that exist (tools/node-facts/project.mjs);
//   - the project: its Node major (`.nvmrc` / `.node-version` / Volta, _utils/node-version.ts) — a project fact.
//
// MOVING ONE is a release decision: an existing project's pin is PROJECT STATE (class B), so it moves only by a
// migration — and a migration never imports these, nor the derived tables (firebase-compat.ts, node-facts.ts): it
// FREEZES its own copy of every value it writes (the live value moves on, and a rung's fixture must pin what it does
// under every later payload). It may share the pure MECHANICS that take those values as parameters — the version-spec
// rule, the Node grammar, the @angular/fire judge — as every rung shares json-edits.

/**
 * THE Playwright version — one number for both of its uses, so they share one Chromium download: the shared
 * browser's own runtime (playwright-core, tools/shared-browser/runtime.mjs) and a JS project's @playwright/test.
 * Chromium's OS packages are projected from it (tools/playwright-deps/project.mjs --write when it moves).
 */
export const PLAYWRIGHT_VERSION = '1.63.0';

/**
 * The Firebase CLI, as the project's own devDependency — exact, because it runs the emulators and the deploys, and
 * the same commit must run the same CLI on every machine and in CI. Moving it: tools/firebase-compat/project.mjs
 * --write (Cloud Functions' supported Node runtimes are projected from THIS version's own table).
 */
export const FIREBASE_TOOLS_VERSION = '15.32.1';

/**
 * The Google Cloud CLI release the firebase layer installs into the IMAGE — from Google's VERSIONED ARCHIVE
 * (dl.google.com/…/google-cloud-cli-<v>-linux-<arch>.tar.gz, kept for every release), never its apt repository, whose
 * index drops a release after about a year. A rebuild reuses it and every machine runs this one. Its state (logins,
 * application-default credentials, configurations) lives in ~/.config/gcloud — the persisted ~/.config.
 * Moving it: change this, then `node tools/firebase-compat/project.mjs --write` re-projects the archives' sha256
 * (gcloud-archive.ts); the check fails until it has.
 */
export const GCLOUD_CLI_VERSION = '588.0.0';

/** The Cloud Functions runtime SDKs — the workspace root AND the deploy manifest (functions/package.json) read these. */
export const FIREBASE_ADMIN_VERSION = '^13.6.0';
export const FIREBASE_FUNCTIONS_VERSION = '^7.0.0';

/** The type utilities the vendored navigation kernel imports (only a prerelease is published, so it is exact). */
export const TYPESCRIPT_UTILS_VERSION = '0.1.0-alpha.0';

/**
 * The Node major a NEW project is seeded with (its `.nvmrc`). Only a seed: from then on the project's `.nvmrc` is
 * the one source — the devcontainer image, the functions `engines` and the docs read it, and no upgrade moves it.
 * Must be a GA Cloud Functions runtime (tools/test-layers checks it against the projected table).
 */
export const HOUSE_NODE_MAJOR = '24';
