<!-- Generated by @bespunky/nx-tools:design-system. Rewritten on every run — do not hand-edit. -->
# The design system — structure & conventions

This library is the **single source of visual truth** for the workspace: every colour, space, radius, type
step, elevation, border, duration and easing comes from here. It ships the **mechanism** — tokens, a SASS API,
a theme — and no components and no opinionated styles.

It is the **framework-neutral core**: no UI framework in this workspace has a design-system binding yet, so it
carries its runtime as plain DOM (`setMode`). When a framework binding is added (in a house project, the
`angular` layer), components arrive through that binding's generator.

## The two layers

| Layer | What it is | Where it lives |
| --- | --- | --- |
| **Runtime** — CSS custom properties | What actually ships. Cascades, so a theme change is a **re-binding**, live. | Emitted **once**, by `ds.theme()`, from the consumer's global stylesheet |
| **Author-time** — the SASS API | Functions, mixins, placeholders. **Zero-output** until called. | `styles/` |

A consumer reads **semantic** tokens (`color-on-surface`), never a primitive swatch.

## Layout

```
{{root}}/
├── styles/
│   ├── _index.scss          ★ THE PUBLIC SASS API — @forward … show
│   ├── _core/               the token engine (private): _tokens.scss (the ONLY file with literal values),
│   │                        _functions.scss, _theme.scss
│   └── _utils/              the authoring toolkit (private): mixins, accessibility (visually-hidden, skip-link, skip-target), placeholders
└── src/
    ├── index.ts             ★ THE PUBLIC RUNTIME API ({{importPath}})
    └── lib/ds-mode.ts       setMode / getMode / resolvedMode — writes `data-{{tokenPrefix}}-mode`
```

## Consuming it

Put the library's PARENT directory on your sass load path, then:

```scss
@use '{{specifier}}' as ds;      // at the very top of the global stylesheet
@include ds.theme();             // once, anywhere after it — emits the tokens as CSS custom properties

.card { padding: ds.space(4); color: ds.color('on-surface'); background: ds.color('surface'); }
```

```ts
import { setMode } from '{{importPath}}';
setMode('dark');   // a re-binding of tokens, not a reload
```

## The rules

1. **No literal visual values outside `styles/_core/_tokens.scss`.** If the value isn't a token, add the token.
2. **Consumers read semantic tokens only**, never a primitive.
3. **`ds.theme()` is called exactly once**, from the global stylesheet. Everything else is zero-output.
4. **When the design system lacks a concept, model it here** — never work around the gap locally.

> **The tokens in `_tokens.scss` are PLACEHOLDERS with no design authority.** The design phase
> (`bespunky-product-ux:stage-the-vision` → `realize-the-vision`) replaces that file wholesale.
