// Validation for host-port arbitration — including the TWO-CONTAINER case, which is the only case that
// matters: the failure this whole mechanism exists to prevent cannot be reproduced with one container.
//
// Run:  node --test tools/shared-browser/
//
// The concurrency tests spawn REAL processes against ONE registry directory and bind REAL sockets, so
// the atomic-claim race is exercised for real rather than simulated in-process.
//
// Generated by @bespunky/nx-tools:shared-browser. Edit the template in the toolkit, not this copy.
import { execFile } from 'node:child_process';
import { mkdtempSync, mkdirSync, readdirSync, rmSync, writeFileSync, utimesSync } from 'node:fs';
import { createServer } from 'node:net';
import { tmpdir } from 'node:os';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { promisify } from 'node:util';
import assert from 'node:assert/strict';
import { test, describe, before, after } from 'node:test';

const pexec = promisify(execFile);
const HERE = dirname(fileURLToPath(import.meta.url));
const CLI = join(HERE, 'port-claim.mjs');

// A high, quiet band so a developer's real services can't make these tests flaky.
const BAND_START = 21080;
const BAND_SIZE = 8;

let root;
before(() => { root = mkdtempSync(join(tmpdir(), 'port-claim-')); });
after(() => rmSync(root, { recursive: true, force: true }));

let seq = 0;
const freshRegistry = () => {
  const dir = join(root, `reg-${seq++}`);
  mkdirSync(dir, { recursive: true });
  return dir;
};

async function claim(args) {
  const { stdout } = await pexec(process.execPath, [CLI, ...args]);
  return JSON.parse(stdout);
}
async function claimFails(args) {
  try {
    await pexec(process.execPath, [CLI, ...args]);
    return null;
  } catch (err) {
    return JSON.parse(err.stdout);
  }
}
const allocArgs = (registry, identity, extra = []) => [
  'allocate', `--registry=${registry}`, `--identity=${identity}`,
  `--band-start=${BAND_START}`, `--band-size=${BAND_SIZE}`, ...extra,
];

/** Hold a real listening socket, so the local gate has something true to find. */
function hold(port) {
  return new Promise((resolve, reject) => {
    const srv = createServer();
    srv.once('error', reject);
    srv.listen(port, '127.0.0.1', () => resolve(() => new Promise((r) => srv.close(r))));
  });
}

describe('allocation', () => {
  test('distinct containers get distinct ports', async () => {
    const reg = freshRegistry();
    const ports = [];
    for (const id of ['dc-a', 'dc-b', 'dc-c', 'dc-d']) {
      ports.push((await claim(allocArgs(reg, id))).port);
    }
    assert.equal(new Set(ports).size, ports.length, `expected distinct, got ${ports}`);
  });

  test('the same container is stable, and a REBUILD reclaims the same port', async () => {
    const reg = freshRegistry();
    const first = await claim(allocArgs(reg, 'dc-stable'));
    // A rebuild is a new container instance with the SAME devcontainer id and no local record.
    const again = await claim(allocArgs(reg, 'dc-stable'));
    assert.equal(again.port, first.port);
    assert.equal(again.reclaimed, true);
  });

  test('the recorded port gets first refusal, so a bookmarked URL cannot drift', async () => {
    const reg = freshRegistry();
    // Pin our identity to a port that is NOT its hashed slot, then re-allocate with it recorded.
    const target = BAND_START + BAND_SIZE - 1;
    writeFileSync(join(reg, `${target}.claim`), 'dc-drift\nclaimed\n');
    const got = await claim(allocArgs(reg, 'dc-drift', [`--recorded=${target}`]));
    assert.equal(got.port, target);
    assert.equal(got.reclaimed, true);
  });

  test('a port someone is listening on is never handed out', async () => {
    const reg = freshRegistry();
    const slotOwner = await claim(allocArgs(reg, 'dc-probe'));
    rmSync(join(reg, `${slotOwner.port}.claim`));
    const release = await hold(slotOwner.port);
    try {
      const other = await claim(allocArgs(reg, 'dc-probe'));
      assert.notEqual(other.port, slotOwner.port);
    } finally {
      await release();
    }
  });

  test("another container's live claim is respected; an expired one is taken over", async () => {
    const reg = freshRegistry();
    const mine = await claim(allocArgs(reg, 'dc-x'));
    rmSync(join(reg, `${mine.port}.claim`));
    writeFileSync(join(reg, `${mine.port}.claim`), 'dc-someone-else\nclaimed\n');

    const detoured = await claim(allocArgs(reg, 'dc-x'));
    assert.notEqual(detoured.port, mine.port, 'must not steal a live claim');

    // Age the foreign claim past its TTL, then a container hashing there may take it over.
    const old = new Date(Date.now() - 1000 * 60 * 60 * 24 * 30) / 1000;
    utimesSync(join(reg, `${mine.port}.claim`), old, old);
    const reclaimed = await claim(allocArgs(reg, 'dc-x', [`--recorded=${mine.port}`, '--ttl=60']));
    assert.equal(reclaimed.port, mine.port, 'an expired claim should be reclaimable');
  });

  test('an exhausted band fails loudly instead of double-booking', async () => {
    const reg = freshRegistry();
    for (let i = 0; i < BAND_SIZE; i++) {
      writeFileSync(join(reg, `${BAND_START + i}.claim`), `dc-other-${i}\nclaimed\n`);
    }
    const err = await claimFails(allocArgs(reg, 'dc-late'));
    assert.match(err.error, /no free port/);
  });

  test('with NO registry it still allocates — and says the gate was unavailable', async () => {
    const got = await claim(allocArgs('/proc/nonexistent-registry', 'dc-solo'));
    assert.equal(got.registry, false);
    assert.ok(got.port >= BAND_START && got.port < BAND_START + BAND_SIZE);
  });
});

describe('two containers, concurrently — the case that only matters in pairs', () => {
  test('8 containers racing on ONE registry all get distinct ports', async () => {
    const reg = freshRegistry();
    const ids = Array.from({ length: BAND_SIZE }, (_, i) => `dc-race-${i}`);
    const results = await Promise.all(ids.map((id) => claim(allocArgs(reg, id))));
    const ports = results.map((r) => r.port);
    assert.equal(new Set(ports).size, ports.length, `double-booked: ${ports}`);
    assert.equal(readdirSync(reg).filter((f) => f.endsWith('.claim')).length, BAND_SIZE);
  });

  test('the SAME container racing itself converges on one port and one claim', async () => {
    const reg = freshRegistry();
    const runs = await Promise.all(Array.from({ length: 6 }, () => claim(allocArgs(reg, 'dc-same'))));
    const ports = new Set(runs.map((r) => r.port));
    assert.equal(ports.size, 1, `one container must not spread across ${[...ports]}`);
    assert.equal(readdirSync(reg).filter((f) => f.endsWith('.claim')).length, 1);
  });
});

describe('claim hygiene', () => {
  test('our orphaned claims are collected, but never a port being served', async () => {
    const reg = freshRegistry();
    const keep = await claim(allocArgs(reg, 'dc-gc'));
    const orphan = BAND_START + ((keep.port - BAND_START + 1) % BAND_SIZE);
    const livePort = BAND_START + ((keep.port - BAND_START + 2) % BAND_SIZE);
    writeFileSync(join(reg, `${orphan}.claim`), 'dc-gc\nclaimed\n');
    writeFileSync(join(reg, `${livePort}.claim`), 'dc-gc\nclaimed\n');

    const release = await hold(livePort);
    try {
      await claim(allocArgs(reg, 'dc-gc', [`--recorded=${keep.port}`, `--live=${livePort}`]));
      const left = readdirSync(reg).filter((f) => f.endsWith('.claim')).map((f) => Number(f.split('.')[0]));
      assert.ok(!left.includes(orphan), 'a stale claim in our own name should be dropped');
      assert.ok(left.includes(livePort), 'NEVER release a port we are serving on');
    } finally {
      await release();
    }
  });

  test("refresh will not overwrite another container's live claim", async () => {
    const reg = freshRegistry();
    writeFileSync(join(reg, `${BAND_START}.claim`), 'dc-owner\nclaimed\n');
    const res = await claim(['refresh', `--registry=${reg}`, '--identity=dc-intruder', `--port=${BAND_START}`]);
    assert.equal(res.ok, false);
    assert.equal(res.conflict, true);
    assert.equal(res.owner, 'dc-owner');
  });

  test('release only ever drops our own claim', async () => {
    const reg = freshRegistry();
    writeFileSync(join(reg, `${BAND_START}.claim`), 'dc-owner\nclaimed\n');
    const nope = await claim(['release', `--registry=${reg}`, '--identity=dc-other', `--port=${BAND_START}`]);
    assert.equal(nope.ok, false);
    assert.equal(nope.notOurs, true);
    const yes = await claim(['release', `--registry=${reg}`, '--identity=dc-owner', `--port=${BAND_START}`]);
    assert.equal(yes.ok, true);
  });
});

describe('single-owner ports (:80, :4200) — first wins, the rest are TOLD', () => {
  test('the first container owns it; the second is told who does', async () => {
    const reg = freshRegistry();
    const first = await claim(['advise', `--registry=${reg}`, '--identity=dc-first', '--port=80']);
    assert.equal(first.mine, true);
    const second = await claim(['advise', `--registry=${reg}`, '--identity=dc-second', '--port=80']);
    assert.equal(second.mine, false);
    assert.equal(second.owner, 'dc-first', 'the loser must learn WHO holds it, not just that it lost');
  });

  test('re-advising is idempotent for the owner', async () => {
    const reg = freshRegistry();
    await claim(['advise', `--registry=${reg}`, '--identity=dc-a', '--port=4200']);
    const again = await claim(['advise', `--registry=${reg}`, '--identity=dc-a', '--port=4200']);
    assert.equal(again.mine, true);
  });

  test('without a registry it assumes ownership rather than crying wolf', async () => {
    const res = await claim(['advise', '--registry=/proc/nope', '--identity=dc-a', '--port=80']);
    assert.equal(res.registry, false);
    assert.equal(res.mine, true);
  });
});
