#!/usr/bin/env bash
# BeSpunky voice (WSLg audio) — the install entrypoint of a LOCAL devcontainer feature.
#
# The devcontainer CLI copies this directory into the image and runs this script during the
# BUILD, once. It installs the audio ENGINE only; the two halves that make the engine reachable
# — the /mnt/wslg bind mount and the PULSE_SERVER / BESPUNKY_VOICE environment — are declared in
# this feature's devcontainer-feature.json, which is the entire reason voice is a feature at all.
# Packages without the socket are mute, and the socket without packages has nothing to play
# through; as one unit, opting into voice is adding one line to `features` and can never again be
# half-applied.
#
# BESPUNKY_VOICE=1 (declared in the json, not here) is a DECLARATION that replaces an INFERENCE.
# post-create.sh detects voice today by testing `[ -d /mnt/wslg ]` — inferring intent from a side
# effect of one host's mount, because it had no flag to read. post-create now gates on
# ${BESPUNKY_VOICE:-} instead and asks the question it actually means: was voice requested?
#
# It runs as ROOT. There is no `sudo` anywhere below — deliberately, not as an omission:
# post-create.sh calls sudo because it runs as the `node` remote user, and copying that habit
# here would depend on a sudo binary and a sudoers rule that a feature has no business assuming.
#
# Generated by @bespunky/nx-tools:devcontainer. Edit the template in the toolkit, not this copy —
# every `scaffold.sh --sync` regenerates this file and a hand edit here is silently discarded.
set -eu

# apt must never stop to ask a question during a build: there is no terminal to answer on, and a
# package whose postinst opens a dialog would hang the build until the daemon times it out.
export DEBIAN_FRONTEND=noninteractive

# The package list — ONE variable, so the hand-recovery command printed on failure is DERIVED
# from it rather than retyped. post-create.sh states that rule and earned it: a re-run instruction
# that has drifted from what the step installs is worse than none. Kept POSIX (a plain string, not
# an array) so this file survives being invoked as `sh install.sh` by a CLI or base image that
# ignores the shebang.
#
# espeak-ng is the free TTS floor the bespunky-voice plugin speaks through; pulseaudio-utils
# supplies `paplay`, the client that pushes that audio at the PulseServer socket the mount
# exposes. Piper (the natural-voice upgrade) is deliberately NOT here — it is a large model
# download and a machine-local opt-in via the plugin's install-piper.sh, so it stays out of every
# image build.
VOICE_PACKAGES="pulseaudio-utils espeak-ng"

echo "[voice] provisioning the voice engine (espeak-ng + pulseaudio-utils)"

# Retry with backoff — 3 attempts, 10s then 20s. Not defensive padding: WSL+Docker DNS is
# intermittently flaky (getaddrinfo failures on an otherwise-working network, where the very next
# attempt succeeds), and apt's own retry gives up far too fast to outlast the blip.
#
# Correct under `set -e` because the command runs as an `if` CONDITION: errexit is suppressed for
# the condition of a compound command, so a failed attempt lands in the loop instead of killing
# the script. Written any other way — a bare command plus `$?` — the first failure would abort
# before the retry it exists for.
voice_apt_ok=0
for attempt in 1 2 3; do
  # $VOICE_PACKAGES is deliberately UNQUOTED: word-splitting into one argument per package is the
  # point. Safe because every member is a Debian package name — no whitespace, no globs.
  # shellcheck disable=SC2086
  if apt-get update && apt-get install -y $VOICE_PACKAGES; then
    voice_apt_ok=1; break
  fi
  if [ "$attempt" -lt 3 ]; then
    echo "[voice] apt install attempt $attempt/3 failed (often transient WSL/Docker DNS); retrying in $((attempt * 10))s..."
    sleep "$((attempt * 10))"
  fi
done

if [ "$voice_apt_ok" = 1 ]; then
  echo "[voice] voice engine ready (espeak-ng floor; run the plugin's install-piper.sh for the neural-voice upgrade)"
  exit 0
fi

# ---------------------------------------------------------------------------------------------
# THE ONE DESIGN POINT IN THIS FILE: we warn LOUDLY and exit 0 — we never exit non-zero.
#
# A feature's install.sh returning non-zero FAILS THE ENTIRE CONTAINER BUILD. Losing the whole
# container — editor, shell, workspace, and the means to fix it — because an OPTIONAL convenience
# could not reach a Debian mirror is the wrong trade by a wide margin, and the failure is usually
# a DNS blip that would be gone by the time the developer read the error. The house stance
# everywhere in post-create.sh is the same one, for the same reason, and it is a real tradeoff
# taken deliberately, not laziness: a half-provisioned container beats no container.
#
# What we give up by exiting 0 is the build-time guarantee — the container comes up with the
# mount and BESPUNKY_VOICE=1 set, so everything downstream believes voice is available, and the
# failure resurfaces later as `/voice` producing silence. That is why the warning is LOUD, says
# exactly what still works and what does not, and prints the exact command to finish the job —
# derived from $VOICE_PACKAGES, never retyped. A silent exit 0 would be the indefensible version
# of this; a loud one hands the developer a working container and a one-line repair.
# ---------------------------------------------------------------------------------------------
echo "[voice] ================================================================================"
echo "[voice] WARNING: voice engine install failed after 3 attempts — likely a transient"
echo "[voice]          network/DNS issue. NOT failing the container build: a container without"
echo "[voice]          a voice engine beats no container at all."
echo "[voice]"
echo "[voice]          The WSLg audio bridge (mount + PULSE_SERVER + BESPUNKY_VOICE) IS in"
echo "[voice]          place, so nothing else needs redoing — but /voice will be silent until"
echo "[voice]          these two packages are present."
echo "[voice]"
echo "[voice]          Finish this one step from a shell in the container once the network"
echo "[voice]          settles (as root, or prefix with sudo as the 'node' user):"
echo "[voice]            apt-get update && apt-get install -y $VOICE_PACKAGES"
echo "[voice] ================================================================================"
exit 0
