#!/usr/bin/env bash
# BeSpunky devcontainer post-create.
#
# Runs ONCE after the container is built (or rebuilt). Owns all multi-step setup that doesn't fit cleanly as a
# devcontainer "feature" — the project's dependencies, the Claude Code plugin pre-install, any OS package the image lacks and
# whatever tooling this project's LAYERS bring.
#
# COMPOSED, not static: every section below was contributed by one of this project's layers ({{LAYERS}}), and an
# upgrade recomposes the whole file from the layers it detects. Add a layer (Firebase, a web app, …), re-run
# `house.sh upgrade`, rebuild — its steps appear here; a layer that leaves takes its steps with it.
#
# Generated by @bespunky/nx-tools:devcontainer. Edit the template in the toolkit,
# not this copy.
set -euo pipefail

# Devcontainer-cli runs postCreateCommand from the workspace root.
WS="$(pwd)"
# The user this container runs as, and its home — read, never assumed: the image decides them
# (`node` on typescript-node, `vscode` on the neutral devcontainers base).
ME="$(id -un)"
ME_GROUP="$(id -gn)"
