<!-- GENERATED by @bespunky/nx-tools · house-doc generator. Regenerated on every `scaffold.sh --repair` to match the installed @bespunky/nx-tools. DO NOT EDIT — hand edits are overwritten; to restore or update, re-run `scaffold.sh --repair`. Project-specific notes live in CLAUDE.md. -->

# HOUSE.md — house tooling & conventions

> BeSpunky house directives + mechanical how-to for this project: the architecture rules, the branch & release workflow, serving, worktrees{{#firebase}}, Firebase{{/firebase}}, Nx, and the co-driven browser. **Generator-owned — never hand-edit** (regenerated from `@bespunky/nx-tools` on every `scaffold.sh --repair`). `CLAUDE.md` points here and carries the project-specific notes.

## Architect mentality

Approach every decision — at any scale, from a single function to the whole workspace — as a software architect. Treat **everything as a black box**: a clear boundary, a small deliberate public contract, hidden internals, dependencies received from the outside, and connections to other black boxes only through well-defined, intentionally-directed connection types (dependency injection, parent–child, layered/domain-driven dependency rules). Never reach across a boundary into another box's internals. **Place every element on purpose** — every line, `if`, constant, config, abstraction, and dependency is there deliberately; put each concern where it *belongs* (the place dedicated to it), never merely where it "fits" or happens to work. Model the missing **concept** instead of working around gaps; concentrate complexity so the edges stay simple; refuse false tradeoffs; keep abstractions empowering and honest; design for the next consumer; lead with *why* and one consistent mental model; **build for the goal, not the brief** — a request is a pointer to an outcome, so deliver the outcome (including the surrounding pieces the user implied), generalize examples to the class they represent, and resolve ambiguity by reasoning over the context rather than waiting for a fully-specified brief; and **go the extra mile — always** (find or invent the elegant solution; never settle for the easy-but-complex; *easy ≠ simple*). Be lazy about repetition — **automate every repeated process** (never do the same thing by hand twice; derive from a single source of truth and make it runnable in one step) — and relentless about design quality.

For the full mindset, think with the **`bespunky-engineering:architect-mentality`** skill. It is the *why*; the section below is the *operational rule* that enforces it.

## Architecture-first (non-negotiable)

Every change — feature, bug, edge case, or "quick fix" — is solved through **design and infrastructure, never a patch.** No special-case `if`s keyed on one input/customer/env, no magic values, no copy-paste, no boolean flags to make one unit do two things, no casts to silence a type mismatch, no bumped timeouts to mask a structural problem. **For bugs, find and fix the root cause — never mask the symptom** (no swallowed errors, defaulted bad data, or guards bolted on at the symptom site). When the current design does not account for a requirement, **redesign and refactor** the relevant seam (model the missing concept, extract, decouple, build the missing abstraction, reuse) so the new behavior is a natural case of the design — don't bolt it on. Coupling, duplication, and special-casing must never grow. **If a refactor is needed to lay infrastructure for a feature or to fix a bug, design it first, get confirmation, and only then implement** — never refactor ad hoc mid-edit; if a correct redesign is genuinely large, surface it and its cost rather than patching silently.

For any non-trivial change, invoke the **`bespunky-engineering:architecture-first`** skill before writing code — it carries the full loop, the bug root-cause and refactor gates, the patch smells to refuse, and the redesign moves.

## Redesign means rethink

When asked to **redesign** any UI — a layout, screen, page, component, or flow — treat it as a **complete creative reconception from scratch**, never a modification or reskin of what exists. The existing implementation has **zero design authority**: do **not** read it to inform the new design, and don't even look at it before conceiving the new one. Reconceive the **form** from the intent, the requirements, and the feeling; honor the **purpose** (what the thing is for, its data and functionality), which comes from the spec and the user — never reverse-engineered from the old layout. Read the existing code **only after** the new design exists — to plan what to clean up, overwrite, or migrate, and to confirm what functionality must survive — then build the new design cleanly and **remove the old**. (A *targeted tweak* — "move this button", "change this colour" — is **not** a redesign; don't inflate it into one.)

For any redesign, invoke the **`bespunky-product-ux:redesign-means-rethink`** skill — the entry gate to the experience-design trio (`envision-the-experience` → `stage-the-vision` → `realize-the-vision`, run from scratch).

## Stack

- **Monorepo**: Nx, integrated layout (`apps/` + `libs/`).
- **Framework**: Angular (clean `--minimal` app; no demo content).
- **Package manager**: yarn.
- **Dev environment**: devcontainer on `mcr.microsoft.com/devcontainers/typescript-node` (Node from the base image) with the Claude CLI and Claude VS Code extension. `.claude` is persisted across container rebuilds.

## Serving the app

`nx serve <app>` is the one command for local dev — a single **`@bespunky/nx-tools:serve`** orchestrator that composes, in parallel under one Ctrl+C:

- the **app dev-server** (the `dev-server` target → `@angular/build:dev-server`, host `0.0.0.0`), and
- the **shared co-driven browser** — a real Chromium *inside the container* that it brings up and navigates to your app, so you and Claude watch and drive the same instance together{{#firebase}}, and
- the **Firebase emulator suite** (this is a Firebase workspace — see below){{/firebase}}.

It auto-derives a **port offset** from the tree you're in — the **main tree is always offset 0** (app on `http://localhost:4200`); each git worktree gets its own stable, verified-free port block — and registers a pretty **`<slug>.localhost`** domain for the app.

| Flag | Effect |
| --- | --- |
| `--configuration=production\|development` | dev-server variant (Angular's canonical env-file replacements; default `development`). |
| `--no-shared-browser` | serve without bringing up / navigating the shared browser. |
| `--worktree=<branch\|slug\|path>` | serve a worktree you're **not** cwd'd into (see *Serving an in-flight worktree* below). Omit → current tree; pass it empty in a TTY → interactive picker. |
| `--port-offset=auto\|<n>` | `auto` (default) derives the block from the tree; `0` pins the base ports; an int pins a specific block. |
{{#firebase}}| `--no-emulators` | serve the app **alone**, every Firebase service resolved **real** (`?emulate=none`) — no suite booted. |
{{/firebase}}| `--dry-run` | print the resolved tree, offset, port, slug, layers, and URLs — run nothing. |

### Two ways to view the running app

1. **The shared browser (default, blessed)** — a real containerized Chromium you watch over **noVNC at `http://localhost:6080`** in any host tab; Claude attaches to the *same* instance over loopback CDP to co-drive. This surface works for **every** tree — main and worktrees alike.
2. **A host browser tab** — `:80` (the worktree-domains proxy) and the base `http://localhost:4200`{{#firebase}} (+ emulator){{/firebase}} ports are forwarded, so you can open any tree's app in a host tab: the pretty **`<slug>.localhost`** URL routes through the proxy to whichever tree is served. The **main tree** works fully there.{{#firebase}} For a **worktree**, the app loads but its *shifted emulator ports* aren't forwarded — Firebase calls only connect inside the shared browser (loopback), so use the shared browser for the full worktree experience.{{/firebase}}

Each worktree serve gets a pretty **`<slug>.localhost`** domain (browsers auto-resolve any `*.localhost` to loopback; the in-container proxy on the forwarded `:80` routes it to that tree's app) plus a **per-worktree tab title and tinted favicon**, so several co-driven worktrees stay visually distinct.

### Observe-only etiquette (co-driving)

The shared browser is one instance you and Claude share. Before Claude asks *you* to complete an interactive step it can't do for you — a real OAuth sign-in, a captcha, anything needing your credentials — it runs **`shared-browser observe`** so its own automation refuses to navigate/click/type and won't move the view under your hands; it runs **`shared-browser resume`** once you're done. Full co-drive mechanics live in the **`bespunky-browser-automation:shared-browser`** skill.

{{#firebase}}
## Firebase

This project was scaffolded with `--firebase`, so **`nx serve <app>` boots the emulator suite alongside the app** (and the shared browser) — offline, no `firebase login` / cloud project / `.firebaserc` needed (project id derived from `environment.ts` — `demo-<workspaceName>` by default). **Local dev is not forced through the emulators** — tune what's emulated with one flag, or with the per-service knobs below:

| Command | What it does |
| --- | --- |
| `nx serve <app>` | App **+ emulator suite + shared browser**, in parallel, offline. The full local Firebase stack. |
| `nx serve <app> --no-emulators` | App **alone, no emulators** — every service resolved real (`?emulate=none`); e.g. pure UI work, or a real/staging backend. |
| `nx run firebase:emulators` | The emulator suite **alone** (restart/run it independently of the app). |

The `@bespunky/nx-tools:serve` executor runs the emulator suite alongside the app `dev-server` (pinned to the emulator env by default) as one parallel run. The Nx TUI is disabled in `nx.json` so both stream plain prefixed logs and one Ctrl+C stops everything.

### Per-service emulator toggling

You don't have to emulate everything or nothing — each Firebase service is independently emulated-or-real, so you can run e.g. **Firestore on the emulator but real Auth**.

- **Committed default (whole team):** the `EMULATE` map at the top of `apps/<app>/src/environments/environment.ts`. Flip any service to `false`, save, the dev server hot-reloads (~1s).
- **Per session (just you, no rebuild):** override via URL query or localStorage —
  - `?emulate=firestore,storage` → ONLY these emulated this tab (others real); `all` / `none` work too
  - `?real=auth` → force Auth to the real backend this tab
  - `localStorage.setItem('emulate','firestore')` → persist per browser (`removeItem('emulate')` to drop it)
  - precedence (later wins): committed default **<** localStorage **<** URL query

**Turning a service real needs real credentials.** A service resolved to real uses the `firebase` block of the active environment file — the `demo-<workspaceName>` values only work against the emulator. Fill `firebase` with your real/**staging** web config (`firebase apps:sdkconfig WEB <appId> --project <staging>`; never production for anything you write to). **If you forget, a dev-only `ngDevMode` guard (stripped from prod) logs a loud `firebase.config.ts` console error at bootstrap** naming the real-but-demo-configured services — so the cause is up front instead of only a cryptic `auth/api-key-not-valid` later. It logs rather than throws: the app still loads (one misconfigured service shouldn't brick the whole dev app), but that service won't authenticate against the real backend until you fill in real config. One coupled caveat, now handled for you: a real `projectId` is then also used by any *still-emulated* services (`singleProjectMode`), so the emulator suite must run under it too — `tools/emulators.sh` does this automatically by deriving its `--project` from `environment.ts` (override with `FIREBASE_EMULATOR_PROJECT`). The resolver is `apps/<app>/src/app/emulator-overrides.ts` (generator-owned); `firebase.config.ts` applies `committed-default ⊕ override` per service, gated on `ngDevMode` — Angular's dev-mode flag, which the optimizer folds to `false` in production builds, so the resolver, the per-service wiring, every `connect*Emulator(...)` call, and all emulator addresses are tree-shaken out of the prod artifact. (Firebase's own SDK still carries its internal emulator support — that's library code, not ours.)

`nx serve <app> --no-emulators` is the extreme of the same knob: **no** emulator suite booted and **every** service real. It carries `?emulate=none` to the app (the `emulator-overrides.ts` resolver maps `none` / `real=all` → all services real) and, like the per-service toggles above, resolves each service against `environment.ts`'s `firebase` block — the same "go real" path, no separate `no-emulators` environment file or build configuration.

### Cloud Functions (apps/functions)

Cloud Functions are a first-class Nx app: `nx build functions` (esbuild) bundles `apps/functions/src/main.ts` into `dist/apps/functions` with a generated deploy-manifest `package.json`; the emulator and `firebase deploy` both consume that dist output (`firebase.json` → `functions.source`). Runtime deps (`firebase-admin`/`firebase-functions`) live at the **workspace root** — no per-project `node_modules`. Deploy with `nx run functions:deploy`. **Platform firewall (ESLint-enforced):** `platform:web` projects must never import `firebase-admin`/`firebase-functions`; `platform:server` projects (`functions`, `firebase`) must never import `firebase`/`@angular/*`. Tag new libraries accordingly.

**Functions secrets (`defineSecret`).** Secret values live in `apps/functions/.secret.local` — **gitignored**; copy `.secret.local.example` and fill it. One source of truth, two sinks: `tools/emulators.sh` injects it beside the local bundle so the **emulator** reads it, and `yarn nx run functions:push-secrets` sets each `KEY` in **Google Secret Manager** for production (values piped via stdin — never on a command line or in a log). Add a `KEY=VALUE` when your functions call `defineSecret('KEY')`, then re-push and redeploy.

### Emulator seeds, caching & reset (no re-onboarding each serve)

The emulators **persist and seed their data**. The launch path is `tools/emulators.sh` (all `firebase:emulators*` targets funnel through it): it reaps stale processes, primes the **gitignored working dir** `.emulator-data/` from a seed, then starts the suite with `--import .emulator-data` and (full runs only) `--export-on-exit .emulator-data`. So session + data **cache across serves**: onboard once, stay in. Sign in with a seeded email and the Auth emulator matches the existing account by email — you inherit the seeded uid and its docs.

- **Seeds** are committed, known-good worlds under `tools/emulator-seeds/` (see its README for the catalog). They are **generated artifacts**, never hand-edited.
- **Reset (on-call):** `yarn nx run firebase:reset` — takes effect on the next serve. Add `reset:<seed>` targets in `firebase/project.json` for extra worlds.
- **Rebuild seeds:** `yarn nx run firebase:seed:build`.

**Directive — the seed is part of the schema contract.** The seeds' single source of truth is the **declarative** `tools/seed/world.mjs` (a description of accounts + Firestore docs, applied by a generic encoder — adding a field/collection/world is purely additive; the build orchestrator derives the seed list from it). **Whenever a Firestore document shape changes or a feature gains a backend, update the matching world in `world.mjs` and rebuild, committing `tools/emulator-seeds/`** — so the seed never drifts from the code.

### Auth in the devcontainer (the good news)

The shared co-driven browser is **real Chromium with a real window manager**, running inside the container and hitting **container-localhost directly** — so the old devcontainer OAuth pain is *gone*, and the previous "prefer redirect / popups fail" guidance no longer applies:

- **`signInWithPopup` works**, and so do redirect flows. There's no forwarded-port origin boundary between the browser and the app any more, so the `Sending authEvent failed` popup failure is gone — you don't have to prefer `signInWithRedirect`.
- **`environment.ts` still ships an `authDomain`** — required for any OAuth provider sign-in (popup *and* redirect refuse without it, even against the Auth emulator). Don't remove it.
- **VS Code Simple Browser / a host browser are now only *viewers*** of the shared browser over noVNC (`:6080`) — they no longer have to *complete* the OAuth flow themselves; the containerized Chromium does. They stay fine for viewing.
- **Emulator auth works from anywhere** — any origin, any tree, including the pretty `<slug>.localhost` domains and offset ports.
- **Real Google OAuth is pinned to the main-tree serve on `http://localhost:4200`.** That exact origin/redirect URI is the one registered in the Google OAuth client; worktree offset ports and the `<slug>.localhost` domains are **not** registered, so real Google sign-in only works on the main tree at `:4200`. To enable it, add `http://localhost:4200` to both **Authorized JavaScript origins** and **Authorized redirect URIs** on the OAuth 2.0 client in Google Cloud. For worktrees, use the Auth **emulator** (it authenticates anywhere).

The devcontainer forwards the base dev-server + emulator ports to the **same host ports** (`forwardPorts`) — if you re-port an emulator, update `firebase.json`, `environment.ts`, AND `.devcontainer/devcontainer.json` together. When Claude needs *you* to complete a real OAuth sign-in in the shared browser, it enters **observe-only** (`shared-browser observe`) first so it won't move the view under you, and **resumes** after.

**When the user asks to deploy this app — or otherwise connect it to a real Firebase project — walk them through these steps** (from the workspace root inside the devcontainer, where the Firebase CLI is installed). The BeSpunky default is Firebase **App Hosting** (framework-aware; config in `apphosting.yaml`), not classic static Hosting:

1. `firebase login` — one-time auth against their Google account (opens a browser).
2. `firebase use --add` — picks a project from their account and writes `.firebaserc`. If they don't have a project yet, create it first (Firebase console or `firebase projects:create <id>`).
3. `firebase apphosting:backends:create --project <projectId>` — one-time: creates the App Hosting backend (interactive — picks region and **links a GitHub repo**). **Link the repo this project was scaffolded with** — that linkage is what sets up deploy CI: Firebase provisions its own Cloud Build pipeline and auto-deploys on every push to the configured branch.
4. `firebase apps:sdkconfig WEB <appId> --project <projectId>` — prints the real web config for client-side SDK init.
5. Paste the returned `firebaseConfig` fields into `firebase` in **`apps/<APP>/src/environments/environment.prod.ts`** — the production environment file, which the Angular build swaps in for `environment.ts` via `project.json`'s `targets.build.configurations.production.fileReplacements` (Angular's canonical environment-files pattern). Never edit `apps/<APP>/src/app/firebase.config.ts` — that's structural code the generator owns end-to-end.

After the backend is created, **App Hosting deploys are GitHub-driven**: pushing to the configured branch triggers a Cloud Build → Cloud Run deploy. Tweak build/runtime behavior in `apphosting.yaml` at the workspace root.

**The CI/deploy pipeline is Firebase's, not ours.** This project ships **no GitHub Actions deploy workflow** — linking the repo at step 3 hands CI/CD to Firebase's GitHub integration, which creates and maintains the Cloud Build config. That's deliberate: it means deploys keep working as Firebase evolves its mechanism, with nothing in this repo to update. (The project's GitHub repo is created automatically at scaffold time, so it already exists to be linked.)

**Never fabricate `.firebaserc` or the production config** — the Firebase CLI is the source of truth for cloud state. `provideAppFirebase()` throws at bootstrap if production is attempted with an empty `environment.firebase`, so silent broken deploys are impossible. Inside the devcontainer, **every interactive terminal shows a self-extinguishing banner** (`tools/firebase-welcome.sh`, sourced via `/etc/profile.d/zz-firebase-welcome.sh`) reminding the user of the recipe until setup is complete — when both `.firebaserc` exists and `environment.firebase.projectId` in `environment.prod.ts` is filled, the banner goes silent automatically. The same recipe also lives in the header of `environment.prod.ts` and in the `bespunky-project-starter:new-project` skill.

### Staging environment & per-environment Firestore database

A first-class **staging** environment is opt-in — `scaffold.sh --repair --firebase --staging` (or `nx g @bespunky/nx-tools:firebase-emulators --project=<app> --staging`). It scaffolds **`environment.staging.ts`** (swapped in by a `staging` build configuration in `project.json`) and **`apphosting.staging.yaml`**, which tells the App Hosting backend named `staging` to build `nx build <app> --configuration=staging` instead of the framework-default prod build — otherwise the staging backend silently ships **prod's** config. Bind it once at backend-create: `firebase apphosting:backends:create … --environment staging`.

**Isolating staging's data** — the `firebase.databaseId` field (in the Environment interface) picks which Firestore database a build targets. Set it (e.g. `databaseId: 'staging'` in `environment.staging.ts`) and `firebase.config.ts` uses `getFirestore(app, databaseId)` instead of the `(default)` DB. To turn it on: create the named DB in the console, set `databaseId`, and add it to `firebase.json`'s `firestore` array (`[{ "database": "(default)", … }, { "database": "staging", … }]`).

> **Caveat — same-project isolation is Firestore-only.** A named database isolates *client-written* data, but Auth users are shared (same project = one user pool), and the single shared Cloud Functions deployment writes via the Admin SDK's default `getFirestore()` → the `(default)` DB, so anything a callable persists still lands in prod. Full isolation (its own Auth pool + functions) needs a **separate Firebase project** — a deliberate step up in operational cost.

### Cloud Functions: callables proxy & region

Callables run through the **dev-server's own origin**, not a directly-dialed emulator port. `environment.ts` marks the functions emulator `proxied: true`, so `firebase.config.ts` connects it to the app's origin and the generated **`apps/<APP>/proxy.conf.mjs`** relays `/<projectId>/**` to the Functions emulator — **shifted by `PORT_OFFSET`**. Two failure classes disappear: a **squatted or forwarded `:5001`** on the host (common on Windows — a squatter that accepts TCP but never answers hangs every callable until the ~70s deadline, while Firestore/Auth stay fine) can't stall callables, and a **worktree can't silently relay its callables to another tree's emulator**. The serve executor auto-wires the proxy for a Firebase serve; pass your own `--proxyConfig` to override, or set `proxied: false` to dial the emulator port directly.

**Region** — pin callables to a region with `firebase.functionsRegion` (e.g. `'europe-west1'`) in an environment file; `firebase.config.ts` reads it for `getFunctions(app, region)`. Like `databaseId`, it's *configuration*, so it never means hand-editing the config file.

**`firebase.config.ts` is generator-owned and rewritten in full on every `--repair`** — it holds no per-project values by design, so there's no "is it customized?" guess to freeze it behind template improvements. Change behavior where it belongs: **config** (emulator toggles, the `firebase` web config, `databaseId`, `functionsRegion`, functions `proxied`) in `environment.ts` / `environment.<env>.ts`; **providers** in `app.config.ts` beside `provideAppFirebase()`. Editing `firebase.config.ts` directly means the next repair silently reverts it.
{{/firebase}}

## Branch & release workflow (non-negotiable)

**You MUST invoke the `bespunky-workflow:branch-and-release` skill before any git branch, worktree, integration, promotion, or release action — this is mandatory, not a recommendation.** The skill is the operative procedure (the relevance check, per-feature git worktrees + the Nx-root override, the rebase-and-re-verify divergence rule, and the three human-gated promotions with their exact commands), not a reference to consult when convenient. Performing any of those steps from memory — skipping the skill — is a process violation; the skill is the always-on, **auto-updating** source of truth and supersedes any recollection of the flow. The project-specific parameters below are what it reads. The always-on *rules* it enforces:

- **Step 0, every request — decide related vs. unrelated BEFORE touching anything.** Consciously judge whether the request continues the *current* worktree's in-flight work or is something else (a different feature/bug, tooling, docs). **Related** → keep working in the current tree. **Unrelated** → **open a new worktree off `development` and do all of it there** — don't ask, and don't "just start" in the current tree meaning to relocate later. This classification is a precondition for touching files, never a cleanup step; never pile unrelated changes onto an in-flight branch.
- **Never commit directly onto `development`, `staging`, or `main`** — they advance only by merging the branch directly upstream, so promotions stay clean fast-forwards.
- **Commit small increments as you work in the worktree** — after each coherent, working step (a passing test, a completed sub-step), not one giant commit at the end. Each commit is a restore point and keeps rebases cheap; the `--no-ff` merge into `development` groups them into one revertable unit, so you get granular *and* grouped.
- **Nothing promotes on its own.** Only the relevance check + worktree creation are automatic; every downstream move (feature→`development`, `development`→`staging`, `staging`→`main`) waits on your explicit signal.

**The four branches** — work flows one way, `feature` → `development` → `staging` → `main`, each a strict ancestor of the next:

| Branch | Role |
| --- | --- |
| `development` | integration — all ongoing/finished work not yet promoted |
| `staging` | pre-production / release-candidate line |
| `main` | production / released line |

{{#firebase}}
**Deploy binding (this project):** `staging` and `main` each track a Firebase App Hosting environment — pushing either triggers an auto-rollout (`staging` → staging, `main` → production). `development` tracks **no** environment, so pushing it does **not** deploy. (Production is `main`; App Hosting's prod backend tracks it — "master" in conversation means `main` here.) The topology is set up when the repo is linked at `firebase apphosting:backends:create` (see the Firebase deploy recipe above).
{{/firebase}}
{{^firebase}}
**Deploy binding (this project):** none yet — no deploy target is wired. `staging` and `main` are promotion checkpoints kept ready to bind to a deploy mechanism (Firebase App Hosting, a CI workflow, a container push, …): bind it to fire on push to `staging` for staging and `main` for production. Until then the pipeline is pure branch hygiene.
{{/firebase}}

**Serving an in-flight worktree** — the same `nx serve <app>` serves a tree you're **not** cwd'd into via `--worktree`, so an in-flight feature is testable in the real app before it's promoted, without merging it back:

```bash
nx serve <app>                              # serve the tree you're in (main → base ports; a worktree → its own offset block)
nx serve <app> --worktree=<branch|slug>     # serve another worktree (pass --worktree empty in a TTY for an arrow-key picker)
nx serve <app> --port-offset=auto           # ISOLATED: own verified-free port block, coexists with a running serve
nx serve <app> --dry-run                    # print what it would serve, without serving
```

It installs the worktree's deps on first serve and applies the `NX_WORKSPACE_ROOT_PATH` / `NX_DAEMON=false` overrides for you. A worktree serve shifts the **whole stack** (app dev-server{{#firebase}} **and** the emulator suite{{/firebase}}) onto the worktree's stable, verified-free offset block, so it never collides with a server on the base/forwarded ports. **A worktree serve is `:6080`-only** — its shifted ports aren't forwarded, so watch it in the shared browser over noVNC (the executor navigates it to the worktree's pretty `<slug>.localhost` domain), not a host tab. (A worktree serve does **not** reliably hot-reload — restart after each edit; the skill covers this and the promotion mechanics in full.)

## Generator-first, manual last

For anything Nx can generate - apps, libraries, components, services, project config - **use the Nx generator (`nx g ...`); never hand-create and fill files.** Before hand-writing anything structural, check what exists: `nx list <plugin>` / `nx g <generator> --help` (or the `nx-generate` skill / the Nx MCP server). Only fall back to manual file creation when no generator covers the task. **Never guess flags** - verify against `--help` / `nx_docs`.

## Common Commands

```bash
# Generate the next Angular app or library (generator-first!)
# Apps go through the HOUSE generator, never raw @nx/angular:application. It applies the
# BeSpunky per-app config the raw generator omits — dev-server host 0.0.0.0, and (when this
# is a Firebase workspace, auto-detected from firebase.json) the full per-app Firebase wiring.
# Same one command, same code path the scaffolder used for the first app, so a second app is
# configured identically. No flags needed; Firebase is detected automatically.
yarn nx g @bespunky/nx-tools:app apps/<app-name>
yarn nx g @nx/angular:library libs/<lib-name>

# Serve / build / test / lint a project
yarn nx serve <project>
yarn nx build <project>
yarn nx test <project>
yarn nx lint <project>

# Run a target across everything affected by your changes
yarn nx affected -t build test lint
```

## Working with Nx

- For navigating/exploring the workspace, invoke the `nx-workspace` skill first - it has patterns for querying projects, targets, and dependencies.
- When running tasks (build, lint, test, e2e, etc.), always prefer `nx` (`nx run`, `nx run-many`, `nx affected`) over the underlying tooling directly.
- Prefix nx commands with the workspace package manager (`yarn nx ...`) - avoids the globally installed CLI.
- You have access to the Nx MCP server and its tools - use them.
- For Nx plugin best practices, check `node_modules/@nx/<plugin>/PLUGIN.md` (not all plugins have it - proceed without if absent).
- For scaffolding (apps, libs, structure), invoke the `nx-generate` skill FIRST before exploring or calling MCP tools.

## Angular AI tooling (MCP + agent skills)

This project ships Angular's official AI tooling, wired in two layers that complement each other:

- **Angular CLI MCP server** — declared in project-scoped `.mcp.json` (`npx -y @angular/cli mcp`, always the latest CLI, no version to maintain). It exposes Angular's **knowledge tools**: `get_best_practices`, `search_documentation`, `find_examples`, `ai_tutor`, and `onpush_zoneless_migration`. **Treat these as the source of truth for current Angular guidance** — signals, `linkedSignal`, `resource`, Signal Forms, the built-in control flow, zoneless/OnPush, SSR, ARIA — rather than training-data recall, which lags the framework. The server's *experimental* exec tools (`build`, `devserver.*`, `test`, `e2e`) are deliberately **not** enabled: this is an integrated Nx workspace with **no root `angular.json`**, so those tools (which read `angular.json` and shell out to `ng build`/`ng serve`) can't function here and would only pull you off the Nx-owned targets. Build / serve / test verification belongs to **Nx** (`yarn nx build|serve|test`) and the Playwright skill — never the Angular CLI directly.
- **Angular agent skills** — `angular-developer` and `angular-new-app` are fetched fresh from `github.com/angular/skills` into `.claude/skills/` on every container build (gitignored — a refreshable cache that tracks upstream, never a vendored fork). They load automatically and carry idiomatic, version-aware Angular patterns. **One reconciliation:** those skills are Angular-CLI-centric (they reach for `ng new` / `ng generate`); in this workspace you **always go through Nx instead** — `yarn nx g @nx/angular:application|library|component …`, `yarn nx build|serve|test` — per **Generator-first** above. Take their *Angular* guidance; ignore their *`ng` invocation* mechanics.

## Playwright (available out of the box)

This devcontainer ships with **Chromium + Playwright pre-installed** (the devcontainer's `post-create.sh` runs `playwright install --with-deps chromium` when it detects `@playwright/test` in `package.json`, and the browser binary is cached in a per-workspace volume so rebuilds don't re-download). You can drive a real browser from a Bash script today — no `playwright install`, no apt step, no `sudo`.

Use Playwright whenever you need to **observe** or **drive** the running app instead of reasoning about source: verify a UI change end-to-end, reproduce a user-reported bug in the actual browser, capture before/after screenshots, scrape Angular-rendered output, or generate test scaffolding via codegen. Always headless — there is no display in the container.

For the canonical patterns (when to choose Playwright vs. the `Claude_Preview` / `Claude_in_Chrome` MCPs, how to write a headless script, how to capture and feed back screenshots, common pitfalls), invoke the **`bespunky-browser-automation:playwright`** skill before reaching for any browser-side check.

## Local servers — never clobber a running server (non-negotiable)

**When you start a server to test a change, you MUST bind it to a random free port — never the default (`4200`{{#firebase}}, or the emulator ports `8080`/`9099`/…{{/firebase}}) or any container-forwarded port.** Those belong to whatever server the developer launched manually; grabbing them fails, silently attaches, or forces a disruptive restart. You verify **headless** (Playwright reaches any `localhost:<port>` directly), so you never need the forwarded ports — a random port costs nothing. Read the bound URL from the server's own startup output and point your browser there; tear the server down when done, and **never kill a server you didn't start** to free a port. Full rules — invoke the **`bespunky-workflow:local-server-isolation`** skill.
{{#firebase}}
The emulator suite is the trap: `tools/emulators.sh` **reaps existing emulator processes** on launch, so serving on the base ports (`--port-offset=0`, i.e. the main tree) would kill the developer's running suite (a random *app* port alone doesn't prevent that). The clean fix is to serve **from your feature worktree** — `nx serve <app>` there auto-offsets the entire stack (app + emulators, incl. the hub/logging ports) onto a free block and reaps only *its own* shifted ports, so it coexists with the developer's suite instead of killing it. Watch it in the shared browser over noVNC (`:6080`). (Or, if you only changed the app: reuse the running suite by serving the app alone against it — `--no-emulators` on a shifted block.) Never boot a colliding suite on the base ports.
{{/firebase}}
