#!/usr/bin/env node
// Project what the house must KNOW about Node versions — never typed by hand — into the payload.
//
// WHY: a project declares its Node in the files nvm, fnm, setup-node and Volta already read (`.nvmrc`, `.node-version`,
// package.json `volta.node`), and those speak a GRAMMAR, not just a number: `lts/*`, `lts/jod`, `node`, `22.x`. The
// house tags the devcontainer image with the major, so it has to resolve those — offline, at generation time, and in
// the upgrade's probe before anything is written. And it may only tag an image that EXISTS: Microsoft publishes
// `typescript-node:<major>` for even (LTS-line) majors only, so `.nvmrc = 23` would pass every check and fail at image
// pull. Two upstream sources, projected here:
//   - nodejs.org/dist/index.json → every LTS codename's major, the newest LTS major (`lts/*`), the newest major (`node`);
//   - MCR's tag list for devcontainers/typescript-node → the majors it publishes a bare `:<major>` tag for.
//
// MOVING ALIASES ARE STAMPED. `lts/*` and `node` mean different majors next year; the table records the date it was
// projected (NODE_FACTS_AS_OF), and every message that resolves one through it says "as of <date>". The date moves only
// when the data does, so the check below compares the data, not the calendar.
//
// IT DRIFTS WITH UPSTREAM, BY DESIGN (a new Node major, a new LTS, a new image): the check fails — re-run with --write.
// It runs on a schedule and before every payload publish (.github/workflows/upstream-tables.yml, publish.sh), never in
// the per-push test job, where an upstream release would turn every unrelated PR red.
//
//   node tools/node-facts/project.mjs           check: the generated file matches upstream today
//   node tools/node-facts/project.mjs --write   regenerate it (needs the network)
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..', '..');
const OUT = join(ROOT, 'plugins/house/engine/nx-tools/src/generators/_utils/node-facts.ts');

async function json(url) {
  const response = await fetch(url);
  if (!response.ok) throw new Error(`${url} → HTTP ${response.status}`);
  return response.json();
}

async function nodeReleases() {
  const releases = await json('https://nodejs.org/dist/index.json');
  const lts = {};
  let newest = 0;
  let newestLts = 0;
  for (const { version, lts: codename } of releases) {
    const major = Number(/^v(\d+)/.exec(version)?.[1]);
    if (!major) continue;
    newest = Math.max(newest, major);
    if (codename) {
      lts[codename.toLowerCase()] = major;
      newestLts = Math.max(newestLts, major);
    }
  }
  if (!newest || !newestLts) throw new Error('nodejs.org/dist/index.json: no releases — the projection\'s premise is gone');
  return { lts: Object.fromEntries(Object.entries(lts).sort(([, a], [, b]) => a - b)), newest, newestLts };
}

async function imageMajors() {
  const { tags } = await json('https://mcr.microsoft.com/v2/devcontainers/typescript-node/tags/list');
  const majors = [...new Set(tags.filter((tag) => /^\d+$/.test(tag)).map(Number))].sort((a, b) => a - b);
  if (!majors.length) throw new Error('typescript-node publishes no bare <major> tag — the projection\'s premise is gone');
  return majors;
}

function render({ lts, newest, newestLts }, images, asOf) {
  return `// GENERATED by tools/node-facts/project.mjs from nodejs.org and MCR — never hand-edit; re-run it with --write.
// Import-free on purpose: house.sh's probe loads it (with ./node-spec.ts) before anything is installed.

/** The date this was projected — the moving aliases (\`lts/*\`, \`node\`) mean what they meant on it. */
export const NODE_FACTS_AS_OF = '${asOf}';

/** Every Node LTS codename (lower-case, as nvm's \`lts/<name>\` takes it) → its major, oldest first. */
export const NODE_LTS_CODENAMES: Readonly<Record<string, number>> = ${JSON.stringify(lts, null, 2).replace(/"(\w+)":/g, '$1:')};

/** The newest LTS major (\`lts/*\`) and the newest major of all (\`node\`, \`current\`, \`latest\`, \`stable\`). */
export const NODE_NEWEST_LTS_MAJOR = ${newestLts};
export const NODE_NEWEST_MAJOR = ${newest};

/** The Node majors mcr.microsoft.com/devcontainers/typescript-node publishes a \`:<major>\` image for. */
export const TYPESCRIPT_NODE_IMAGE_MAJORS: readonly number[] = [${images.join(', ')}];
`;
}

const [releases, images] = await Promise.all([nodeReleases(), imageMajors()]);
const previous = existsSync(OUT) ? readFileSync(OUT, 'utf8') : '';
const previousDate = /NODE_FACTS_AS_OF = '([^']+)'/.exec(previous)?.[1];
const today = new Date().toISOString().slice(0, 10);
// The data as of the recorded date: when nothing but the calendar moved, the file is unchanged.
const same = previousDate !== undefined && render(releases, images, previousDate) === previous;
const expected = render(releases, images, same ? previousDate : today);
if (process.argv.includes('--write')) {
  writeFileSync(OUT, expected);
  console.log(same ? `unchanged: ${OUT} (as of ${previousDate})` : `wrote ${OUT} (as of ${today})`);
} else if (!same) {
  console.error(
    `DRIFT: ${OUT} is not what upstream says today (a new Node major or LTS, or typescript-node images moved) — run: ` +
      'node tools/node-facts/project.mjs --write, review the diff, and decide whether existing projects need a migration.',
  );
  process.exit(1);
} else {
  console.log(`ok: the Node facts match upstream (as of ${previousDate})`);
}
