// 0.48.0 — a devcontainer the house wrote stops PULLING its image and BUILDS it from .devcontainer/house.Dockerfile.
//
// WHY. The OS packages were apt-installed by post-create on every container create, so every rebuild paid for them
// again. 0.48.0 builds the image from a generated Dockerfile (FROM the same image) whose package layer Docker caches;
// the devcontainer generator now composes `build` instead of `image`. But its merge never REMOVES a key — so without
// this rung a house-owned devcontainer.json would keep its old `image` next to the new `build`: two image sources.
//
// WHAT IT TAKES: the `image` member (its comma, and the `//` lines directly above it, which explained a key that is
// gone) — only where the HOUSE wrote it (`houseWrote`: the file is owned, or the adoption record says the house added
// exactly this). Any other `image` is left and reported: the generator then records `build` as skipped and says when
// switching is safe. The generator, later in the same upgrade, adds `build` and writes the image files.
//
// WHAT IT REPORTS: an `apt-get`/`apt` install in the project's own `post-create.local.sh` (or a `post-create.sh` the
// house did not write). Those are the project's, so they stay — but they now reinstall on every rebuild while the
// house's packages are a cached layer, and they no longer get the `apt-get update` the old house step ran before them
// on every create. Moving them into `.devcontainer/os-packages.txt` fixes both. A `post-create.local.sh` that is still
// byte-for-byte the 0.47 stub is the house's untouched seed — its example is an apt step the new rule forbids — so it is
// replaced with the current stub.
import { type Tree, logger } from '@nx/devkit';
import { findNodeAtLocation } from 'jsonc-parser';
import { parseJsoncStrict } from '../../generators/_utils/jsonc-strict';
import { removeMemberWithLeadingComment } from '../../generators/_utils/jsonc-remove-member';
import { houseWrote } from '../../generators/_utils/devcontainer-provenance';
import { HOUSE_SCRIPT_MARKER, LOCAL_STUB } from '../../generators/devcontainer/generator';
import { isPresent } from '../../layers/registry';

const TAG = '[0.48.0 build-from-house-dockerfile]';
const DEVCONTAINER = '.devcontainer/devcontainer.json';
const LOCAL = '.devcontainer/post-create.local.sh';
const POST_CREATE = '.devcontainer/post-create.sh';
const SWITCH = '"build": { "dockerfile": "house.Dockerfile", "context": "." }';

/** The seeded post-create.local.sh exactly as 0.47.0 (and every release before it since the seam existed) wrote it. */
const LOCAL_STUB_0_47 = `#!/usr/bin/env bash
# Project-specific devcontainer setup. THIS FILE IS YOURS.
#
# .devcontainer/post-create.sh is generated by @bespunky/nx-tools and is overwritten on every
# \`house.sh upgrade\`. This file is created once and never regenerated, so anything you put here
# survives. It runs LAST, after workspace deps, Claude plugins and every house prerequisite — so you can
# assume a working environment.
#
# Runs in a subshell; a non-zero exit warns rather than failing the container build.
set -euo pipefail

# Example — install a project-specific tool:
# sudo apt-get update -qq && sudo apt-get install -y --no-install-recommends postgresql-client
`;

export default async function buildFromHouseDockerfile(tree: Tree): Promise<void> {
  if (!tree.exists(DEVCONTAINER) || !isPresent(tree, 'agent')) return;
  retireHouseImage(tree);
  reportProjectAptSteps(tree);
}

function retireHouseImage(tree: Tree): void {
  const text = tree.read(DEVCONTAINER, 'utf8') ?? '';
  const root = parseJsoncStrict(text);
  if (!root) {
    logger.warn(`${TAG} Left in place — ${DEVCONTAINER} could not be parsed as JSONC. If the house wrote its "image", replace it with ${SWITCH} by hand.`);
    return;
  }
  const image = findNodeAtLocation(root, ['image']);
  if (!image) return;
  if (!houseWrote(tree, { path: ['image'], value: image.value })) {
    logger.info(
      `${TAG} Left in place — the "image" in ${DEVCONTAINER} is not recorded as house-written (adoptions before 0.41.0 ` +
        `have no record), so it is treated as the project's. The devcontainer generator says, below, whether switching it ` +
        `to the house build is safe.`,
    );
    return;
  }
  const result = removeMemberWithLeadingComment(text, image);
  const after = parseJsoncStrict(result);
  const keys = (node: typeof root) => (node?.children ?? []).map((member) => member.children?.[0]?.value as string);
  const expected = keys(root).filter((key) => key !== 'image');
  if (!after || JSON.stringify(keys(after)) !== JSON.stringify(expected)) {
    logger.warn(`${TAG} Left in place — removing "image" from ${DEVCONTAINER} would not leave the file intact. Replace it with ${SWITCH} by hand.`);
    return;
  }
  tree.write(DEVCONTAINER, result);
  logger.info(
    `${TAG} removed "image": "${image.value}" from ${DEVCONTAINER} — the container now builds from ` +
      `.devcontainer/house.Dockerfile (FROM the same image, the OS packages one cached layer), which the devcontainer ` +
      `generator writes in this same upgrade. Rebuild the container.`,
  );
}

function reportProjectAptSteps(tree: Tree): void {
  const local = tree.exists(LOCAL) ? (tree.read(LOCAL, 'utf8') ?? '') : undefined;
  if (local === LOCAL_STUB_0_47) {
    tree.write(LOCAL, LOCAL_STUB);
    logger.info(`${TAG} refreshed ${LOCAL} — it was still the untouched 0.47 stub, whose apt-get example the new rule retires (OS packages go in .devcontainer/os-packages.txt).`);
  }
  const theirs = [
    ...(local !== undefined && local !== LOCAL_STUB_0_47 ? [[LOCAL, local]] : []),
    ...(tree.exists(POST_CREATE) && !(tree.read(POST_CREATE, 'utf8') ?? '').includes(HOUSE_SCRIPT_MARKER)
      ? [[POST_CREATE, tree.read(POST_CREATE, 'utf8') ?? '']]
      : []),
  ];
  for (const [file, content] of theirs) {
    const steps = content.split('\n').filter((line) => /^\s*[^#\s].*\bapt(-get)?\s+(-\S+\s+)*install\b/.test(line));
    if (!steps.length) continue;
    logger.warn(
      `${TAG} ${file} installs OS packages itself (${steps.length} line${steps.length > 1 ? 's' : ''}, e.g. ` +
        `\`${steps[0].trim()}\`). Left as it is — the file is yours — but move those package names into ` +
        `.devcontainer/os-packages.txt: there they are built into the image as one cached layer, while here they ` +
        `reinstall on every rebuild — and no longer get the \`apt-get update\` the house step used to run before them ` +
        `on every create, so an install without its own update may now fail.`,
    );
  }
}
