// MIGRATION 0.24.6 — delete a `post-create.bespunky.sh` that the beside-path duplication bug left behind.
//
// THE BUG THAT MADE IT. When the devcontainer generator does not own `devcontainer.json`, it refuses to
// overwrite a `post-create.sh` it finds there and writes the house script BESIDE it, as
// `.devcontainer/post-create.bespunky.sh`. The test for "is the house path free?" used to be
// `owning || !tree.exists(HOUSE_PATH)`. On an ADOPTED devcontainer `owning` is permanently false, so from
// the run that first wrote `post-create.sh` onward the generator looked at its OWN output, decided it was
// foreign, and wrote a second copy beside it — re-manufacturing on every sync the exact duplication the
// beside-path exists to prevent. 0.23.0 fixed the test by also accepting a house script that carries the
// generator's own marker line. It fixed the CAUSE. `writePostCreate` has no `tree.delete`, so every copy
// already written stayed exactly where it was, and no later sync will ever touch it again.
//
// This repository is the proof: `014ea0ea` added `.devcontainer/post-create.bespunky.sh` (+353 lines) during
// its own dogfooding sync, and `9323f3df` — the fix commit — removed it BY HAND. Consumers got the fix and
// kept the file.
//
// WHY IT IS WORTH A MIGRATION RATHER THAN A SHRUG. Left alone it is a 350-line file frozen at ≤0.22.0 that
// nothing maintains. That is ugly. The reason it is more than ugly is that the old generator PRINTED, on
// every sync, an instruction to chain it: "add this line to whatever your postCreateCommand does run: bash
// .devcontainer/post-create.bespunky.sh". Anyone who followed that advice now provisions their container
// twice — once from a current `post-create.sh`, once from a frozen copy that predates 0.23.0's marketplace
// self-adaptation and will therefore install the PUBLISHED plugins over a working tree. And anyone who edits
// the wrong one of the two files is editing a script that never runs.
//
// REGISTERED ABOVE THE FIX, not at 0.23.0. A project that has already synced past 0.23.0 still carries the
// orphan — the fix stopped producing it, it never removed it — so a 0.23.0 key would skip precisely the
// projects that took the fix. Keyed above every published version instead, and a no-op for everyone else.
//
// SELF-CONTAINED by the migration contract: the marker string below is a copy, not an import.
import { type Tree, logger } from '@nx/devkit';

const BESIDE = '.devcontainer/post-create.bespunky.sh';
const HOUSE = '.devcontainer/post-create.sh';
const LOCAL = '.devcontainer/post-create.local.sh';
const DEVCONTAINER = '.devcontainer/devcontainer.json';

/**
 * The provenance line the house `post-create.sh.tpl` has carried since its first commit — verified present in
 * every revision from `9f179a3` through `d0525bc7`. It is what makes "this file is ours to delete" a fact
 * rather than a guess about a filename.
 */
const HOUSE_SCRIPT_MARKER = 'Generated by @bespunky/nx-tools:devcontainer';

export default function removeOrphanedBesidePostCreate(tree: Tree): void {
  // The overwhelmingly common case, and the idempotency fixed point: nothing here, nothing to do.
  if (!tree.exists(BESIDE)) return;

  // Somebody else's file that merely shares the name is not ours to remove. Only a script that declares its
  // own provenance qualifies.
  const beside = tree.read(BESIDE, 'utf8') ?? '';
  if (!beside.includes(HOUSE_SCRIPT_MARKER)) return;

  // IS THE BESIDE PATH THE LEGITIMATE HOME, rather than a duplicate? It is, whenever `post-create.sh` is
  // absent or is somebody else's script — that is the situation the beside-path was designed for, and the
  // file there is then the project's ONLY copy of the house setup. Deleting it would silently remove the
  // provisioning. Only when a house-marked `post-create.sh` exists beside it is this a genuine duplicate.
  const house = tree.exists(HOUSE) ? tree.read(HOUSE, 'utf8') ?? '' : '';
  if (!house.includes(HOUSE_SCRIPT_MARKER)) return;

  // AND IS ANYTHING STILL POINTING AT IT? The old generator told people to chain it by hand, so a reference
  // may be load-bearing. Removing a file something still calls turns a quiet duplicate into a broken
  // container build — a strictly worse outcome than the one being repaired. Detect and report; do not act.
  // (Substring safety: 'post-create.bespunky.sh'.includes('post-create.sh') is false, so these do not alias.)
  const referencedIn = [DEVCONTAINER, HOUSE, LOCAL].filter(
    (path) => tree.exists(path) && (tree.read(path, 'utf8') ?? '').includes('post-create.bespunky.sh')
  );
  if (referencedIn.length > 0) {
    logger.warn(
      `[migrate 0.24.6] \`${BESIDE}\` is a stale duplicate of \`${HOUSE}\`, frozen at the version that wrote ` +
        `it, but it is still referenced in ${referencedIn.map((p) => `\`${p}\``).join(', ')} — so it was LEFT ` +
        `IN PLACE. Remove the line that runs it, then delete the file: keeping it means your container is ` +
        `provisioned twice, once from a script no sync updates any more.`
    );
    return;
  }

  // AND IS THE HOUSE PATH THE ONE THAT ACTUALLY RUNS? The generator only writes to `post-create.sh` when
  // the container INVOKES it; where `postCreateCommand` runs something else entirely, the beside file is the
  // live copy and `post-create.sh` is the stale one — the reverse of the case above. Deleting the beside file
  // there removes the only script the generator still maintains, and the next sync writes it straight back,
  // so it is churn at best and the wrong file at worst. Mirror the generator's own `invoked` test and stay
  // out of it unless the house path is genuinely the one wired up.
  const container = tree.exists(DEVCONTAINER) ? tree.read(DEVCONTAINER, 'utf8') ?? '' : '';
  const houseIsInvoked = container === '' || container.includes('post-create.sh');
  if (!houseIsInvoked) {
    logger.warn(
      `[migrate 0.24.6] \`${BESIDE}\` and \`${HOUSE}\` are both house scripts, but this devcontainer's ` +
        `postCreateCommand runs neither by name — so which one is live cannot be determined and BOTH were ` +
        `left in place. Point postCreateCommand at \`${HOUSE}\` and delete the other.`
    );
    return;
  }

  tree.delete(BESIDE);
  logger.info(
    `[migrate 0.24.6] Removed \`${BESIDE}\` — a duplicate of \`${HOUSE}\` left behind by the beside-script ` +
      `bug, frozen at the version that wrote it and updated by nothing since. \`${HOUSE}\` is the live script.`
  );
}
