# BeSpunky house — the image this devcontainer builds (devcontainer.json → "build").
#
# Generated by @bespunky/nx-tools:devcontainer — regenerated on every house upgrade. Edit the template in the
# toolkit, not this copy. Your OS packages go in os-packages.txt beside it; anything else of your own goes in
# post-create.local.sh.
#
# WHY A DOCKERFILE: Docker caches every layer, so a rebuild reuses each one whose inputs have not changed. The OS
# packages used to be apt-installed by post-create on EVERY rebuild; here they are one layer, rebuilt only when a
# package list changes (or on "Rebuild Without Cache"). Devcontainer features are applied on top of this image.
#
# Claude Code is deliberately NOT installed here: its auto-updater updates it inside the running container, so a
# cached layer would hand back the build-day version on every rebuild. It lives in ~/.local, a persisted volume.
FROM mcr.microsoft.com/devcontainers/typescript-node:22

COPY os-packages.sh os-packages.txt /tmp/bespunky-os-packages/
RUN sh /tmp/bespunky-os-packages/os-packages.sh /tmp/bespunky-os-packages/os-packages.txt \
    && rm -rf /tmp/bespunky-os-packages /var/lib/apt/lists/*
