#!/bin/sh
# BeSpunky house — the OS packages this container needs, and the ONE installer for them.
#
# Generated by @bespunky/nx-tools:devcontainer — regenerated on every house upgrade. Edit the template in the
# toolkit, not this copy. YOUR packages go in .devcontainer/os-packages.txt (one per line, `#` comments), never here.
#
# TWO CALLERS, ONE RULE — install only what is MISSING:
#   - the IMAGE BUILD (.devcontainer/house.Dockerfile) runs it as root: everything is missing, so it installs the
#     lot — as one Docker layer, cached until this file or os-packages.txt changes. That is the whole point: a
#     rebuild reinstalls nothing that has not changed.
#   - post-create runs it on every container create: in a container built from the house Dockerfile every package
#     is already there and it does nothing; in one built from an image of the project's own (an adopted
#     devcontainer), it installs them, as the house always did.
#
# Exits non-zero when an install fails after its retries — the image build fails loudly instead of producing a
# container that is quietly missing tools; post-create reports it and carries on.
#
# POSIX sh, not bash: it runs in the image build before any layer has added bash to a minimal base.
set -u

# The house's packages, composed from this project's layers (nx, agent, node) and grouped BY CAPABILITY — so a reader
# can tell why each one is here, and it leaves with the layer that needs it.
HOUSE_PACKAGES='
# Durable shells. A tmux session outlives the client attached to it — the ONLY way an interactive shell
# opened into this container from the outside survives its opener restarting (the Docker Engine API cannot
# re-attach to an exec). No config is written on purpose: presence on PATH is the whole contract.
tmux
# General utilities the house tooling shells out to.
curl
# Voice (bespunky-voice): `paplay` reaches the host audio socket, espeak-ng is the free speech floor. Installed
# on the voice INTENT, not on a socket being present: a host fact cannot key a cached image layer, and both are small.
pulseaudio-utils espeak-ng
'

# Every list: the house's, then each file given (the project's own). Comments and blanks dropped, de-duplicated in
# order. A token that is not a Debian package NAME is refused here, before it can reach a root apt-get command line.
wanted() {
  { printf '%s\n' "$HOUSE_PACKAGES"; for list in "$@"; do [ -f "$list" ] && cat "$list"; done; } |
    sed 's/#.*//' | tr -s ' \t' '\n\n' | sed '/^$/d' | awk '!seen[$0]++' |
    while read -r name; do
      case "$name" in
        *[!a-z0-9.+-]* | [!a-z0-9]*) echo "[os-packages] ignoring '$name' — not a Debian package name" >&2 ;;
        *) echo "$name" ;;
      esac
    done
}

missing=""
for name in $(wanted "$@"); do
  dpkg-query -W -f='${Status}' "$name" 2>/dev/null | grep -q ' installed$' || missing="$missing $name"
done
if [ -z "$missing" ]; then
  echo "[os-packages] all present — nothing to install"
  exit 0
fi

as_root=""
[ "$(id -u)" = 0 ] || as_root="sudo"
echo "[os-packages] installing:$missing"
for attempt in 1 2 3; do
  # $missing is deliberately UNQUOTED: one argument per package. Safe — every member passed the name check above.
  # shellcheck disable=SC2086
  if $as_root apt-get update && $as_root env DEBIAN_FRONTEND=noninteractive apt-get install -y $missing; then
    echo "[os-packages] installed"
    exit 0
  fi
  if [ "$attempt" -lt 3 ]; then
    echo "[os-packages] attempt $attempt/3 failed (apt mirrors are occasionally flaky over Docker DNS); retrying in $((attempt * 10))s..."
    sleep $((attempt * 10))
  fi
done
echo "[os-packages] FAILED after 3 attempts:$missing" >&2
exit 1
