#!/usr/bin/env bash
# Project-specific devcontainer setup. THIS FILE IS YOURS.
#
# .devcontainer/post-create.sh is generated by @bespunky/nx-tools and is overwritten on every
# `scaffold.sh --sync`. This file is created once and never regenerated, so anything you put here
# survives. It runs LAST, after workspace deps, Claude plugins and every house prerequisite — so you can
# assume a working environment.
#
# Runs in a subshell; a non-zero exit warns rather than failing the container build.
set -euo pipefail

WS="$(pwd)"

# --- Reclaim the bind-mounted Claude config dir ---
# `.claude/data` is bind-mounted to /home/node/.claude. If Docker created the mount point as root (e.g. the
# host dir was missing on a fresh clone), the `node` user can't write auth/plugin state. Idempotent.
#
# NOT covered by the house script: that one reclaims /home/node/.cache, a different directory serving a
# different purpose (sibling tool caches). This mount is specific to how THIS repo persists Claude state.
if [ -d /home/node/.claude ] && [ "$(stat -c %U /home/node/.claude)" != "node" ]; then
  echo "[post-create.local] reclaiming /home/node/.claude ownership for node user"
  sudo chown node:node /home/node/.claude
fi

# --- Audio toolset (voice-plugin spike + bespunky-voice) ---
# WSLg audio is bridged in via devcontainer.json (PULSE_SERVER + the /mnt/wslg mount). The house script
# installs espeak-ng + pulseaudio-utils when it sees that bridge; this adds the two tools it doesn't —
# `alsa-utils` and `sox` — which the audio-boundary spike uses to record and inspect, not merely to speak.
# Best-effort: an offline rebuild must not fail the build. Verify the bridge with:
#   bash spikes/voice-audio-boundary/probe-audio.sh
echo "[post-create.local] installing the extra audio tools (alsa-utils sox)"
if sudo apt-get update -qq && sudo apt-get install -y -qq alsa-utils sox; then
  echo "[post-create.local] audio toolset complete"
else
  echo "[post-create.local] NOTE: audio tools skipped (offline?). Install later with:"
  echo "[post-create.local]   bash spikes/voice-audio-boundary/probe-audio.sh --install"
fi
