#!/usr/bin/env bash
# BeSpunky devcontainer post-create.
#
# Runs ONCE after the container is built (or rebuilt). Owns the multi-step setup that can only
# happen at CONTAINER-START time — workspace deps, Claude Code plugin pre-install, and Firebase
# prerequisites when this is a Firebase project.
#
# THE DIVISION OF LABOUR WITH `.devcontainer/features/*`. The always-on apt packages this script
# used to install now ship as locally-consumed devcontainer features (relative `./features/...`
# sources — nothing published), because a feature runs at BUILD time: it bakes into the image, it
# is cached across rebuilds, it fails the BUILD loudly rather than warning from inside a
# half-provisioned container, and — decisively — a `features` entry is MERGED into a
# devcontainer.json this generator merely ADOPTED, whereas this script on an adopted devcontainer
# is written beside the human's own as `post-create.bespunky.sh` and is never chained. An
# always-on capability living here was therefore always-on only in the containers we own.
#
# What stays here is what a feature CANNOT do, and every step below qualifies on one of two counts.
# Either its TARGET is a path a MOUNT replaces the moment the container starts — `/home/node/.cache`
# and the ms-playwright volume, the `/home/node/.claude` bind mount, `/var/opt/bespunky/ports` — so
# a build-time install of it would be writing into a directory that is about to be covered up. Or
# its TRIGGER is the workspace itself (`firebase.json`, `@playwright/test`, `@angular/core`), which
# is likewise a mount and simply is not there at build time, when the image knows nothing about the
# project it will host.
#
# Self-adapting: Firebase steps fire only when `firebase.json` is present at the
# workspace root, so the same script works whether or not --firebase was used at
# scaffold time. Add Firebase later? Re-run --sync --firebase, then rebuild —
# this script picks it up on the next post-create.
#
# POSIX-sh PARSEABLE, deliberately — no bash arrays, no `[[ ]]`, no process substitution, however
# naturally they would read here. The devcontainer generator supports a path where a human chains
# this file from a `postCreateCommand` of their own (`.devcontainer/post-create.bespunky.sh`, see
# the devcontainer generator), and under `/bin/sh` a bash-only construct is a PARSE error — sh
# parses incrementally, so the run gets as far as `yarn install` and then dies at that line with a
# bare syntax error, skipping every step below it and every WARNING they would have printed.
# Staying POSIX-parseable costs nothing and removes that whole class of failure.
#
# Generated by @bespunky/nx-tools:devcontainer. Edit the template in the toolkit,
# not this copy.
set -euo pipefail

# Devcontainer-cli runs postCreateCommand from the workspace root.
WS="$(pwd)"

# --- which package manager does THIS project use? ---
# Detected at RUN time, not baked in at generation time — the same self-adapting stance as the Firebase,
# Playwright and Angular steps below, and for a stronger reason here: this script re-runs on every container
# rebuild, long after it was generated, and a project can change package manager in between.
#
# Getting this wrong is not cosmetic. `yarn install` in an npm project does not switch it, it writes a SECOND
# lockfile beside the first — after which `npm ci` fails for the whole team, caused by a container rebuild.
# scaffold.sh takes exactly this care for the commands IT runs; this file is the artifact that runs forever
# afterwards, so it has to take the same care itself.
# THE DECLARATION FIRST, then the artifacts. `packageManager` is the only signal a human deliberately wrote;
# a lockfile is a by-product, and a STRAY one is exactly what this script used to leave behind when it ran
# `yarn install` regardless of the project's package manager. Checking lockfiles first meant the container
# kept trusting its own past mistake. Same order as scaffold.sh and the house-doc generator.
case "$(grep -m1 '"packageManager"' "$WS/package.json" 2>/dev/null)" in
  *pnpm*) PM=pnpm; PM_INSTALL="pnpm install"; PM_EXEC="pnpm exec" ;;
  *yarn*) PM=yarn; PM_INSTALL="yarn install"; PM_EXEC="yarn" ;;
  *npm*)  PM=npm;  PM_INSTALL="npm install";  PM_EXEC="npx --no-install" ;;
  *)
    if [ -f "$WS/pnpm-lock.yaml" ]; then
      PM=pnpm;  PM_INSTALL="pnpm install";  PM_EXEC="pnpm exec"
    elif [ -f "$WS/yarn.lock" ]; then
      PM=yarn;  PM_INSTALL="yarn install";  PM_EXEC="yarn"
    elif [ -f "$WS/package-lock.json" ]; then
      PM=npm;   PM_INSTALL="npm install";   PM_EXEC="npx --no-install"
    else
      PM=yarn;  PM_INSTALL="yarn install";  PM_EXEC="yarn"
    fi
    ;;
esac
echo "[post-create] package manager: $PM"

# --- 0. Reclaim /home/node/.cache ownership ---
# Docker creates intermediate mount-point directories as root. When the
# devcontainer mounts a volume to /home/node/.cache/ms-playwright (the
# Playwright browser cache), Docker creates the parent /home/node/.cache
# as root:root — so any tool running as `node` that later wants to mkdir
# a sibling under /home/node/.cache hits EACCES (firebase-tools' emulator
# JAR cache is the loud one; yarn/npm caches break silently). This
# chowns just the parent dir, leaving the mounted volume's contents
# untouched. Idempotent: skipped when already node-owned.
if [ -d /home/node/.cache ] && [ "$(stat -c %U /home/node/.cache)" != "node" ]; then
  echo "[post-create] reclaiming /home/node/.cache ownership for node user"
  sudo chown node:node /home/node/.cache
fi

# --- 0b. Shared host-port registry ---
# /var/opt/bespunky/ports is the FIXED-name docker volume every BeSpunky devcontainer on this engine
# mounts (see devcontainer.json). It is how containers see each other's noVNC port claims, so the
# shared browser can allocate a host port nobody else took instead of everyone assuming 6080 and the
# second container silently forwarding somewhere else. A fresh named volume is root-owned, so chown it
# to `node` — the allocator must be able to write claims as the remote user. Idempotent; best-effort,
# because a missing registry only degrades allocation (hash + probe), it never blocks a container.
#
# chmod 1777, not just chown: ownership in a SHARED volume is a UID, and different containers can have
# different UIDs for their remote user (a different base image, a second host user, updateRemoteUserUID
# not applying). A plain chown would let the second container take the directory AWAY from the first,
# whose allocator would then silently fall back to probe-only — reopening the collision window with no
# error anywhere. Sticky + world-writable means any UID can create its own claim file and no container
# can ever strand another; the sticky bit still stops one container deleting another's claim.
if [ -d /var/opt/bespunky/ports ]; then
  if [ "$(stat -c %U /var/opt/bespunky/ports)" != "node" ] || [ "$(stat -c %a /var/opt/bespunky/ports)" != "1777" ]; then
    echo "[post-create] preparing the shared host-port registry (/var/opt/bespunky/ports)"
    sudo chown node:node /var/opt/bespunky/ports || true
    sudo chmod 1777 /var/opt/bespunky/ports \
      || echo "[post-create] WARNING: could not prepare the port registry — shared-browser will fall back to probe-only allocation (parallel devcontainers won't see each other's noVNC port claims)"
  fi
fi

# --- 1. Workspace deps ---
echo "[post-create] $PM_INSTALL"
$PM_INSTALL

# --- 2. Pre-install the BeSpunky claude-toolkit plugins at project scope ---
# So house skills/agents are live the moment the container opens. If the CLI
# isn't reachable (offline rebuild, etc.) we don't fail the build — the project's
# .claude/settings.json declares the marketplace, so Claude on the host offers a
# one-click install on first session instead.
# THE SOURCE SELF-ADAPTS, on the same principle as the Firebase, Playwright and Angular steps below.
#
# A repo that IS the claude-toolkit marketplace must register its OWN WORKING TREE, never the published
# copy of itself: the whole point of developing there is that a skill edit is live in the next session with
# no publish round-trip, and pulling the released plugins over the top would silently shadow the very files
# being edited. `.claude-plugin/marketplace.json` uses relative `./plugins/...` sources, so the workspace
# root is a valid marketplace as-is.
#
# Narrow on purpose — the marketplace must be claude-toolkit ITSELF, not merely "some marketplace". A repo
# that is a DIFFERENT marketplace (its own plugins, its own name) still wants the BeSpunky plugins from
# GitHub, because its working tree does not contain them, and `install bespunky@claude-toolkit` against it
# would simply fail.
if grep -q '"name"[[:space:]]*:[[:space:]]*"claude-toolkit"' "$WS/.claude-plugin/marketplace.json" 2>/dev/null; then
  MARKETPLACE_SOURCE="$WS"
  echo "[post-create] this repo IS the claude-toolkit marketplace — registering the working tree (dogfooding), not the published copy"
else
  MARKETPLACE_SOURCE="BeSpunky/claude-toolkit"
  echo "[post-create] pre-installing claude-toolkit plugins"
fi
if claude plugin marketplace add "$MARKETPLACE_SOURCE" \
    && claude plugin install bespunky@claude-toolkit --scope project \
    && claude plugin install bespunky-project-starter@claude-toolkit --scope project \
    && claude plugin install bespunky-engineering@claude-toolkit --scope project \
    && claude plugin install bespunky-workflow@claude-toolkit --scope project \
    && claude plugin install bespunky-browser-automation@claude-toolkit --scope project \
    && claude plugin install bespunky-product-ux@claude-toolkit --scope project \
    && claude plugin install bespunky-design-system@claude-toolkit --scope project \
    && claude plugin install bespunky-vscode-identity@claude-toolkit --scope project; then
  echo "[post-create] claude-toolkit plugins installed at project scope"
else
  echo "[post-create] NOTE: Claude plugin pre-install skipped; .claude/settings.json will offer install on first run"
fi

# --- 3. Firebase prerequisites (auto-detected via firebase.json) ---
# The emulator suite (Firestore / RTDB / Storage) runs on the JVM, so OpenJDK is
# required. We install it via apt — Debian's package mirrors are reliable and
# don't depend on the build phase reaching github.com (which the SDKMAN-based
# `ghcr.io/devcontainers/features/java` feature does, intermittently failing
# under quirky WSL+Docker network paths).
#
# We also install a /etc/profile.d sourcer for the self-extinguishing Firebase
# welcome banner (tools/firebase-welcome.sh in the workspace), so every login
# shell nudges the user toward the cloud-linkage steps until setup is complete.
if [ -f "$WS/firebase.json" ]; then
  echo "[post-create] firebase.json detected — installing OpenJDK (default-jdk-headless) + wiring welcome banner"
  sudo apt-get update -qq
  sudo apt-get install -y --no-install-recommends default-jdk-headless
  echo "[ -f $WS/tools/firebase-welcome.sh ] && source $WS/tools/firebase-welcome.sh" \
    | sudo tee /etc/profile.d/zz-firebase-welcome.sh > /dev/null
  echo "[post-create] Firebase prerequisites ready"
fi

# --- 4. Playwright prerequisites (auto-detected via @playwright/test in package.json) ---
# Chromium binary + the apt libs Chromium needs (fonts, libnss3, libatk, …).
# `playwright install --with-deps chromium` does both: it downloads the browser
# into ~/.cache/ms-playwright (mounted as a per-workspace volume by the
# devcontainer generator, so rebuilds reuse the cached browser) and invokes
# sudo internally for the apt step. The typescript-node base image grants
# passwordless sudo to the `node` user, so no prompt.
#
# Self-adapting: fires only when the workspace already declares @playwright/test
# in package.json (the `@bespunky/nx-tools:playwright` generator adds it). So
# the same script works whether or not Playwright was opted in at scaffold time
# — adding `@playwright/test` later and rebuilding picks it up on the next
# post-create.
if grep -q '"@playwright/test"' package.json 2>/dev/null; then
  echo "[post-create] @playwright/test detected — installing Chromium + system deps"
  # Reclaim the Playwright cache VOLUME mount point. The browser cache is a
  # per-workspace Docker volume mounted at /home/node/.cache/ms-playwright, and
  # Docker creates fresh named-volume mount points as root:root. Step 0 chowns the
  # parent /home/node/.cache (so sibling caches like firebase's JAR cache work) but
  # deliberately leaves the volume's contents untouched — so the mount point itself
  # stays root-owned and `playwright install`, running as `node`, hits EACCES the
  # first time it mkdirs inside it (the __dirlock lock dir). Guarded on ownership:
  # runs only on a fresh (empty → instant) volume, no-op on rebuilds where the
  # cache is already node-owned and populated.
  if [ -d /home/node/.cache/ms-playwright ] && [ "$(stat -c %U /home/node/.cache/ms-playwright)" != "node" ]; then
    echo "[post-create] reclaiming /home/node/.cache/ms-playwright volume ownership for node user"
    sudo chown -R node:node /home/node/.cache/ms-playwright
  fi
  # The browser binary is a large download from cdn.playwright.dev. WSL+Docker DNS is
  # intermittently flaky (getaddrinfo ENOTFOUND on an otherwise-working network — apt and the
  # rest of post-create succeed, then this one host fails to resolve), and Playwright's own
  # retries fire too fast to outlast the blip. Without this, a single hiccup would abort the
  # whole post-create (set -e) and leave the container half-provisioned. So retry with backoff,
  # and if it still fails, warn LOUDLY but do NOT fail the build — everything else (deps,
  # plugins, Firebase) is ready and the user can finish this one step once the network settles
  # (same best-effort stance as the claude-toolkit plugin pre-install above).
  pw_ok=0
  for attempt in 1 2 3; do
    if $PM_EXEC playwright install --with-deps chromium; then pw_ok=1; break; fi
    if [ "$attempt" -lt 3 ]; then
      echo "[post-create] Playwright browser install attempt $attempt/3 failed (often transient WSL/Docker DNS); retrying in $((attempt * 10))s..."
      sleep $((attempt * 10))
    fi
  done
  if [ "$pw_ok" = 1 ]; then
    echo "[post-create] Playwright prerequisites ready"
  else
    echo "[post-create] WARNING: Playwright browser install failed after 3 attempts — likely a transient network/DNS issue."
    echo "[post-create]          The container is otherwise ready; finish this one step once the network settles with:"
    echo "[post-create]            $PM_EXEC playwright install --with-deps chromium"
  fi
fi

# --- 5. Angular agent skills (auto-detected via @angular/core in package.json) ---
# Angular ships official agent skills (angular-developer, angular-new-app) at
# github.com/angular/skills, authored in Claude's own SKILL.md format (name/description
# frontmatter + a references/ dir of progressive-disclosure docs). We fetch them FRESH
# into .claude/skills/ on every container build rather than vendoring copies, so they
# track upstream Angular with zero maintenance: the skills repo is itself auto-generated
# from angular/angular, so a fork would silently go stale. The committed `.mcp.json`
# (Angular CLI MCP server) is the always-current *knowledge* channel; these skills are
# the always-loaded, triggerable companion. `.claude/skills/` is gitignored (a
# refreshable cache, like node_modules) — the @bespunky/nx-tools:angular-ai generator
# added that ignore rule. Best-effort with retry: a network blip never fails the build
# (same stance as the plugin pre-install and Playwright steps above).
if grep -q '"@angular/core"' package.json 2>/dev/null; then
  echo "[post-create] @angular/core detected — fetching Angular agent skills into .claude/skills/"
  skills_ok=0
  for attempt in 1 2 3; do
    ng_skills_tmp="$(mktemp -d)"
    if git clone --depth 1 --quiet https://github.com/angular/skills "$ng_skills_tmp" 2>/dev/null; then
      mkdir -p "$WS/.claude/skills"
      for s in angular-developer angular-new-app; do
        if [ -d "$ng_skills_tmp/$s" ]; then
          rm -rf "$WS/.claude/skills/$s"
          cp -r "$ng_skills_tmp/$s" "$WS/.claude/skills/$s"
        fi
      done
      rm -rf "$ng_skills_tmp"
      skills_ok=1
      break
    fi
    rm -rf "$ng_skills_tmp"
    if [ "$attempt" -lt 3 ]; then
      echo "[post-create] Angular skills fetch attempt $attempt/3 failed (often transient DNS); retrying in $((attempt * 5))s..."
      sleep $((attempt * 5))
    fi
  done
  if [ "$skills_ok" = 1 ]; then
    echo "[post-create] Angular agent skills ready (.claude/skills/{angular-developer,angular-new-app})"
  else
    echo "[post-create] WARNING: Angular skills fetch failed after 3 attempts — likely a transient network issue."
    echo "[post-create]          The container is otherwise ready; refetch this one step once the network settles with:"
    echo "[post-create]            t=\$(mktemp -d); git clone --depth 1 https://github.com/angular/skills \"\$t\" && mkdir -p .claude/skills && cp -r \"\$t\"/angular-developer \"\$t\"/angular-new-app .claude/skills/ && rm -rf \"\$t\""
  fi
fi

# --- The OS floor moved to BUILD time: `.devcontainer/features/os-floor` ---
# NOT DROPPED — RELOCATED. The apt packages every BeSpunky devcontainer carries, whatever it is a
# devcontainer FOR, used to be one apt transaction right here: xvfb / x11vnc / novnc / websockify /
# fluxbox / fonts (the shared browser's virtual display and its noVNC bridge), tmux (durable shells
# that outlive the client attached to them), and iproute2 / procps / curl (the utilities the
# worktree-domains proxy and the port probes shell out to). They now install at BUILD time from
# `.devcontainer/features/os-floor`, a locally-consumed devcontainer feature (relative path,
# nothing published). The list, its grouping BY CAPABILITY, and the reason each package is there
# live in that feature's install.sh — this file deliberately keeps no second copy, because two
# copies of one list is exactly how `nx serve`'s hand-typed copy of it silently drifted.
#
# Why a feature rather than a step here — the reason is ADOPTION, and it is the whole point. A
# `features` entry is MERGED into a devcontainer.json this generator merely adopted, so the floor
# reaches every house container. This script is merged nowhere: on an adopted devcontainer it is
# written beside the human's own as `post-create.bespunky.sh` and never chained. An always-on
# capability that lived here was always-on only where we also owned the postCreateCommand. Build
# time buys the rest: the layer is cached across rebuilds, and a failure fails the BUILD instead of
# printing a WARNING from inside a container that then opens looking fine.

# --- 6. Shared-browser Chromium (ALWAYS-ON — the one part of the floor that is not an apt package) ---
# It stayed behind when the rest of the floor became a build-time feature, and for the reason that
# decides every such call in this file: its target, /home/node/.cache/ms-playwright, is a
# per-workspace Docker VOLUME. A feature writes into the IMAGE at build time, and the volume mount
# replaces that directory wholesale the moment the container starts — so a browser installed there
# at build time is discarded before anything can use it. Container start or nowhere.
#
# Ensure a Playwright Chromium binary exists for the shared browser to launch (the CLI resolves
# it at runtime via whichever of playwright / playwright-core / @playwright/test is installed).
# Step 4 already fetched it when @playwright/test is in package.json — so here we only install
# if it is still MISSING, avoiding a redundant ~150 MB download. Best-effort + retry; a failure
# only warns (the shared-browser CLI's own guard also runs `npx playwright install chromium` on
# first `up` if it is absent, so this is provisioning-ahead, not a hard requirement).
if [ -d /home/node/.cache/ms-playwright ] && \
   find /home/node/.cache/ms-playwright -maxdepth 1 -type d -name 'chromium-*' 2>/dev/null | grep -q .; then
  echo "[post-create] shared-browser: Playwright Chromium already present — skipping install"
else
  echo "[post-create] shared-browser: Playwright Chromium not found — installing"
  sb_pw_ok=0
  for attempt in 1 2 3; do
    if npx --yes playwright install chromium; then sb_pw_ok=1; break; fi
    if [ "$attempt" -lt 3 ]; then
      echo "[post-create] shared-browser Chromium install attempt $attempt/3 failed (often transient DNS); retrying in $((attempt * 10))s..."
      sleep $((attempt * 10))
    fi
  done
  if [ "$sb_pw_ok" = 1 ]; then
    echo "[post-create] shared-browser: Playwright Chromium ready"
  else
    echo "[post-create] WARNING: shared-browser Chromium install failed after 3 attempts — likely a transient network issue."
    echo "[post-create]          The container is otherwise ready; finish this one step once the network settles with:"
    echo "[post-create]            npx playwright install chromium"
  fi
fi

# --- 7. Voice plugin pre-install (DECLARED by the voice feature via BESPUNKY_VOICE) ---
# The bespunky-voice plugin speaks (TTS) and listens (STT) through a PulseAudio sink. Its engine —
# espeak-ng (the free TTS floor) plus pulseaudio-utils for `paplay` — now installs at BUILD time
# from `.devcontainer/features/voice`, alongside the audio bridge itself. What is left here is the
# half a feature cannot do: pre-installing the plugin writes into /home/node/.claude, a bind mount
# from the host that does not exist until the container is running. Piper (the natural-voice
# upgrade) stays a manual, machine-local opt-in via the plugin's install-piper.sh — same stance as
# the claude-toolkit repo's own devcontainer.
#
# A DECLARATION, NOT AN INFERENCE — and this is the whole reason voice became a feature. This step
# used to gate on `[ -d /mnt/wslg ]`. Voice is OPT-IN (scaffold with --voice), this script cannot
# see that flag, so it detected voice by the PRESENCE OF THE MOUNT the other half of the capability
# had put there — reading one part's side effect as a signal for another. An inference like that is
# wrong in both directions the moment anything moves: a non-WSL host wired for audio some other way
# (macOS, Codespaces) has no /mnt/wslg and silently gets no voice, and anything else that ever
# mounts /mnt/wslg switches voice on for a project that never asked for it. The feature now states
# the fact outright — `containerEnv` BESPUNKY_VOICE=1, set by `.devcontainer/features/voice` and so
# present on the container EXACTLY when voice was requested — and the gate reads that intent
# instead of guessing at it from a mount path.
#
# `${BESPUNKY_VOICE:-}` rather than `$BESPUNKY_VOICE`, because `set -u` aborts the whole script on
# an unset variable and unset is the ORDINARY case here: every container without voice.
if [ -n "${BESPUNKY_VOICE:-}" ]; then
  echo "[post-create] BESPUNKY_VOICE declared — pre-installing the bespunky-voice plugin at project scope"
  # Pre-install the voice plugin at project scope so /voice is live on open. Best-effort:
  # the marketplace was added in step 2; if that was offline, .claude/settings.json offers
  # install on first run. (The other house plugins are pre-installed unconditionally in step 2;
  # bespunky-voice is gated here because without the voice feature's engine and audio bridge it
  # would have nothing to speak through.)
  if claude plugin install bespunky-voice@claude-toolkit --scope project; then
    echo "[post-create] bespunky-voice plugin installed at project scope"
  else
    echo "[post-create] NOTE: bespunky-voice plugin install skipped (CLI offline?) — enable later with /plugin"
  fi
fi

# --- 8. Project-specific setup (YOURS — this script's one extension point) ---
# Everything above is GENERATED and is overwritten on every `scaffold.sh --sync`. That is fine for
# house steps and fatal for yours: a project that needs its own provisioning (a database client, an
# internal CA, a language runtime the house image doesn't carry) had nowhere to put it but this file,
# where the next sync would silently delete it. Hence a seam.
#
# `.devcontainer/post-create.local.sh` is YOURS. It is created once, never regenerated, never read by
# any generator, and it runs last — after the workspace has deps, plugins and every house prerequisite,
# which is the only point at which project-specific setup can assume a working environment.
#
# Run in a SUBSHELL (bash, not source) so a stray `exit` or a variable named like one of ours can't
# reach back into this script. A failure WARNS rather than aborts — the same stance every step above
# takes, and for the same reason: a half-provisioned container is worse than a missing optional step.
if [ -f "$WS/.devcontainer/post-create.local.sh" ]; then
  echo "[post-create] running .devcontainer/post-create.local.sh (project-specific)"
  if bash "$WS/.devcontainer/post-create.local.sh"; then
    echo "[post-create] project-specific setup done"
  else
    echo "[post-create] WARNING: .devcontainer/post-create.local.sh exited non-zero — the house setup above completed,"
    echo "[post-create]          but your project-specific step did not. Re-run it directly to see the failure:"
    echo "[post-create]            bash .devcontainer/post-create.local.sh"
  fi
fi

echo "[post-create] done"
