#!/usr/bin/env bash
# Project-specific devcontainer setup. THIS FILE IS YOURS.
#
# .devcontainer/post-create.sh is generated by @bespunky/nx-tools and is overwritten on every
# house upgrade (`house.sh upgrade`). This file is created once and never regenerated, so anything you put here
# survives. It runs LAST, after workspace deps, Claude plugins and every house prerequisite — so you can
# assume a working environment.
#
# Runs in a subshell; a non-zero exit warns rather than failing the container build.
set -euo pipefail

WS="$(pwd)"

# --- Reclaim the bind-mounted Claude config dir ---
# `.claude/data` is bind-mounted to /home/node/.claude. If Docker created the mount point as root (e.g. the
# host dir was missing on a fresh clone), the `node` user can't write auth/plugin state. Idempotent.
#
# NOT covered by the house script: that one reclaims /home/node/.cache, a different directory serving a
# different purpose (sibling tool caches). This mount is specific to how THIS repo persists Claude state.
if [ -d /home/node/.claude ] && [ "$(stat -c %U /home/node/.claude)" != "node" ]; then
  echo "[post-create.local] reclaiming /home/node/.claude ownership for node user"
  sudo chown node:node /home/node/.claude
fi

# --- Release guard: point git at the repo's committed hooks --------------------------------------------------
# `tools/git-hooks/pre-push` refuses a push whose plugin/payload changes carry no version bump — the failure
# that is otherwise SILENT (the marketplace advertises the old version and consumers simply never get the
# change). It lives here, in the never-regenerated local seam, and NOT in the generated post-create.sh: that
# file is regenerated into every scaffolded project, and a consumer project has no plugins to version.
# Idempotent, and cheap enough to re-assert on every container create.
if [ -d tools/git-hooks ]; then
  git config core.hooksPath tools/git-hooks
  echo "[post-create.local] git hooks -> tools/git-hooks (pre-push release guard active)"
fi
