#!/usr/bin/env bash
# BeSpunky devcontainer post-create.
#
# Runs ONCE after the container is built (or rebuilt). Owns all multi-step setup that doesn't fit cleanly as a
# devcontainer "feature" — the project's dependencies, the Claude Code plugin pre-install, any OS package the image lacks and
# whatever tooling this project's LAYERS bring.
#
# COMPOSED, not static: every section below was contributed by one of this project's layers (nx, agent, node), and an
# upgrade recomposes the whole file from the layers it detects. Add a layer (Firebase, a web app, …), re-run
# `house.sh upgrade`, rebuild — its steps appear here; a layer that leaves takes its steps with it.
#
# Generated by @bespunky/nx-tools:devcontainer. Edit the template in the toolkit,
# not this copy.
set -euo pipefail

# Devcontainer-cli runs postCreateCommand from the workspace root.
WS="$(pwd)"
# The user this container runs as, and its home — read, never assumed: the image decides them
# (`node` on typescript-node, `vscode` on the neutral devcontainers base).
ME="$(id -un)"
ME_GROUP="$(id -gn)"

# --- Volume ownership (DERIVED from this devcontainer's volume mounts) ---
# Docker creates a fresh named volume — and every directory missing on the way to its mount point (`.nx/` on a
# fresh clone, `~/.cache` under the Playwright cache) — owned by ROOT. Everything below runs as the remote user,
# so the first install would hit EACCES (`mkdir node_modules/…`). This section is generated from the mounts in
# devcontainer.json, one line per volume, so a layer that adds a volume gets its reclaim by declaring it — never
# by remembering to script one. It runs FIRST, before anything installs.
#
#   reclaim_volume tree  <dir>   the mount point: chown -R (a fresh volume is empty, so it is instant; an older
#                                volume a root process populated needs the recursion)
#   reclaim_volume dir   <dir>   a directory Docker created on the way: chown of that directory only — the rest
#                                of what lives in it is not the volume's
#   share_volume         <dir>   a volume SEVERAL containers mount: chmod 1777 rather than chown, because
#                                ownership in a shared volume is a UID and remote users' UIDs differ between
#                                containers — a chown would let the second container take it away from the
#                                first. Sticky + world-writable lets every UID write its own entries and none
#                                delete another's.
#
# Guarded on ownership (or mode), so every rebuild after the first is a no-op. A failure WARNS, never aborts:
# the step that needed the directory reports its own error, louder and more specifically than this could.
reclaim_volume() {
  [ -d "$2" ] || return 0
  [ "$(stat -c %U "$2")" = "$ME" ] && return 0
  echo "[post-create] reclaiming $2 for $ME (Docker created it as root)"
  if [ "$1" = tree ]; then
    sudo chown -R "$ME:$ME_GROUP" "$2" || echo "[post-create] WARNING: could not reclaim $2 — writes into it will fail with EACCES"
  else
    sudo chown "$ME:$ME_GROUP" "$2" || echo "[post-create] WARNING: could not reclaim $2 — writes into it will fail with EACCES"
  fi
}
share_volume() {
  [ -d "$1" ] || return 0
  [ "$(stat -c %a "$1")" = 1777 ] && return 0
  echo "[post-create] opening the shared volume $1 to every container's user (1777)"
  sudo chmod 1777 "$1" || echo "[post-create] WARNING: could not open the shared volume $1 — containers whose user does not own it cannot write there"
}
reclaim_volume dir "$WS/.nx"
reclaim_volume tree "$WS/.nx/cache"
reclaim_volume tree "$WS/.nx/workspace-data"
reclaim_volume tree "$HOME/.config"
reclaim_volume tree "$HOME/.local"
reclaim_volume tree "$WS/node_modules"

# --- Claude Code's account record, kept inside the persisted config dir (agent) ---
# CLAUDE_CONFIG_DIR (devcontainer.json containerEnv) puts `.claude.json` — the login and onboarding record — inside
# the bind-mounted config dir, so it survives a rebuild. Exported here as well, because a lifecycle command may run
# without the container's env applied and the plugin pre-install below runs `claude`.
#
# A config dir that has NO account record yet but does have Claude Code's own backups of one (it keeps them under
# `backups/`) is restored from the newest: that is exactly a container that predates the setting — whose record
# lived in the container-local $HOME and died with the old container — so its first rebuild with the setting does
# not ask to log in either. Never overwrites a record that exists.
export CLAUDE_CONFIG_DIR="${CLAUDE_CONFIG_DIR:-$HOME/.claude}"
if [ ! -f "$CLAUDE_CONFIG_DIR/.claude.json" ]; then
  claude_backup="$(ls -1t "$CLAUDE_CONFIG_DIR"/backups/.claude.json.backup.* 2>/dev/null | head -n 1 || true)"
  if [ -n "$claude_backup" ] && cp -p "$claude_backup" "$CLAUDE_CONFIG_DIR/.claude.json"; then
    echo "[post-create] restored Claude Code's account record from $(basename "$claude_backup") — no new login needed"
  fi
fi

# --- The OS packages (the house's and .devcontainer/os-packages.txt) ---
# They are installed when the IMAGE is built (.devcontainer/house.Dockerfile) — one cached Docker layer, so a
# rebuild reinstalls nothing unless a list changed. This step runs the same installer, which installs only what is
# MISSING: nothing, in a container built from the house Dockerfile; everything, in one built from an image of the
# project's own. Best-effort: a failure WARNS — it never aborts post-create and leaves the container half-provisioned.
if sh .devcontainer/house.packages.sh .devcontainer/os-packages.txt; then
  echo "[post-create] OS packages ready"
else
  echo "[post-create] WARNING: some OS packages could not be installed (often a transient network issue)."
  echo "[post-create]          The container is otherwise ready. Finish this one step once the network settles:"
  echo "[post-create]            sh .devcontainer/house.packages.sh .devcontainer/os-packages.txt"
fi

# --- The Nx wrapper's installation (nx) ---
# A repo that hosts Nx through the wrapper (`./nx`, `.nx/nxw.js` — the house's choice for a repo with no
# package.json) keeps Nx, @nx/devkit and @bespunky/nx-tools in the GITIGNORED `.nx/installation`, pinned
# exactly in nx.json `installation`. Any `./nx` invocation installs it to match the pins; doing it HERE means
# the first `./nx g …` in the new container doesn't pay for it, and an offline rebuild says so now rather than
# mid-task. Self-adapting: a repo without the wrapper (Nx in node_modules) skips this — its package-manager
# install below brings Nx.
if [ -f "$WS/.nx/nxw.js" ] && [ -x "$WS/nx" ]; then
  echo "[post-create] installing the Nx wrapper's pinned packages (.nx/installation)"
  if "$WS/nx" --version > /dev/null; then
    echo "[post-create] Nx wrapper ready"
  else
    echo "[post-create] WARNING: the Nx wrapper could not install its packages (offline?). The next ./nx call retries."
  fi
fi

# --- Claude Code, installed ONCE, natively (agent) ---
# The native install (~/.local/bin/claude) is the one `claude update` and Claude Code's background auto-updater
# manage, so a container installed this way stays current with nobody running anything. There is deliberately
# no second copy: the house used to install Claude Code through a devcontainer feature as well, and that build-
# time copy sat earlier on PATH — every update landed in the shadowed one, reported success, and changed
# nothing, freezing the container at its build-day version (and hiding every newer Claude Code feature the
# toolkit relies on). devcontainer.json puts ~/.local/bin first on PATH for the same reason; this script
# exports it too, because a lifecycle command may run without remoteEnv and the plugin pre-install below
# needs `claude`. Best-effort: offline, it warns and the container still comes up.
if [ -x "$HOME/.local/bin/claude" ]; then
  echo "[post-create] Claude Code already installed natively — its own updater keeps it current"
elif curl -fsSL https://claude.ai/install.sh | bash; then
  echo "[post-create] Claude Code installed natively (~/.local/bin/claude)"
else
  echo "[post-create] WARNING: Claude Code could not be installed (offline?). Run: curl -fsSL https://claude.ai/install.sh | bash"
fi
export PATH="$HOME/.local/bin:$PATH"

# --- The project's dependencies (node — this repo has a package.json) ---
# Which package manager does THIS project use? Detected at RUN time, not baked in at generation time: this
# script re-runs on every container rebuild, long after it was generated, and a project can change package
# manager in between.
#
# Getting this wrong is not cosmetic. `yarn install` in an npm project does not switch it, it writes a SECOND
# lockfile beside the first — after which `npm ci` fails for the whole team, caused by a container rebuild.
# THE DECLARATION FIRST, then the artifacts. `packageManager` is the only signal a human deliberately wrote;
# a lockfile is a by-product, and a STRAY one is exactly what an unconditional `yarn install` used to leave
# behind. The detection below is RENDERED from the one rule (generators/_utils/package-manager.ts), so it cannot
# disagree with the generators; house.sh keeps the same order.
if [ -f "$WS/package.json" ]; then
  case "$(grep -m1 '"packageManager"' "$WS/package.json" 2>/dev/null | tr -d ' ')" in
    *'"pnpm@'*) PM=pnpm; PM_INSTALL="pnpm install"; PM_EXEC="pnpm exec" ;;
    *'"yarn@'*) PM=yarn; PM_INSTALL="yarn install"; PM_EXEC="yarn" ;;
    *'"npm@'*) PM=npm; PM_INSTALL="npm install"; PM_EXEC="npx --no-install" ;;
    *)
      if [ -f "$WS/pnpm-lock.yaml" ]; then PM=pnpm; PM_INSTALL="pnpm install"; PM_EXEC="pnpm exec"
      elif [ -f "$WS/yarn.lock" ]; then PM=yarn; PM_INSTALL="yarn install"; PM_EXEC="yarn"
      elif [ -f "$WS/package-lock.json" ]; then PM=npm; PM_INSTALL="npm install"; PM_EXEC="npx --no-install"
      else PM=yarn; PM_INSTALL="yarn install"; PM_EXEC="yarn"
      fi
      ;;
  esac
  echo "[post-create] package manager: $PM"
  echo "[post-create] $PM_INSTALL"
  $PM_INSTALL
else
  echo "[post-create] no package.json — no package-manager install (the Nx wrapper hosts the house tooling)"
fi

# --- Pre-install the Claude Code plugins at project scope (agent) ---
# So house skills/agents are live the moment the container opens. The list is the SAME one
# .claude/settings.json enables — both are composed from this project's layers — so the two can't drift. If
# the CLI isn't reachable (offline rebuild, etc.) we don't fail the build: .claude/settings.json declares the
# marketplaces, so Claude offers a one-click install on first session instead.
#
# THE claude-toolkit SOURCE SELF-ADAPTS. A repo that IS the claude-toolkit marketplace must register its OWN
# WORKING TREE, never the published copy of itself: the whole point of developing there is that a skill edit
# is live in the next session with no publish round-trip, and pulling the released plugins over the top would
# silently shadow the very files being edited. Narrow on purpose — the marketplace must be claude-toolkit
# ITSELF, not merely "some marketplace": a repo that is a DIFFERENT marketplace still wants the BeSpunky
# plugins from GitHub.
# One `<marketplace name> <source>` pair per line.
HOUSE_MARKETPLACES="nx-claude-plugins nrwl/nx-ai-agents-config
claude-toolkit BeSpunky/claude-toolkit"
HOUSE_PLUGINS="nx@nx-claude-plugins bespunky@claude-toolkit bespunky-house@claude-toolkit bespunky-engineering@claude-toolkit bespunky-workflow@claude-toolkit bespunky-product-ux@claude-toolkit bespunky-vscode-identity@claude-toolkit bespunky-communication@claude-toolkit"
if grep -q '"name"[[:space:]]*:[[:space:]]*"claude-toolkit"' "$WS/.claude-plugin/marketplace.json" 2>/dev/null; then
  echo "[post-create] this repo IS the claude-toolkit marketplace — registering the working tree (dogfooding), not the published copy"
  TOOLKIT_SELF=1
else
  TOOLKIT_SELF=0
fi
echo "[post-create] pre-installing Claude Code plugins"
plugins_ok=1
while read -r mp_name mp_source; do
  [ -n "$mp_name" ] || continue
  if [ "$mp_name" = "claude-toolkit" ] && [ "$TOOLKIT_SELF" = 1 ]; then mp_source="$WS"; fi
  claude plugin marketplace add "$mp_source" || plugins_ok=0
done <<HOUSE_MARKETPLACES_EOF
$HOUSE_MARKETPLACES
HOUSE_MARKETPLACES_EOF
if [ "$plugins_ok" = 1 ]; then
  for plugin in $HOUSE_PLUGINS; do
    claude plugin install "$plugin" --scope project || { plugins_ok=0; break; }
  done
fi
if [ "$plugins_ok" = 1 ]; then
  echo "[post-create] Claude Code plugins installed at project scope"
else
  echo "[post-create] NOTE: Claude plugin pre-install skipped; .claude/settings.json will offer install on first run"
fi

# --- git authenticates through the persisted GitHub CLI login (agent) ---
# The `gh` login lives in the persisted ~/.config (devcontainer.json mounts), so it survives a rebuild; ~/.gitconfig does not. This
# re-points git's GitHub credential helper at `gh` on every container create, so `git push` works in ANY shell —
# including one opened from outside the editor, which the editor's own forwarded credential helper never reaches.
# Not logged in yet (a fresh ~/.config) is not an error: `gh auth login` offers the same wiring when it runs.
if command -v gh > /dev/null && gh auth status > /dev/null 2>&1; then
  if gh auth setup-git; then
    echo "[post-create] git uses the persisted GitHub CLI login"
  else
    echo "[post-create] WARNING: could not wire git to the GitHub CLI login. Run: gh auth setup-git"
  fi
else
  echo "[post-create] GitHub CLI not logged in yet — run \`gh auth login\` once; it persists across rebuilds"
fi

# --- Voice: enable the plugin when host audio arrived (the --voice intent) ---
# The bespunky-voice plugin speaks (TTS) and listens (STT) through a PulseAudio-protocol socket.
# Voice is OPT-IN (scaffold with --voice): only then does the devcontainer carry the host probe
# (initializeCommand) and the bind mount that lands the host's socket folder at ONE fixed
# endpoint, /run/bespunky/host/pulse/ — WSLg, native PulseAudio and PipeWire's pulse shim alike.
# On a host with no audio the probe mounts an empty dir instead, so the container still opens.
# Its OS packages (espeak-ng, the free speech floor, and pulseaudio-utils for `paplay`) are in the composed package
# list — installed with the image, a cached layer — so this step only enables the plugin, and only when a socket
# actually ARRIVED in that folder: without a speaker and mic to reach, the plugin has nothing to do. Piper (the
# natural voice) and whisper are the plugin's own machine-local installs, kept in ~/.claude across rebuilds.
# (`find -type s` rather than one fixed name: WSLg's own socket is called `PulseServer`, the others `native`.)
if [ -n "$(find /run/bespunky/host/pulse/ -maxdepth 1 -type s 2>/dev/null | head -n 1)" ]; then
  echo "[post-create] host audio socket detected (--voice) — enabling bespunky-voice"
  # Pre-install the voice plugin at project scope so /speak is live on open. Best-effort:
  # the marketplace was added by the plugin pre-install; if that was offline, .claude/settings.json offers
  # install on first run. (The other house plugins are pre-installed by the plugin step;
  # bespunky-voice is gated here because without a host audio socket it can't play audio.)
  if claude plugin install bespunky-voice@claude-toolkit --scope project; then
    echo "[post-create] bespunky-voice plugin installed at project scope"
  else
    echo "[post-create] NOTE: bespunky-voice plugin install skipped (CLI offline?) — enable later with /plugin"
  fi
fi

# --- Project-specific setup (YOURS — this script's one extension point) ---
# Everything above is GENERATED and is overwritten on every `house.sh upgrade`. That is fine for
# house steps and fatal for yours: a project that needs its own provisioning (a database client, an
# internal CA, a language runtime the house image doesn't carry) had nowhere to put it but this file,
# where the next upgrade would silently delete it. Hence a seam.
#
# `.devcontainer/post-create.local.sh` is YOURS. It is created once, never regenerated, never read by
# any generator, and it runs last — after the workspace has deps, plugins and every house prerequisite,
# which is the only point at which project-specific setup can assume a working environment.
#
# Run in a SUBSHELL (bash, not source) so a stray `exit` or a variable named like one of ours can't
# reach back into this script. A failure WARNS rather than aborts — the same stance every step above
# takes, and for the same reason: a half-provisioned container is worse than a missing optional step.
if [ -f "$WS/.devcontainer/post-create.local.sh" ]; then
  echo "[post-create] running .devcontainer/post-create.local.sh (project-specific)"
  if bash "$WS/.devcontainer/post-create.local.sh"; then
    echo "[post-create] project-specific setup done"
  else
    echo "[post-create] WARNING: .devcontainer/post-create.local.sh exited non-zero — the house setup above completed,"
    echo "[post-create]          but your project-specific step did not. Re-run it directly to see the failure:"
    echo "[post-create]            bash .devcontainer/post-create.local.sh"
  fi
fi

echo "[post-create] done"
