// 0.35.0 — host-port arbitration moves from tools/shared-browser/ to its own home, tools/port-claim/.
//
// WHY IT MOVED. Three tools consult one host-port registry: the shared browser (allocates its noVNC port), the
// worktree-domains proxy (who owns :80) and the dev engine (who owns an app's base port). The arbiter lived
// inside tools/shared-browser/, so the other two reached into a SIBLING's private file — a hidden dependency
// that broke the moment the shared browser was absent. From 0.35.0 the `port-claim` generator owns
// tools/port-claim/.
//
// A MOVE IS A RENAME, so this rung:
//   1. MOVES the two files (port-claim.mjs, port-claim.test.mjs) — byte for byte, mode kept — when the old copy
//      is the house's (it carries the generator's "Generated by @bespunky/nx-tools:shared-browser" stamp). A
//      file at that path WITHOUT the stamp is somebody's own and is left where it is, REPORTED.
//   2. RETARGETS every reference to the old location in the workspace, including the house CLIs a bare
//      `nx migrate` leaves in place until the next sync rewrites them — so the shared browser and the domains
//      proxy keep arbitrating between the migration and that sync:
//        tools/shared-browser/shared-browser   PORT_CLAIM="$SCRIPT_DIR/port-claim.mjs"
//        anything                              tools/shared-browser/port-claim(.test).mjs
//      and the moved test file's own run instruction. Every rewritten file is named in the log.
//   3. Never touches node_modules, .git, .nx, or .claude/worktrees (other branches' checkouts).
//
// SELF-CONTAINED by the migration contract: the paths and the stamp are frozen here as 0.34.x wrote them.
import { type Tree, logger } from '@nx/devkit';

const TAG = '[migrate 0.35.0 relocate-port-claim]';
const OLD_DIR = 'tools/shared-browser';
const NEW_DIR = 'tools/port-claim';
const FILES = ['port-claim.mjs', 'port-claim.test.mjs'];
const HOUSE_STAMP = 'Generated by @bespunky/nx-tools:shared-browser';

/** [old, new] text pairs, most specific first. */
const REWRITES: [string, string][] = [
  [`${OLD_DIR}/port-claim.test.mjs`, `${NEW_DIR}/port-claim.test.mjs`],
  [`${OLD_DIR}/port-claim.mjs`, `${NEW_DIR}/port-claim.mjs`],
  ['PORT_CLAIM="$SCRIPT_DIR/port-claim.mjs"', 'PORT_CLAIM="$SCRIPT_DIR/../port-claim/port-claim.mjs"'],
];
const SKIP_DIRS = new Set(['node_modules', '.git', '.nx', '.angular', 'dist', 'tmp']);
const BINARY = /\.(png|jpe?g|gif|webp|avif|ico|svg|woff2?|ttf|eot|pdf|zip|gz|tgz|mp4|webm|lock)$|(^|\/)(package-lock\.json|pnpm-lock\.yaml)$/i;

export default function relocatePortClaim(tree: Tree): void {
  const moved: string[] = [];
  for (const file of FILES) {
    const from = `${OLD_DIR}/${file}`;
    if (!tree.exists(from)) continue;
    const body = tree.read(from, 'utf8') ?? '';
    if (!body.includes(HOUSE_STAMP)) {
      logger.warn(`${TAG} ${from} does not carry the house stamp — it is not the generator's copy, so it is LEFT IN PLACE. The house arbiter now lives in ${NEW_DIR}/.`);
      continue;
    }
    const to = `${NEW_DIR}/${file}`;
    const relocated = body
      .split(HOUSE_STAMP)
      .join('Generated by @bespunky/nx-tools:port-claim')
      .split(`node --test ${OLD_DIR}/`)
      .join(`node --test ${NEW_DIR}/`);
    if (!tree.exists(to)) tree.write(to, relocated, file.endsWith('.test.mjs') ? undefined : { mode: 0o755 });
    tree.delete(from);
    moved.push(`${from} -> ${to}`);
  }
  if (moved.length) logger.info(`${TAG} Moved ${moved.join(', ')}.`);

  const touched: string[] = [];
  const walk = (dir: string): void => {
    let children: string[];
    try {
      children = tree.children(dir);
    } catch {
      return;
    }
    for (const child of children) {
      const path = dir ? `${dir}/${child}` : child;
      if (SKIP_DIRS.has(child) || path === '.claude/worktrees') continue;
      if (!tree.isFile(path)) {
        walk(path);
        continue;
      }
      if (BINARY.test(path)) continue;
      let text: string;
      try {
        text = tree.read(path, 'utf8') ?? '';
      } catch {
        continue;
      }
      let next = text;
      for (const [from, to] of REWRITES) next = next.split(from).join(to);
      if (next !== text) {
        tree.write(path, next);
        touched.push(path);
      }
    }
  };
  walk('');
  if (touched.length) logger.info(`${TAG} Re-pointed references to ${NEW_DIR}/ in: ${touched.join(', ')}.`);
}
