// House generator: write the BeSpunky-standard .devcontainer/ — devcontainer.json, the post-create script, the
// one LOCAL devcontainer feature that devcontainer.json references by relative path, and the host probe — run on
// the host before every open, it makes each workspace bind source exist (a fresh clone has none of the
// gitignored ones) and, when `voice` is on, bridges the host's PulseAudio-protocol socket (WSLg or native
// PulseAudio/PipeWire) into the container. Writes through the Nx Tree.
//
// COMPOSED FROM THE ACTIVE LAYERS. Each layer states its share of the container as data (`descriptor.devcontainer`
// — image, features, extensions, settings, mounts, env, run args, ports, OS packages, post-create pieces), and
// `compose.ts` assembles the shares of the layers this project has — into devcontainer.json, post-create.sh, and the
// image the container BUILDS (house.Dockerfile + the one package installer house.packages.sh: the OS packages as a
// cached Docker layer). There is no flag per layer here any more:
// a Python repo gets a neutral Debian base with Node as a feature (the Nx floor and the house tooling run on
// it) and nothing Node-, web- or Angular-shaped; a Node repo gets the typescript-node image, node_modules and
// its package-manager install; the shared browser's X stack arrives only with `web`. `voice` is not a layer but
// an INTENT ("this project wants audio"), host-neutral — WHERE the host's audio socket lives is a per-machine
// fact the host probe resolves at container-open time — and it contributes a fragment the same way.
//
// MERGE INTO A FOREIGN DEVCONTAINER, never clobber it (the claude-settings lesson, applied to the file with the
// most to lose). A sync run on an EXISTING repo will usually find a .devcontainer/devcontainer.json somebody
// wrote by hand, with their image, their features, their extensions. Overwriting it is the single most
// destructive thing this tool could do. So: a file we wrote is regenerated (we own it), and a file we did NOT
// write is treated as the user's, and we only ADD what's missing — of the ACTIVE layers' fragments only.
import { type Tree, logger, parseJson } from '@nx/devkit';
import { applyEdits, modify } from 'jsonc-parser';
import { existsSync, readFileSync } from 'node:fs';
import { join, posix } from 'node:path';

import type { DevcontainerFragment } from '../../layers/descriptor';
import { activeLayers, claudePlugins, devcontainerFragments } from '../_utils/layer-contributions';
import {
  type Composition,
  type Contributor,
  HOUSE_DOCKERFILE,
  type ImageSource,
  compose,
  renderDevcontainerJson,
  renderHouseDockerfile,
  renderOsPackagesScript,
  renderPostCreate,
} from './compose';
import {
  DEVCONTAINER,
  DEVCONTAINER_MARKER as MARKER,
  type HouseWrite,
  reconcileHouseAdded,
  recordedHouseAdded,
} from '../_utils/devcontainer-provenance';
import { projectNodeMajor } from '../_utils/node-version';

type Json = Record<string, unknown>;

interface DevcontainerSchema {
  name: string;
  /** The layers this devcontainer serves. Default: DETECTED from the workspace. */
  layers?: string[] | string;
  /**
   * Not a layer — an intent: bridge the host's PulseAudio-protocol socket (WSLg or native
   * PulseAudio/PipeWire) into the container, located per machine by the host probe.
   */
  voice?: boolean;
}

/**
 * The line every house post-create script carries in its header. Its presence is how a later run recognises a
 * script as generator-written rather than the project's own — provenance the file states about itself, so no
 * separate marker has to be kept in sync with it. (The 0.24.6 migration keys on the same line.)
 */
export const HOUSE_SCRIPT_MARKER = 'Generated by @bespunky/nx-tools:devcontainer';


/**
 * The one LOCAL devcontainer feature: the folder this generator writes, and — in the composed `features` map
 * (`compose.ts` HOUSE_FEATURE_ID) — the id that points at it. A `./` id is a PATH resolved from the folder
 * holding devcontainer.json, so the two are one fact stated in two files; the folder is written
 * UNCONDITIONALLY (see `writeHouseSetupFeature`) so they can never disagree.
 */
const HOUSE_FEATURE = 'bespunky-house-setup';
const HOUSE_FEATURE_DIR = `.devcontainer/features/${HOUSE_FEATURE}`;

/**
 * The voice INTENT's share of the container. Not a layer — nothing it installs leaves a trace in the workspace
 * to detect — so it lives here, beside the probe it depends on, and composes exactly like a layer fragment.
 */
const VOICE: DevcontainerFragment = {
  remoteEnv: [
    {
      name: 'PULSE_SERVER',
      value: 'unix:/run/bespunky/host/pulse/native',
      why: 'The host audio socket, bridged in by the voice mount at ONE fixed in-container endpoint (bespunky-voice).',
    },
    {
      name: 'BESPUNKY_HOST_WSL_DISTRO',
      value: '${localEnv:WSL_DISTRO_NAME}',
      why: 'A host FACT passed through, empty off WSL — read only by the voice plugin to pick its default mic gain.',
    },
  ],
  mounts: [
    {
      mount: 'source=${localWorkspaceFolder}/.devcontainer/.host/pulse,target=/run/bespunky/host/pulse,type=bind',
      why:
        'Host audio (bespunky-voice). The source is the FIXED path the host probe just pointed at this machine\'s\n' +
        'socket folder — or an empty dir when the host has no audio — so the mount is valid on every host.',
    },
  ],
  osPackages: [
    {
      packages: ['pulseaudio-utils', 'espeak-ng'],
      why:
        'Voice (bespunky-voice): `paplay` reaches the host audio socket, espeak-ng is the free speech floor. Installed\n' +
        'on the voice INTENT, not on a socket being present: a host fact cannot key a cached image layer, and both are small.',
    },
  ],
  postCreate: [{ phase: 'provision', piece: 'voice' }],
};

export default async function devcontainerGenerator(
  tree: Tree,
  options: DevcontainerSchema
): Promise<void> {
  if (!options.name) {
    throw new Error('devcontainer generator requires --name (the devcontainer / project name).');
  }
  // The image tag / Node feature version: the PROJECT's declared Node (.nvmrc) — never the machine running this.
  const nodeMajor = projectNodeMajor(tree);
  const voice = !!options.voice;
  const layers = activeLayers(tree, options.layers);
  const layerIds = layers.map((entry) => entry.id);

  const declared: Contributor[] = [...devcontainerFragments(tree, layers), ...(voice ? [{ id: 'voice', fragment: VOICE }] : [])];
  // The probe follows from the mounts: every workspace bind source it guarantees is one a contributor declared.
  const bindSources = workspaceBindSources(declared);
  const contributors: Contributor[] = bindSources.length ? [...declared, { id: 'host-probe', fragment: HOST_PROBE }] : declared;
  const houseComposition = compose(contributors, { nodeMajor });
  // An ADOPTED devcontainer that keeps an image of its own runs as THAT image's user: the house's mount targets
  // (`{{home}}/.claude`, …) must follow it, and no house `remoteUser` may be added to an image that may not have
  // that user at all — a container that cannot start is the worst thing an additive merge could produce.
  const imageSource = adoptedImageSource(tree, houseComposition.image.ref);
  const composition = imageSource.kind === 'build' ? houseComposition : compose(contributors, { nodeMajor, imageSource });
  const rendered = renderDevcontainerJson(options.name, layerIds, composition);

  // OWNERSHIP. The marker separates "regenerate the file we maintain" from "adopt somebody else's" — and it
  // records that as an EXPLICIT `owned` flag, not as its own existence.
  //
  // Deriving ownership from the marker merely EXISTING is a trap this fell into: the marker was written on
  // both paths, so the run after an adoption saw a marker, concluded it owned the file, and overwrote the
  // devcontainer it had carefully merged into the run before. The guarantee held for exactly one run — the
  // worst kind of bug, because a single-run test passes and the damage lands on somebody's second sync.
  //
  // A missing `owned` on an existing marker reads as NOT owned. That is the safe direction: the cost of
  // being wrong is an additive merge where a regeneration would have done (recoverable, visible in the
  // report below), against overwriting a file we don't own (not recoverable without the backup tag).
  const marker = readMarker(tree);
  const ours = marker?.owned === true;
  const exists = tree.exists(DEVCONTAINER);
  const owning = !exists || ours;

  // Whose postCreateCommand will the container actually run? Captured BEFORE the merge, because the merge
  // is additive: a project that declares none gets ours (so the house script runs), and a project that
  // declares its own keeps it (so the house script would not).
  const foreignPostCreate = exists ? postCreateCommandOf(tree) : undefined;

  // OWNERSHIP DECIDES WHETHER HOUSE KEYS ARE RE-ASSERTED — NEVER WHETHER THE PROJECT'S KEYS SURVIVE.
  //
  // Owning used to mean `tree.write(rendered)`: the whole file replaced, so anything the project had added
  // to a devcontainer we own — a forwarded port, a mount, an extension, and every comment explaining why —
  // was deleted on the next sync. That made the ownership marker a destructive binary, which in turn made
  // `claim-legacy-devcontainer-ownership` far more consequential than it looked: a migration that flipped a
  // flag was really arming a full rewrite of a file it had never read.
  //
  // Both paths now go through the same additive, comment-preserving merge. The only difference is what
  // happens on a key BOTH declare: an owned devcontainer takes the house value (that is what ownership
  // means), an adopted one keeps the project's. Keys the house does not know about survive in both.
  let skipped: string[] = [];
  let houseAdded: HouseWrite[] = [];
  if (!exists) {
    tree.write(DEVCONTAINER, rendered);
  } else {
    ({ skipped, houseAdded } = mergeIntoExisting(tree, rendered, ours ? 'assert' : 'adopt'));
  }
  if (imageSource.kind !== 'build') {
    // Recorded with the other keys the project kept: the house's `build` was NOT added beside its image source.
    skipped.push('build');
    logger.info(
      `[devcontainer] This devcontainer uses an image source of its own, so the house's cached package layer is not ` +
        `used: post-create installs the OS packages it lacks on every container create instead. ` +
        (imageSource.kind === 'house-ref'
          ? `Its image IS the house's (${composition.image.ref}), so switching is safe: replace "image" in ` +
            `${DEVCONTAINER} with "build": { "dockerfile": "${HOUSE_DOCKERFILE}", "context": "." } — the same image, ` +
            `the packages one cached layer.`
          : `Do NOT point it at .devcontainer/${HOUSE_DOCKERFILE}: that builds FROM the house's image, not yours. To ` +
            `cache the packages, install them in your own image's build instead.`),
    );
  }

  writeImageFiles(tree, composition);

  // The LOCAL feature — the thing that makes the house script run in a project whose devcontainer we do
  // not own. Written on BOTH paths (see the function), and after the merge, which is what may have just
  // added `./features/bespunky-house-setup` to a foreign `features` map.
  writeHouseSetupFeature(tree);

  // `invoked` — not merely `owning`. Writing `.devcontainer/post-create.sh` into a project whose
  // postCreateCommand points somewhere else produces a 300-line provisioning script that never runs and
  // never says so: the worst kind of output, because it LOOKS like the setup happened. So the house script
  // only takes that filename when something will actually call it.
  const invoked = owning || !foreignPostCreate || foreignPostCreate.includes('post-create.sh');
  writePostCreate(tree, renderPostCreate(layerIds, composition, claudePlugins(layers)), invoked, owning);

  if (bindSources.length) writeHostProbe(tree, bindSources, voice);

  // The ADOPTION REPORT. An adopted devcontainer diverges from the house spec on every key it already
  // declared, permanently and by design — the merge is additive and never argues with the project's own
  // choices. Until now the only trace of that was a log line that scrolled past, so the divergence grew
  // with nothing to see it. Recording the skipped keys makes it a fact a human (or the SessionStart hook)
  // can look at and decide about. It is a RECORD, never an input: the next run re-reads the files and
  // recomputes the whole thing, exactly as with the layer stamp.
  const record: Json = {
    generator: '@bespunky/nx-tools:devcontainer',
    owned: owning,
    // What this devcontainer was composed for — a RECORD (the next run re-detects), and the carrier of the
    // voice intent, which has nothing in the workspace to detect it by (layers/agent.ts reads it back).
    layers: layerIds,
    voice,
  };
  if (!owning) {
    record.adopted = {
      note:
        'This devcontainer.json was written by the project, not by this generator, so house settings are ' +
        'only ADDED, never changed. The keys below already had project values and were left alone — apply ' +
        'any of them by hand if you want the house behaviour. `houseAdded` is what the house ADDED here — the ' +
        'record that lets a later migration clean up after the house without guessing (an entry counts only ' +
        'while the file still holds it exactly; change or remove one and it is yours).',
      skipped,
      // The PROVENANCE record (generators/_utils/devcontainer-provenance.ts): earlier runs' additions the file
      // still holds, plus this run's. Unlike `skipped` it accumulates — an addition happens once, and the
      // run that made it is the only one that knows.
      houseAdded: reconcileHouseAdded(recordedHouseAdded(marker), houseAdded, tryParse(tree.read(DEVCONTAINER, 'utf8') ?? '')),
    };
  }
  tree.write(MARKER, `${JSON.stringify(record, null, 2)}\n`);
}

/**
 * What the container runs on (`ImageSource`), read from an ADOPTED devcontainer — `build` when the house owns the
 * file, there is none yet, or it already builds from the house Dockerfile (a HOUSE-marked one, under any spelling
 * of its path, or the legacy `dockerFile` key). Otherwise its own image source decides: `house-ref` when it names
 * the house's image; else `foreign`, running as its declared `remoteUser`, else `containerUser`, else `root` (what a
 * plain language image — python, golang, … — runs as), with a note, since that last one is an assumption about an
 * image this generator cannot inspect.
 */
function adoptedImageSource(tree: Tree, houseImage: string): ImageSource {
  if (!tree.exists(DEVCONTAINER) || readMarker(tree)?.owned === true) return { kind: 'build' };
  const existing = tryParse(tree.read(DEVCONTAINER, 'utf8') ?? '');
  if (!existing) return { kind: 'build' };
  if (buildsHouseDockerfile(tree, existing)) return { kind: 'build' };
  if (!['image', 'build', 'dockerFile', 'dockerComposeFile'].some((key) => key in existing)) return { kind: 'build' };
  if (existing.image === houseImage) return { kind: 'house-ref' };
  const declared = [existing.remoteUser, existing.containerUser].find((user) => typeof user === 'string');
  if (typeof declared === 'string') return { kind: 'foreign', runsAs: declared };
  logger.info(
    `[devcontainer] This devcontainer keeps its own image and declares no remoteUser/containerUser, so the house ` +
      `mounts assume it runs as root (e.g. the .claude mount targets /root/.claude). If the image runs as ` +
      `another user, declare "remoteUser" in ${DEVCONTAINER} and re-run the sync.`,
  );
  return { kind: 'foreign', runsAs: 'root' };
}

/** Does this devcontainer build from the HOUSE's Dockerfile — the path, however spelled, and a file the house wrote? */
function buildsHouseDockerfile(tree: Tree, existing: Json): boolean {
  const build = existing.build as Json | undefined;
  const named = (build && typeof build === 'object' ? build.dockerfile : undefined) ?? existing.dockerFile;
  if (typeof named !== 'string' || posix.normalize(named) !== HOUSE_DOCKERFILE) return false;
  return isHouseFile(tree, HOUSE_DOCKERFILE_PATH);
}

/** A path the house may write: nothing is there, or what is there says the house generated it. Never somebody else's. */
function isHouseFile(tree: Tree, path: string): boolean {
  return !tree.exists(path) || (tree.read(path, 'utf8') ?? '').includes(HOUSE_SCRIPT_MARKER);
}

const HOUSE_DOCKERFILE_PATH = `.devcontainer/${HOUSE_DOCKERFILE}`;
const OS_PACKAGES_SCRIPT = '.devcontainer/house.packages.sh';
const OS_PACKAGES_LIST = '.devcontainer/os-packages.txt';
const GITATTRIBUTES = '.devcontainer/.gitattributes';
/** LF in every checkout: a CRLF copy of a shell script dies in dash (`set: Illegal option -`) — the IMAGE BUILD fails. */
const LF_ONLY = ['*.sh text eol=lf', 'os-packages.txt text eol=lf'];

/** The project's own package list — SEEDED once (class C), never regenerated: it is the project's to fill. */
const OS_PACKAGES_STUB = `# This project's own OS (Debian) packages. THIS FILE IS YOURS — created once, never regenerated.
#
# Package NAMES only, one per line (or several, space-separated); \`#\` starts a comment — no versions (\`pkg=1.2\`),
# no architectures (\`pkg:amd64\`). They are installed with the house's when the container image is built
# (.devcontainer/house.Dockerfile) — one cached Docker layer, so a rebuild reinstalls nothing unless a list changed.
# A name apt cannot find FAILS the image build (loudly, rather than a container quietly missing a tool); a virtual
# name (one only "provided" by another package) is never seen as installed, so prefer the real package.
#
# Example:
# postgresql-client
`;

/**
 * The image's files beside devcontainer.json:
 *   house.packages.sh — the one installer (OWNED). Always: post-create runs it too, whatever the image.
 *   house.Dockerfile  — OWNED, written while it is or can safely become the image (build / house-ref); on a foreign
 *                       image it would build the WRONG base, so it is not offered — and a house-written one is removed.
 *   os-packages.txt   — the project's list, SEEDED once.
 * An owned path holding a file the house did not write is never overwritten: it is reported and left.
 * `.devcontainer/.gitattributes` gains the LF lines it lacks (its other lines are the project's).
 */
function writeImageFiles(tree: Tree, composition: Composition): void {
  const owned = (path: string, content: string, mode?: number) => {
    if (!isHouseFile(tree, path)) {
      logger.warn(`[devcontainer] ${path} exists and the house did not write it — left untouched. Rename it to let the house write its own.`);
      return;
    }
    tree.write(path, content, mode === undefined ? undefined : { mode });
  };
  // 0o755 so the shebang/mode rule holds in the output; it is invoked as `sh <path>`, so the mode is not load-bearing.
  owned(OS_PACKAGES_SCRIPT, renderOsPackagesScript(composition.osPackages), 0o755);
  if (composition.imageSource.kind === 'foreign') {
    if (tree.exists(HOUSE_DOCKERFILE_PATH) && isHouseFile(tree, HOUSE_DOCKERFILE_PATH)) tree.delete(HOUSE_DOCKERFILE_PATH);
  } else {
    owned(HOUSE_DOCKERFILE_PATH, renderHouseDockerfile(composition));
  }
  if (!tree.exists(OS_PACKAGES_LIST)) tree.write(OS_PACKAGES_LIST, OS_PACKAGES_STUB);

  const attributes = tree.exists(GITATTRIBUTES) ? (tree.read(GITATTRIBUTES, 'utf8') ?? '') : '';
  const lacking = LF_ONLY.filter((line) => !attributes.split('\n').some((have) => have.trim() === line));
  if (lacking.length) {
    const sep = attributes === '' || attributes.endsWith('\n') ? '' : '\n';
    const heading = attributes.includes('# BeSpunky house') ? '' : '# BeSpunky house — LF in every checkout: the image build runs these with /bin/sh, which a CRLF line breaks.\n';
    tree.write(GITATTRIBUTES, `${attributes}${sep}${heading}${lacking.join('\n')}\n`);
  }
}

interface Marker {
  owned?: boolean;
  adopted?: { houseAdded?: unknown };
}

/**
 * The project's own `postCreateCommand`, as a string, or `undefined` when it has none (or declares it as an
 * array/object form we shouldn't second-guess — treated as "it has one", which is the cautious direction).
 */
function postCreateCommandOf(tree: Tree): string | undefined {
  const parsed = tryParse(tree.read(DEVCONTAINER, 'utf8') ?? '');
  const value = parsed?.postCreateCommand;
  if (value === undefined) return undefined;
  return typeof value === 'string' ? value : JSON.stringify(value);
}

/** The ownership marker, or `null` when absent/unparseable (both of which mean "we don't own this"). */
function readMarker(tree: Tree): Marker | null {
  if (!tree.exists(MARKER)) return null;
  const parsed = tryParse(tree.read(MARKER, 'utf8') ?? '');
  return parsed ? (parsed as Marker) : null;
}

/**
 * The companion script — `.devcontainer/post-create.sh` — owns all multi-step setup so
 * devcontainer.json's postCreateCommand stays a one-liner. It is COMPOSED from the active layers' pieces
 * (`compose.ts` renderPostCreate), and each piece still self-adapts at run time where its trigger can change
 * between syncs (a declared @playwright/test, a host audio socket).
 *
 * TWO conditions must BOTH hold for the house script to take the canonical `post-create.sh` name, and
 * conflating them produced a silent failure each way round:
 *
 *   INVOKED — something will actually run it. Writing a 300-line provisioning script that the project's
 *             postCreateCommand never calls is the worst kind of output: it looks like setup happened.
 *   FREE    — no post-create.sh of somebody else's is already there. Overwriting one would delete their
 *             provisioning with no warning and no undo — worse than the devcontainer.json case, since a
 *             shell script's contents cannot be merged meaningfully.
 *
 * When either fails, the house script goes BESIDE the entry point and the one line needed to chain them is
 * printed for a human to place. Same "detect, don't execute" line the SessionStart hook holds: report the
 * fact, let the person who owns the file make the edit.
 */
function writePostCreate(tree: Tree, house: string, invoked: boolean, owning: boolean): void {
  const HOUSE_PATH = '.devcontainer/post-create.sh';
  const BESIDE_PATH = '.devcontainer/post-create.bespunky.sh';

  // "Free" means no one ELSE'S script is sitting at that path — which includes the case where the script
  // there is OURS from a previous run.
  //
  // Deriving that from `owning` alone was wrong, and wrong in a way that compounded: `owning` describes
  // devcontainer.json, so on an ADOPTED devcontainer it is permanently false, and the generator could never
  // recognise the post-create.sh it had itself written one run earlier. Result: run N wrote the house
  // script, run N+1 decided it was foreign and wrote a second copy beside it — manufacturing the very
  // duplication the beside-path exists to avoid, and re-manufacturing it on every sync thereafter.
  //
  // The script already announces its own provenance in its header, so ask IT rather than tracking more
  // state: a file we generated says so, a file somebody wrote by hand does not.
  const existingHouseScript = tree.exists(HOUSE_PATH) ? tree.read(HOUSE_PATH, 'utf8') ?? '' : '';
  const free = owning || !tree.exists(HOUSE_PATH) || existingHouseScript.includes(HOUSE_SCRIPT_MARKER);
  if (invoked && free) {
    tree.write(HOUSE_PATH, house);
    // A house script parked BESIDE on an earlier run (the project's postCreateCommand ran something else then) is
    // superseded now: left there, the chain feature would still run its stale body first, on every create.
    if (tree.exists(BESIDE_PATH) && (tree.read(BESIDE_PATH, 'utf8') ?? '').includes(HOUSE_SCRIPT_MARKER)) {
      tree.delete(BESIDE_PATH);
      logger.info(`[devcontainer] removed ${BESIDE_PATH} — the house setup now runs as ${HOUSE_PATH}, so the parked copy was superseded.`);
    }
    // The extension point's other half: create it ONCE so it is discoverable, and never touch it again.
    // An empty seam nobody knows about is not a seam.
    if (!tree.exists(LOCAL_PATH)) tree.write(LOCAL_PATH, LOCAL_STUB);
    return;
  }

  tree.write(BESIDE_PATH, house);
  logger.info(
    `[devcontainer] The house setup is in \`${BESIDE_PATH}\` rather than \`${HOUSE_PATH}\`, because ` +
      (free
        ? `this project's \`postCreateCommand\` runs something else, so a script at the usual name would never execute.`
        : `\`${HOUSE_PATH}\` already exists and this generator did not write it.`) +
      `\n    Chain it by adding this line to whatever your postCreateCommand does run:\n` +
      `    bash .devcontainer/post-create.bespunky.sh`
  );
}

const LOCAL_PATH = '.devcontainer/post-create.local.sh';

export const LOCAL_STUB = `#!/usr/bin/env bash
# Project-specific devcontainer setup. THIS FILE IS YOURS.
#
# .devcontainer/post-create.sh is generated by @bespunky/nx-tools and is overwritten on every
# \`house.sh upgrade\`. This file is created once and never regenerated, so anything you put here
# survives. It runs LAST, after workspace deps, Claude plugins and every house prerequisite — so you can
# assume a working environment.
#
# Runs in a subshell; a non-zero exit warns rather than failing the container build.
set -euo pipefail

# OS packages do NOT go here — list them in .devcontainer/os-packages.txt, which the image build installs as a
# cached layer. This file is for everything else: a CLI fetched by script, a login check, a seed step. (If you must
# apt-get here anyway, run \`sudo apt-get update\` first: the image ships with empty package lists.)
`;

const HOST_PROBE_PATH = '.devcontainer/host-probe.sh';
/** The probe's machine-local audio output: the `pulse` bind source and `host.env`. Never committed. */
const HOST_STATE_DIR = '.devcontainer/.host/';

/**
 * The host probe's share of the container: the `initializeCommand` entry that runs it. No layer's — it is
 * contributed whenever the declared mounts name a workspace bind source (see `workspaceBindSources`), which
 * every house devcontainer does (`agent`'s `.claude/data`): the one step every container open runs on the
 * HOST before Docker resolves a mount.
 */
const HOST_PROBE: DevcontainerFragment = {
  initializeCommand: [
    {
      name: 'bespunky-host-probe',
      command: 'sh .devcontainer/host-probe.sh',
      why:
        'The host probe makes every workspace bind mount valid before Docker resolves it: a missing source (a fresh\n' +
        'clone has no gitignored .claude/data) becomes an empty dir. With voice it also points .devcontainer/.host/pulse\n' +
        "at this machine's PulseAudio-protocol socket folder, or leaves an empty dir there. A probe + fixed paths,\n" +
        'because `${localEnv:…}` is resolved before this command runs. It always exits 0.',
    },
  ],
};

/**
 * The workspace-relative sources of every BIND mount the contributors declare (`source=${localWorkspaceFolder}/…`)
 * — what the probe must make exist. Read from the declared fragments, so a new layer's mount is covered by
 * declaring it, with nothing to keep in step. A source outside the workspace (`${localEnv:HOME}/…`) is the
 * host's own and not ours to create.
 */
function workspaceBindSources(contributors: readonly Contributor[]): string[] {
  const sources = contributors.flatMap(({ fragment }) =>
    (fragment.mounts ?? []).flatMap(({ mount }) => {
      if (!/(?:^|,)type=bind(?:,|$)/.test(mount)) return [];
      const source = /(?:^|,)source=\$\{localWorkspaceFolder\}\/([^,]+)/.exec(mount)?.[1];
      return source ? [source.replace(/\/+$/, '')] : [];
    }),
  );
  return [...new Set(sources)];
}

/**
 * The host probe — `.devcontainer/host-probe.sh`, run by devcontainer.json's `initializeCommand` on the host
 * before every container start. An OWNED template artifact: regenerated on every sync, on the owned and the
 * adopted path alike (the adopted merge adds the `initializeCommand` entry that calls it — see
 * `composeCommand`), because a gitignored bind source exists on a fresh clone only once the probe has run.
 * Rendered with the sources it guarantees and whether it bridges audio.
 *
 * Its audio output is a machine fact (this host's socket, or none), so `.devcontainer/.host/` is ignored —
 * committing it would hand one developer's symlink to every teammate's host.
 */
function writeHostProbe(tree: Tree, bindSources: readonly string[], audio: boolean): void {
  const rendered = readFileSync(join(__dirname, 'host-probe.sh.tpl'), 'utf8')
    .replace('{{bindSources}}', bindSources.map((source) => `'${source}'`).join(' '))
    .replace('{{audio}}', audio ? '1' : '0');
  // 0o755: the probe is invoked as `sh <path>`, so the mode is not load-bearing — it is set so a human can
  // run it directly when debugging, and so the shebang/mode checker's rule holds in the output.
  tree.write(HOST_PROBE_PATH, rendered, { mode: 0o755 });
  if (!audio) return;

  const gitignore = tree.exists('.gitignore') ? (tree.read('.gitignore', 'utf8') ?? '') : '';
  if (gitignore.includes(HOST_STATE_DIR)) return;
  const sep = gitignore === '' || gitignore.endsWith('\n') ? '' : '\n';
  tree.write(
    '.gitignore',
    `${gitignore}${sep}\n# Devcontainer host probe — this machine's audio-socket link (machine-local, never shared)\n${HOST_STATE_DIR}\n`
  );
}

/**
 * The one LOCAL devcontainer feature — `.devcontainer/features/bespunky-house-setup/`, referenced from
 * devcontainer.json by the relative id `./features/bespunky-house-setup`.
 *
 * IT INSTALLS NOTHING. Its entire content is a `postCreateCommand` that chains
 * `.devcontainer/post-create.bespunky.sh` when that file exists — and that is precisely the point.
 *
 * WHAT IT FIXES. `writePostCreate` above parks the house script at `post-create.bespunky.sh` whenever the
 * project's own `postCreateCommand` runs something else, and then prints the one line a human would have to
 * add to chain it. Until somebody does, ALL house provisioning — workspace deps, the Claude plugin
 * pre-install, the apt floor, Playwright, the Firebase JDK — silently never runs, in exactly the projects
 * this generator was built to retrofit. The script is written, looks provisioned, and executes never.
 *
 * WHY A FEATURE IS THE MECHANISM THAT CLOSES IT. Feature lifecycle commands are ADDITIVE: the spec has them
 * run BEFORE any command declared in devcontainer.json, never instead of it. So a `features` entry is the
 * one key whose value can *run* something without displacing what the project already runs — and the merge
 * above adds a missing `features` sub-key on the adopted path (`mergeIntoExisting(…, 'adopt')`), which is
 * how it reaches a devcontainer we do not own. Nothing else in this file can: every other house key is
 * either declarative or already spoken for by the project.
 *
 * WHY LOCAL RATHER THAN PUBLISHED. A `./`-prefixed feature is built from the folder beside devcontainer.json
 * — nothing published, nothing downloaded, no second version surface and no second deploy procedure. The
 * templates ship inside @bespunky/nx-tools and are versioned by it.
 *
 * UNCONDITIONAL, on the owned path and the adopted one alike. In an owned project the beside-path does not
 * exist and the chain command no-ops (harmless); in an adopted one it is the thing that makes house setup
 * run at all (essential). Being unconditional is also what removes a whole class of bug: there is no
 * retirement path, so the folder and the reference in devcontainer.json can never disagree — and this
 * generator never deletes a `.devcontainer/features/` folder it may not have written.
 */
function writeHouseSetupFeature(tree: Tree): void {
  // Same `__dirname` idiom as post-create.sh.tpl and the shared-browser generator: the scaffold copies the
  // whole nx-tools tree into node_modules and compiles the .ts → .js in place, so the .tpl files travel
  // beside the compiled generator and `__dirname` is the folder holding them. (`src/**/*.tpl` in the
  // package's `files` is a recursive glob, so the nested features/ templates are published too.)
  const template = (file: string) => join(__dirname, 'features', HOUSE_FEATURE, `${file}.tpl`);

  tree.write(
    `${HOUSE_FEATURE_DIR}/devcontainer-feature.json`,
    readFileSync(template('devcontainer-feature.json'), 'utf8')
  );

  // `install.sh` is the feature's own authorship decision, not this generator's: a feature whose whole
  // content is a lifecycle command may carry a trivial one or none at all. So it is copied IF the template
  // exists rather than assumed — this function's contract is "ship whatever the feature is made of".
  //
  // 0o755 is HYGIENE, not a requirement — and the distinction is worth stating because the opposite claim
  // was written here once and had to be retracted. The devcontainer CLI does not depend on the mode: the
  // build layer it generates runs `chmod -R 0755 <dest>` and the install wrapper runs `chmod +x
  // ./install.sh` before `./install.sh`, so a 0644 file builds fine. The bit is set anyway so the script
  // is directly runnable by a human doing hand-recovery, which is the only case that can observe it.
  // The .json needs no mode; it is only ever read.
  const install = template('install.sh');
  if (existsSync(install)) {
    tree.write(`${HOUSE_FEATURE_DIR}/install.sh`, readFileSync(install, 'utf8'), { mode: 0o755 });
  }
}

/**
 * ADDITIVE merge into a devcontainer.json this generator did not write.
 *
 * The rule is deliberately one-way: add what is missing, never change or remove what is there. A repo that
 * already has a devcontainer has already made choices — its base image, its Node version, its own
 * postCreateCommand — and those choices are almost always load-bearing for a project this generator knows
 * nothing about. Adding an extension it lacks is a courtesy; changing its image is a breakage.
 *
 * The cost is honest and worth naming: an adopted devcontainer does NOT get house updates to keys it
 * already defines. So the skipped keys are REPORTED rather than silently dropped — and returned, so the
 * caller can persist them. The reader can then apply any of them by hand, which is a decision they are
 * equipped to make and this generator is not.
 *
 * Returns the dotted paths that were left as the project had them, and what the house added (the provenance record).
 */
/**
 * Merge the rendered house devcontainer into the one on disk, in place, preserving comments.
 *
 * `mode` is the ONLY difference between owning a devcontainer and adopting one:
 *   - `'assert'` (we own it)  — a key both declare takes the HOUSE value.
 *   - `'adopt'`  (they own it) — a key both declare keeps the PROJECT's value, and is reported.
 *
 * Neither mode ever removes a key the house does not know about, and neither re-serializes the file — so
 * comments, including the ones between array members where people explain why a mount exists, survive both.
 */
function mergeIntoExisting(
  tree: Tree,
  rendered: string,
  mode: 'assert' | 'adopt',
): { skipped: string[]; houseAdded: HouseWrite[] } {
  const existingText = tree.read(DEVCONTAINER, 'utf8') ?? '{}';
  const existing = tryParse(existingText);
  const house = tryParse(rendered);

  if (!existing || !house) {
    logger.warn(
      `[devcontainer] \`${DEVCONTAINER}\` exists but could not be parsed as JSONC, so it was left exactly ` +
        `as-is. Fix or remove it and re-run to get the house devcontainer.`
    );
    return { skipped: [], houseAdded: [] };
  }

  const added: string[] = [];
  const skipped: string[] = [];
  const reasserted: string[] = [];
  const kept: string[] = [];
  // What the house ADDS, structured — the provenance record (see devcontainer-provenance.ts). Every addition
  // goes through `write` or `appendMissing`, so recording there misses none.
  const houseAdded: HouseWrite[] = [];
  let text = existingText;

  const write = (path: (string | number)[], value: unknown, bucket: string[]) => {
    if (isNoise(path, value)) return;
    text = applyEdits(text, modify(text, path, value, { formattingOptions: JSONC_FORMAT }));
    bucket.push(path.join('.'));
    if (bucket === added) houseAdded.push(...asRecorded(path.map(String), value));
  };

  const edit = (path: (string | number)[], value: unknown) => write(path, value, added);

  /**
   * Both sides declare this key with different values. In `assert` mode the house value wins (and the
   * project's own comment around it still survives — only the value is edited in place); in `adopt` mode
   * the project's stands and the divergence is recorded, permanently, in the marker.
   *
   * ONE EXCEPTION, and it belongs here rather than in `write`, because it is a statement about ASSERTING,
   * not about adding: when the HOUSE value is an empty container, there is nothing to assert. `{}` means
   * "this key, with default options" — it carries no information, so writing it over a project value that
   * has some can only ever DELETE information, never impose a house choice.
   *
   * The case that proved it: the feature spec permits the string shorthand, so a project may pin a version
   * on a house feature — `"ghcr.io/devcontainers/features/github-cli": "2.0.0"`. That is a deliberate
   * REFINEMENT of the house's `{}`, not a divergence from it, and it lands here at depth 2. Re-asserting
   * would flatten the pin back to `{}` on every sync while the comment explaining the pin survived
   * beside it — a silent downgrade of somebody's pinned toolchain, in a devcontainer we own.
   */
  const conflict = (path: (string | number)[], value: unknown) => {
    if (mode !== 'assert') {
      skipped.push(path.join('.'));
      return;
    }
    if (isEmptyContainer(value)) {
      kept.push(path.join('.'));
      return;
    }
    write(path, value, reasserted);
  };

  /**
   * Append missing array members ONE AT A TIME, in place.
   *
   * Replacing the whole array would re-serialize it — and take out every comment written BETWEEN its
   * members, which in a devcontainer.json is where people explain why a mount exists. jsonc-parser's
   * array insertion splices a single element at an index and leaves the rest of the text untouched.
   */
  const appendMissing = (path: (string | number)[], house: unknown[], current: unknown[]) => {
    const missing = house.filter((item) => !current.some((have) => sameMember(have, item)));
    let at = current.length;
    for (const item of missing) {
      text = applyEdits(
        text,
        modify(text, [...path, at], item, { formattingOptions: JSONC_FORMAT, isArrayInsertion: true })
      );
      added.push(`${path.join('.')}[+${JSON.stringify(item).slice(0, 40)}]`);
      houseAdded.push({ path: path.map(String), member: item });
      at++;
    }
  };

  for (const [key, value] of Object.entries(house)) {
    if (!(key in existing)) {
      edit([key], value);
      continue;
    }
    const composed = composeCommand(key, value, existing[key]);
    if (composed) {
      // The key now mixes the project's lifted command with the house entries — so the record names the house
      // ENTRIES, never the key: the whole key was never the house's to remove.
      write([key], composed, []);
      added.push(key);
      for (const [entry, entryValue] of Object.entries(value as Json)) houseAdded.push({ path: [key, entry], value: entryValue });
      continue;
    }
    // Present already — recurse one useful level into the containers where "missing sub-key" is the
    // common, safe case, and leave scalars strictly alone.
    if (isPlainObject(value) && isPlainObject(existing[key])) {
      mergeObject(key, value, existing[key] as Json, edit, appendMissing, conflict);
    } else if (Array.isArray(value) && Array.isArray(existing[key])) {
      appendMissing([key], value, existing[key] as unknown[]);
    } else if (!sameValue(value, existing[key])) {
      conflict([key], value);
    }
  }

  // Say what changed only when something did: a re-sync of a complete file writes nothing and claims nothing.
  if (text === existingText) return { skipped, houseAdded };
  tree.write(DEVCONTAINER, text);

  if (mode === 'assert') {
    logger.info(
      `[devcontainer] Updated the house-owned \`${DEVCONTAINER}\` in place.\n` +
        `  added:       ${added.length ? added.join(', ') : '(nothing — already complete)'}\n` +
        `  re-asserted: ${reasserted.length ? reasserted.join(', ') : '(nothing — already matching)'}\n` +
        (kept.length
          ? `  kept yours:  ${kept.join(', ')} (the house value there is empty — "with defaults" — so ` +
            `asserting it could only discard what you set, e.g. a feature version pin)\n`
          : '') +
        `  (keys this generator does not manage, and every comment, were left untouched)`
    );
  } else {
    logger.info(
      `[devcontainer] Adopted the existing \`${DEVCONTAINER}\` (not generator-written) — merged additively.\n` +
        `  added:      ${added.length ? added.join(', ') : '(nothing — already complete)'}\n` +
        `  left as-is: ${skipped.length ? skipped.join(', ') : '(nothing)'}\n` +
        `  (recorded in \`${MARKER}\` — this project keeps its own values for those keys)`
    );
  }

  return { skipped, houseAdded };
}

/**
 * A whole value the merge wrote, broken into record entries at the SAME granularity the merge itself works at
 * (`mergeIntoExisting` / `mergeObject`): a map's entries one level down (`features.<id>`, `remoteEnv.<name>`),
 * three levels for `customizations.vscode.*`, an array's members one by one. Recorded whole, the entry would
 * stop holding the moment the next run added a sibling — `features` written as one map is no longer that map
 * once a later layer adds a feature — and the provenance of everything in it would be pruned with it.
 */
function asRecorded(path: string[], value: unknown): HouseWrite[] {
  if (Array.isArray(value)) return value.map((member) => ({ path, member }));
  const depth = path[0] === 'customizations' ? 4 : 2;
  if (isPlainObject(value) && Object.keys(value).length && path.length < depth) {
    return Object.entries(value).flatMap(([key, inner]) => asRecorded([...path, key], inner));
  }
  return [{ path, value }];
}

/** Merge one nested object level: add absent keys, recurse into objects, union arrays, keep scalars. */
function mergeObject(
  prefix: string,
  house: Json,
  existing: Json,
  edit: (path: (string | number)[], value: unknown) => void,
  appendMissing: (path: (string | number)[], house: unknown[], current: unknown[]) => void,
  conflict: (path: (string | number)[], value: unknown) => void
): void {
  for (const [key, value] of Object.entries(house)) {
    const path = [prefix, key];
    if (!(key in existing)) {
      edit(path, value);
      continue;
    }
    if (isPlainObject(value) && isPlainObject(existing[key])) {
      // One more level covers customizations.vscode.{extensions,settings}, which is where the depth is.
      for (const [inner, innerValue] of Object.entries(value)) {
        const innerPath = [...path, inner];
        const have = (existing[key] as Json)[inner];
        if (have === undefined) edit(innerPath, innerValue);
        else if (Array.isArray(innerValue) && Array.isArray(have)) appendMissing(innerPath, innerValue, have);
        else if (isPlainObject(innerValue) && isPlainObject(have)) {
          for (const [leaf, leafValue] of Object.entries(innerValue)) {
            if (!(leaf in (have as Json))) edit([...innerPath, leaf], leafValue);
            else if (!sameValue(leafValue, (have as Json)[leaf])) conflict([...innerPath, leaf], leafValue);
          }
        } else if (!sameValue(innerValue, have)) conflict(innerPath, innerValue);
      }
      continue;
    }
    if (Array.isArray(value) && Array.isArray(existing[key])) {
      appendMissing(path, value, existing[key] as unknown[]);
      continue;
    }
    if (!sameValue(value, existing[key])) conflict(path, value);
  }
}

/**
 * Lifecycle commands the house declares in the spec's OBJECT form — named entries, run in parallel.
 *
 * Only `initializeCommand` (the host probe) today. `postCreateCommand` is deliberately NOT here: the house
 * reaches a foreign one through the local feature instead (see `writeHouseSetupFeature`), and its ordering
 * relative to the project's provisioning matters in a way the probe's does not.
 */
const COMPOSABLE_COMMANDS = new Set(['initializeCommand']);

/** The key a project's own string/array command is kept under once lifted into object form. */
const PROJECT_COMMAND_KEY = 'project';

/**
 * When the project already has a STRING or ARRAY form of a composable command, the house value can't be
 * added beside it — and BOTH ordinary outcomes are wrong:
 *   - adopt mode would keep theirs and report it. But a skipped probe is not a cosmetic divergence: the voice
 *     mount's source is the probe's output, so the container would refuse to START. A report nobody acts on
 *     in time is a broken container.
 *   - assert mode would write the house object over theirs, deleting a command we know nothing about.
 *
 * The spec's object form makes the dilemma false: `{ "project": <their command>, "bespunky-host-probe": … }`
 * runs exactly what they ran (a string still goes through a shell, an array still doesn't) AND the probe.
 * Lifting their value under its own key changes the SHAPE of the key, never what it does — so it is still
 * additive in the sense adoption promises (nothing of theirs is changed or lost), and it is the same move in
 * both modes. An existing OBJECT form needs none of this: the ordinary merge just adds the missing entry.
 *
 * Returns the composed value, or `undefined` when this key/shape isn't a composition case.
 */
function composeCommand(key: string, house: unknown, current: unknown): Json | undefined {
  if (!COMPOSABLE_COMMANDS.has(key) || !isPlainObject(house)) return undefined;
  if (typeof current !== 'string' && !Array.isArray(current)) return undefined;
  return { [PROJECT_COMMAND_KEY]: current, ...house };
}

/**
 * Do the project's value and the house value already AGREE?
 *
 * This is what makes the adoption report mean "where this project DIVERGES from the house" rather than the
 * far less useful "which keys happened to exist". Without it the report grew on the second run: keys the
 * FIRST run added were then present, so they were re-reported as left-as-is — listing settings that had in
 * fact been applied, which is precisely the confusion the report exists to remove. Structural equality,
 * since these are config values (scalars, small arrays and objects), not identities.
 */
function sameValue(a: unknown, b: unknown): boolean {
  return a === b || JSON.stringify(a) === JSON.stringify(b);
}

/**
 * The house keys whose CONTENTS are the information, so that rendering them empty means "nothing here" —
 * `"forwardPorts": []` in a repo that forwards nothing tells a reader less than the absent key did. These
 * are exactly the two keys this generator COMPUTES whole (from the layer flags) and can legitimately
 * render empty; adding them empty is noise, so it is suppressed.
 *
 * NAMED, rather than derived from the path's DEPTH — and the distinction is the bug. The guard used to
 * suppress EVERY empty container at every depth, which is exactly wrong for the other shape of container
 * in this file: a map whose KEYS are the information, where `{}` is a legitimate value meaning "with
 * defaults". A devcontainer feature is that shape — `"ghcr.io/…/github-cli": {}`,
 * `"./features/bespunky-house-setup": {}` — so in any project that already declared a `features` map, EVERY
 * house feature was silently dropped: the new local one, and `claude-code` and `github-cli` with it. The
 * one merge that has to work for an adopted devcontainer, skipped without a word.
 *
 * "Without a word" is why it went unnoticed for so long: the guard returned BEFORE `bucket.push`, so the
 * skip reached neither the log nor the adoption report — the report that exists precisely to make an
 * adopted devcontainer's divergence visible listed nothing, because nothing was even attempted.
 *
 * Depth cannot separate the two shapes and must not be used as a proxy for them: `portsAttributes` is a
 * map-of-options at depth 1, `features.<id>` is a map entry at depth 2. Only the key knows.
 */
const NOISE_WHEN_EMPTY = new Set(['forwardPorts', 'portsAttributes']);

/** Is writing `value` at `path` an addition that carries no information? (See `NOISE_WHEN_EMPTY`.) */
function isNoise(path: (string | number)[], value: unknown): boolean {
  return path.length === 1 && NOISE_WHEN_EMPTY.has(String(path[0])) && isEmptyContainer(value);
}

/** An empty array or empty object — something whose addition would carry no information. */
function isEmptyContainer(value: unknown): boolean {
  if (Array.isArray(value)) return value.length === 0;
  return isPlainObject(value) && Object.keys(value).length === 0;
}

/**
 * Are two array members "the same thing"? Exact equality for scalars; for a MOUNT string, equality of its
 * `target=` — because a mount that targets the same path is the same mount however its source is spelled,
 * and adding a second one for the same target is what breaks a container rather than enriching it.
 */
function sameMember(a: unknown, b: unknown): boolean {
  if (a === b) return true;
  if (typeof a === 'string' && typeof b === 'string') {
    const target = (s: string) => /(?:^|,)target=([^,]+)/.exec(s)?.[1];
    const ta = target(a);
    const tb = target(b);
    if (ta && tb) return ta === tb;
  }
  return JSON.stringify(a) === JSON.stringify(b);
}

const JSONC_FORMAT = { tabSize: 2, insertSpaces: true, eol: '\n' };

function tryParse(source: string): Json | undefined {
  try {
    const parsed: unknown = parseJson(source);
    return isPlainObject(parsed) ? parsed : undefined;
  } catch {
    return undefined;
  }
}

function isPlainObject(value: unknown): value is Json {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}
