#!/usr/bin/env node
// port-claim — arbitration for HOST ports, shared by every BeSpunky devcontainer on this machine.
//
// WHY THIS EXISTS, AND WHY IT IS NOT BASH
// A container cannot discover which host port the editor forwarded it to. So the only way a
// `localhost:<port>` URL printed *inside* a container can be true is to bind a number no one else on
// the host holds — i.e. to ARBITRATE, across containers, before binding. The substrate is a claim file
// per port in a docker volume every BeSpunky devcontainer mounts (one engine = one host = one set of
// contended ports).
//
// Arbitration is a registry with ownership, expiry and atomicity — not process supervision. Bash is the
// right material for `ss`/`flock`/`/proc`/`setsid`; it is the wrong material for this, and the cost was
// real: the bash version's `[ -f claim ] && write` needed an flock, and on lock timeout it proceeded
// UNLOCKED, leaving a genuine double-booking race. Node's `open(path,'wx')` is atomic create-if-absent,
// so the race disappears by construction rather than by holding a lock — there is no lock to time out.
//
// TWO KINDS OF PORT, ONE REGISTRY
//   · MOVABLE  (the shared browser's noVNC port) — `allocate` searches a band for a port that is free
//     everywhere and claims it. Losing a race just means taking the next slot.
//   · SINGLE-OWNER (`:80` for the worktree-domains proxy, `:4200` for the OAuth-registered dev server) —
//     the number is baked into URLs or an OAuth origin, so it CANNOT move. `advise` therefore does not
//     search: it reports whether this container owns the host port. First container wins; the rest are
//     TOLD, which is the whole point — the failure they'd otherwise hit is silent and unattributable.
//
// Every verb prints one JSON object to stdout and exits 0, or prints {"error":...} and exits 1.
// Pure node: built-ins only, no deps, no network beyond a 1s TCP probe.
//
// Generated by @bespunky/nx-tools:port-claim. Edit the template in the toolkit, not this copy.
import { closeSync, openSync, readdirSync, readFileSync, renameSync, statSync, unlinkSync, writeSync } from 'node:fs';
import { join } from 'node:path';
import { createServer, connect } from 'node:net';

const DEFAULTS = { bandStart: {{novncBandStart}}, bandSize: {{novncBandSize}}, ttl: 604800 };

// ── args ─────────────────────────────────────────────────────────────────────────────────────────────
const argv = process.argv.slice(2);
const verb = argv[0] ?? '';
const opt = (name, fallback) => {
  const hit = argv.find((a) => a.startsWith(`--${name}=`));
  return hit === undefined ? fallback : hit.slice(name.length + 3);
};
const num = (name, fallback) => {
  const v = opt(name);
  if (v === undefined || v === '') return fallback;
  const n = Number(v);
  if (!Number.isInteger(n)) die(`--${name} must be an integer (got '${v}')`);
  return n;
};

/** A TCP port argument: 1..65535, refused otherwise — never an uncaught socket error or a `99999.claim`. */
const MAX_PORT = 65535;
const portArg = (name, fallback) => {
  const n = num(name, fallback);
  if (n !== fallback && (n < 1 || n > MAX_PORT)) die(`--${name} must be a port in 1..${MAX_PORT} (got ${n})`);
  return n;
};

const registry = opt('registry', '');
const identity = opt('identity', '');
const gateway = opt('gateway', '');
const ttl = num('ttl', DEFAULTS.ttl);
const bandStart = portArg('band-start', DEFAULTS.bandStart);
const bandSize = num('band-size', DEFAULTS.bandSize);
if (bandSize < 1 || bandStart + bandSize - 1 > MAX_PORT) {
  die(`the band ${bandStart}..${bandStart + bandSize - 1} must hold at least one port and end at or below ${MAX_PORT}`);
}

function die(message) {
  process.stdout.write(JSON.stringify({ error: message }) + '\n');
  process.exit(1);
}
function emit(obj) {
  process.stdout.write(JSON.stringify(obj) + '\n');
  process.exit(0);
}

// ── registry primitives ──────────────────────────────────────────────────────────────────────────────
// A registry is usable only if we can actually write claims into it. Anything else (not mounted, wrong
// UID, read-only) means "no registry" — allocation still works, it just loses the cross-container gate,
// and the caller is told so it can say that out loud instead of degrading in silence.
function registryUsable() {
  if (!registry) return false;
  try {
    // NEVER create it. The registry is a MOUNT POINT the devcontainer provides; a directory this
    // process made would be container-local, so it would look perfectly usable while giving exactly
    // zero cross-container guarantee — a silent degradation of the one gate that carries the promise.
    // Absent means absent, and the caller says so out loud.
    if (!statSync(registry).isDirectory()) return false;
    const probe = join(registry, `.w-${process.pid}`);
    closeSync(openSync(probe, 'wx'));
    unlinkSync(probe);
    return true;
  } catch {
    return false;
  }
}
const claimPath = (port) => join(registry, `${port}.claim`);

/** {owner, at, stale} for a port, or null when unclaimed/unreadable. */
function readClaim(port) {
  try {
    const body = readFileSync(claimPath(port), 'utf8');
    const owner = (body.split('\n')[0] ?? '').trim();
    if (!owner) return null;
    const ageMs = Date.now() - statSync(claimPath(port)).mtimeMs;
    return { owner, stale: ageMs > ttl * 1000 };
  } catch {
    return null;
  }
}

/** Write `body` to a private file, then return its path — the half of a write nobody else can see. */
function stage(port, body) {
  const tmp = join(registry, `${port}.claim.tmp-${process.pid}-${Date.now()}`);
  const fd = openSync(tmp, 'wx');
  try { writeSync(fd, body); } finally { closeSync(fd); }
  return tmp;
}

/** How long a REPLACE mutex may sit before it is presumed abandoned by a crashed process. */
const MUTEX_STALE_MS = 10_000;
/** How long to wait for a live holder — its critical section is one read, one write and one rename. */
const MUTEX_WAIT_MS = 2_000;
const pause = (ms) => Atomics.wait(new Int32Array(new SharedArrayBuffer(4)), 0, 0, ms);

/**
 * Run `fn` holding the port's REPLACE mutex (`<port>.claim.lock`, created `wx`). Only replacing an EXISTING claim
 * takes it; creating an absent one never does. A held mutex is WAITED for (briefly) rather than read as a loss:
 * the holder may be this same container refreshing its own claim, and giving up would walk us to another port.
 * Returns fn's result, or false when the mutex could not be had.
 */
function withReplaceMutex(port, fn) {
  const mutex = `${claimPath(port)}.lock`;
  const acquire = () => {
    for (const end = Date.now() + MUTEX_WAIT_MS; ; pause(5)) {
      try {
        closeSync(openSync(mutex, 'wx'));
        return true;
      } catch (e) {
        if (e?.code !== 'EEXIST') return false;
      }
      // A replacer that crashed inside its critical section leaves the mutex behind; age it out rather than
      // wedging the port for ever. (Two processes reaping the same abandoned mutex in one instant is the
      // residue, and it needs a crash first.)
      try {
        if (Date.now() - statSync(mutex).mtimeMs >= MUTEX_STALE_MS) unlinkSync(mutex);
      } catch { /* released meanwhile */ }
      if (Date.now() >= end) return false;
    }
  };
  if (!acquire()) return false;
  try {
    return fn();
  } finally {
    try { unlinkSync(mutex); } catch { /* already gone */ }
  }
}

/**
 * Take a port ATOMICALLY.
 *
 *   ABSENT   `wx` create — it fails if the file exists, so exactly one racing container can create it.
 *   PRESENT  a replacement (our own refresh, an expired claim, a garbage file) is decided and done UNDER the
 *            port's replace mutex, re-reading the claim there, and lands by RENAME over the old file. The old
 *            way — unlink, then `wx` — was two steps: two containers that both judged a claim stale could each
 *            unlink and each write, and the second unlink deleted the first's FRESH claim, so both reported
 *            `mine:true` for one port. Under the mutex the second re-reads, finds a live claim that is not its
 *            own, and backs off; and since a rename never leaves the path empty, no `wx` creator slips in.
 */
function takeClaim(port, { allowTakeover }) {
  const body = `${identity}\nclaimed ${new Date().toISOString()}\n`;
  try {
    const fd = openSync(claimPath(port), 'wx');
    try { writeSync(fd, body); } finally { closeSync(fd); }
    return true;
  } catch (e) {
    if (e?.code !== 'EEXIST') return false;
  }
  return withReplaceMutex(port, () => {
    const existing = readClaim(port);
    // Garbage (zero-length / unreadable) is not a reservation; ours is a refresh (mtime is the TTL heartbeat).
    const replaceable = !existing || existing.owner === identity || (existing.stale && allowTakeover);
    if (!replaceable) return false;
    let tmp;
    try {
      tmp = stage(port, body);
      renameSync(tmp, claimPath(port));
      return true;
    } catch {
      if (tmp) try { unlinkSync(tmp); } catch { /* never staged */ }
      return false;
    }
  });
}

/** Release every claim in our name except `keep` — a claim is a reservation for ONE port. */
function gcOwnClaims(keep, isLive) {
  if (!registryUsable()) return [];
  const dropped = [];
  for (const file of readdirSync(registry)) {
    if (!file.endsWith('.claim')) continue;
    const port = Number(file.slice(0, -'.claim'.length));
    if (!Number.isInteger(port) || port === keep) continue;
    // NEVER release a port something is actually serving on: that hands a live, forwarded port to a
    // neighbour and manufactures the collision this registry exists to prevent.
    if (isLive(port)) continue;
    if (readClaim(port)?.owner !== identity) continue;
    try { unlinkSync(claimPath(port)); dropped.push(port); } catch { /* best effort */ }
  }
  return dropped;
}

// ── gates ────────────────────────────────────────────────────────────────────────────────────────────
/**
 * Free to bind here, in THIS container's network namespace.
 *
 * A probe is itself a momentary bind, so two racers probing one port at the same instant each see the OTHER'S
 * probe and read the port as busy — which walked one container racing itself onto two ports. A real listener
 * holds the port across every attempt; a probe holds it for a millisecond. So a few spaced attempts, and free
 * on the first that binds.
 */
async function localFree(port) {
  const once = () =>
    new Promise((resolve) => {
      const srv = createServer();
      srv.once('error', () => resolve(false));
      srv.once('listening', () => srv.close(() => resolve(true)));
      srv.listen(port, '127.0.0.1');
    });
  for (let attempt = 0; attempt < 5; attempt++) {
    if (await once()) return true;
    await new Promise((r) => setTimeout(r, 10 + Math.floor(Math.random() * 30)));
  }
  return false;
}

/**
 * Is anything answering on the HOST at this port? Best-effort by construction: it goes out over the
 * gateway, so it sees host listeners on the all-interfaces address but may be blind to ones bound to the
 * host's own 127.0.0.1 (which is what the editor's forwards are). Used ONLY to reject a port — never as
 * proof of freeness — so a blind or absent probe costs precision, never correctness of startup.
 */
function hostBusy(port) {
  if (!gateway) return Promise.resolve(false);
  return new Promise((resolve) => {
    const sock = connect({ host: gateway, port, timeout: 1000 });
    const done = (busy) => { sock.destroy(); resolve(busy); };
    sock.once('connect', () => done(true));
    sock.once('error', () => done(false));
    sock.once('timeout', () => done(false));
  });
}

/** Stable small hash of a key → a slot in [0, size). Same shape as the serve executor's blockForKey. */
export function stableSlot(key, size) {
  let h = 0;
  for (let i = 0; i < key.length; i++) h = (h * 31 + key.charCodeAt(i)) >>> 0;
  return h % size;
}

// ── verbs ────────────────────────────────────────────────────────────────────────────────────────────
/**
 * Find and claim a MOVABLE port.
 *
 * `--recorded` (the port we last held) gets FIRST REFUSAL so the URL doesn't drift: if our hashed slot
 * was taken when we first allocated we settled for the next one, and once that neighbour disappears a
 * plain walk would reach the hashed slot first and hand the human a new URL under their old bookmark.
 * First refusal is not immunity, though — it still passes the gates, because "the claim is ours" is
 * evidence about the registry, not about the host.
 */
async function cmdAllocate() {
  if (!identity) die('--identity is required');
  const haveRegistry = registryUsable();
  const recorded = portArg('recorded', 0);
  const live = portArg('live', 0); // a port we are currently serving on; never GC'd
  const isLive = (p) => p === live;

  // Returns null when the port is unavailable, else {reclaimed} — reclaimed meaning we got back a port
  // this container already held, which is what makes a bookmarked viewer URL survive a rebuild.
  const tryPort = async (port, { allowTakeover }) => {
    let mineAlready = false;
    if (haveRegistry) {
      const existing = readClaim(port);
      if (existing && existing.owner !== identity && !existing.stale) return null;
      mineAlready = existing?.owner === identity;
    }
    if (!(await localFree(port))) return null;
    if (await hostBusy(port)) return null;
    if (haveRegistry && !takeClaim(port, { allowTakeover })) return null;
    return { reclaimed: mineAlready };
  };

  if (recorded && haveRegistry && readClaim(recorded)?.owner === identity) {
    const got = await tryPort(recorded, { allowTakeover: true });
    if (got) {
      const dropped = gcOwnClaims(recorded, isLive);
      emit({ port: recorded, reclaimed: true, registry: true, hostProbe: !!gateway, dropped });
    }
  }

  const start = stableSlot(identity, bandSize);
  for (let i = 0; i < bandSize; i++) {
    const port = bandStart + ((start + i) % bandSize);
    const got = await tryPort(port, { allowTakeover: true });
    if (got) {
      const dropped = haveRegistry ? gcOwnClaims(port, isLive) : [];
      emit({ port, reclaimed: got.reclaimed, registry: haveRegistry, hostProbe: !!gateway, dropped });
    }
  }
  die(
    `no free port in ${bandStart}..${bandStart + bandSize - 1} — widen the band, or pin one explicitly.`
  );
}

/** Refresh our claim's TTL (the liveness heartbeat), only when the claim is unowned or already ours. */
function cmdRefresh() {
  if (!identity) die('--identity is required');
  const port = portArg('port', 0);
  if (!port) die('--port is required');
  if (!registryUsable()) emit({ ok: false, registry: false });
  const existing = readClaim(port);
  if (existing && existing.owner !== identity && !existing.stale) {
    emit({ ok: false, registry: true, owner: existing.owner, conflict: true });
  }
  emit({ ok: takeClaim(port, { allowTakeover: true }), registry: true, owner: identity });
}

/** Give a port back — only ever our own claim. */
function cmdRelease() {
  const port = portArg('port', 0);
  if (!port) die('--port is required');
  if (!registryUsable()) emit({ ok: false, registry: false });
  if (readClaim(port)?.owner !== identity) emit({ ok: false, registry: true, notOurs: true });
  try { unlinkSync(claimPath(port)); } catch { /* already gone */ }
  emit({ ok: true, registry: true });
}

/**
 * SINGLE-OWNER arbitration: report whether this container owns a host port that cannot move.
 *
 * There is no searching and no failure here — the caller binds its own container-local port either way.
 * What this buys is ATTRIBUTION: `<slug>.localhost` has no port to remap, so with two containers up the
 * host tab silently shows whichever one won host :80, and real Google OAuth silently belongs to whoever
 * won :4200. Turning "silently wrong" into "told which container owns it" is the entire deliverable.
 */
function cmdAdvise() {
  if (!identity) die('--identity is required');
  const port = portArg('port', 0);
  if (!port) die('--port is required');
  if (!registryUsable()) emit({ port, owner: 'unknown', mine: true, registry: false });
  const taken = takeClaim(port, { allowTakeover: true });
  if (taken) emit({ port, owner: identity, mine: true, registry: true });
  const existing = readClaim(port);
  emit({ port, owner: existing?.owner ?? 'unknown', mine: false, registry: true });
}

/** Who holds a port (diagnostics). */
function cmdOwner() {
  const port = portArg('port', 0);
  if (!port) die('--port is required');
  if (!registryUsable()) emit({ port, owner: null, registry: false });
  const existing = readClaim(port);
  emit({ port, owner: existing?.owner ?? null, stale: existing?.stale ?? null, registry: true });
}

const RUN = {
  allocate: cmdAllocate,
  refresh: cmdRefresh,
  release: cmdRelease,
  advise: cmdAdvise,
  owner: cmdOwner,
};

// Importable for tests (node:test spawns this file as a CLI *and* imports stableSlot).
if (process.argv[1] && process.argv[1].endsWith('port-claim.mjs')) {
  const run = RUN[verb];
  if (!run) die(`unknown verb '${verb}' (expected: ${Object.keys(RUN).join(' | ')})`);
  await run();
}
