// House generator: write the BeSpunky-standard .devcontainer/ — devcontainer.json, the post-create script,
// and the LOCAL devcontainer features the json references by relative path.
// Reads its own bundled templates (not workspace files) and writes through the Nx Tree.
//
// Template supports two kinds of placeholders:
//   - simple substitution:   {{name}}, {{nodeMajor}}, {{forwardPorts}}, {{portsAttributes}}
//   - conditional blocks:    {{#flag}}...{{/flag}}  -> included iff the flag option is truthy
//
// The flags are the LAYERS this devcontainer serves (`web`, `angular`, `firebase`) plus the one host axis
// (`voice`). They are passed in by the caller, which detects them — this generator never guesses.
//
// TWO properties earn the extra machinery here:
//
// 1. COMMAS ARE THE GENERATOR'S PROBLEM, NOT THE TEMPLATE AUTHOR'S. Wrapping JSON members in conditional
//    blocks means every block boundary is a potential `[, 4200]` or `{"a":1,}`. Hand-placing commas so that
//    every combination of four flags stays valid is 16 cases a template author has to hold in their head,
//    and the failure mode is a container that won't build. So the template writes members naively and the
//    generator NORMALIZES dangling commas afterwards, then PARSES the result and throws if it isn't valid —
//    a template mistake fails here, loudly, at generation time, instead of at someone's next rebuild.
//
// 2. MERGE INTO A FOREIGN DEVCONTAINER, never clobber it (the claude-settings lesson, applied to the file
//    with the most to lose). A sync run on an EXISTING repo — the whole point of layering — will usually
//    find a .devcontainer/devcontainer.json somebody wrote by hand, with their image, their features, their
//    extensions. Overwriting it is the single most destructive thing this tool could do. So: a file we
//    wrote is regenerated (we own it), and a file we did NOT write is treated as the user's, and we only
//    ADD what's missing.
import { type Tree, logger, parseJson } from '@nx/devkit';
import { applyEdits, modify } from 'jsonc-parser';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';

import { NOVNC_BAND_LABEL, novncPortsAttributesJson } from '../shared-browser/novnc-band';

type Json = Record<string, unknown>;

interface DevcontainerSchema {
  name: string;
  nodeMajor?: string | number;
  /** Layer: a project with something to serve — :80 worktree domains, the shared browser, Playwright. */
  web?: boolean;
  /** Layer: Angular — the editor extensions and the 4200 dev-server port label. */
  angular?: boolean;
  /** Layer: Firebase — CLI features, emulator ports, the JDK note. */
  firebase?: boolean;
  /** Host axis (WSL only), not a layer: the WSLg PulseAudio bridge. */
  voice?: boolean;
}

/**
 * The line post-create.sh.tpl carries in its own header. Its presence is how a later run recognises a
 * script as generator-written rather than the project's own — provenance the file states about itself,
 * so no separate marker has to be kept in sync with it.
 */
const HOUSE_SCRIPT_MARKER = 'Generated by @bespunky/nx-tools:devcontainer';

const DEVCONTAINER = '.devcontainer/devcontainer.json';
const MARKER = '.devcontainer/.bespunky-devcontainer.json';

/**
 * Where the LOCAL devcontainer features are written, and the prefix devcontainer.json references them by.
 * A feature id starting with `./` is a path relative to the folder holding devcontainer.json — so these two
 * constants are one fact stated twice and must agree: `FEATURES_DIR` is what this generator writes,
 * `FEATURE_REF` is what the template's `features` block asks the CLI to build.
 */
const FEATURES_DIR = '.devcontainer/features';
const FEATURE_REF = './features';

export default async function devcontainerGenerator(
  tree: Tree,
  options: DevcontainerSchema
): Promise<void> {
  if (!options.name) {
    throw new Error('devcontainer generator requires --name (the devcontainer / project name).');
  }
  // Default the image tag to the Node major we are running under (the base image), if not given.
  const nodeMajor = String(options.nodeMajor ?? process.versions.node.split('.')[0]);
  const flags: Record<string, boolean> = {
    web: options.web ?? true,
    angular: options.angular ?? false,
    firebase: !!options.firebase,
    voice: !!options.voice,
  };

  const rendered = render(
    readFileSync(join(__dirname, 'devcontainer.json.tpl'), 'utf8'),
    options.name,
    nodeMajor,
    flags
  );

  // OWNERSHIP. The marker separates "regenerate the file we maintain" from "adopt somebody else's" — and it
  // records that as an EXPLICIT `owned` flag, not as its own existence.
  //
  // Deriving ownership from the marker merely EXISTING is a trap this fell into: the marker was written on
  // both paths, so the run after an adoption saw a marker, concluded it owned the file, and overwrote the
  // devcontainer it had carefully merged into the run before. The guarantee held for exactly one run — the
  // worst kind of bug, because a single-run test passes and the damage lands on somebody's second sync.
  //
  // A missing `owned` on an existing marker reads as NOT owned. That is the safe direction: the cost of
  // being wrong is an additive merge where a regeneration would have done (recoverable, visible in the
  // report below), against overwriting a file we don't own (not recoverable without the backup tag).
  const marker = readMarker(tree);
  const ours = marker?.owned === true;
  const exists = tree.exists(DEVCONTAINER);
  const owning = !exists || ours;

  // Whose postCreateCommand will the container actually run? Captured BEFORE the merge, because the merge
  // is additive: a project that declares none gets ours (so the house script runs), and a project that
  // declares its own keeps it (so the house script would not).
  const foreignPostCreate = exists ? postCreateCommandOf(tree) : undefined;

  // OWNERSHIP DECIDES WHETHER HOUSE KEYS ARE RE-ASSERTED — NEVER WHETHER THE PROJECT'S KEYS SURVIVE.
  //
  // Owning used to mean `tree.write(rendered)`: the whole file replaced, so anything the project had added
  // to a devcontainer we own — a forwarded port, a mount, an extension, and every comment explaining why —
  // was deleted on the next sync. That made the ownership marker a destructive binary, which in turn made
  // `claim-legacy-devcontainer-ownership` far more consequential than it looked: a migration that flipped a
  // flag was really arming a full rewrite of a file it had never read.
  //
  // Both paths now go through the same additive, comment-preserving merge. The only difference is what
  // happens on a key BOTH declare: an owned devcontainer takes the house value (that is what ownership
  // means), an adopted one keeps the project's. Keys the house does not know about survive in both.
  let skipped: string[] = [];
  if (!exists) {
    tree.write(DEVCONTAINER, rendered);
  } else {
    skipped = mergeIntoExisting(tree, rendered, ours ? 'assert' : 'adopt');
  }

  // The LOCAL features — written UNCONDITIONALLY, on the owning path and the adopting one alike, and
  // AFTER the merge (which is what may have just added `./features/…` to a foreign `features` map, and
  // what could otherwise re-add an entry `writeFeatures` had just retired).
  //
  // `.devcontainer/features/` is a house-owned artifact no matter who owns devcontainer.json: it is not a
  // setting to negotiate over, it is the implementation the `features` entry points AT. Gating it on
  // `owning` would invert the whole reason these capabilities became features — an adopted project is
  // exactly the case a post-create step cannot reach (its script is written beside, unchained), so it is
  // exactly the case that must get the folder. A missing folder there would turn the one mechanism that
  // survives adoption into a devcontainer.json that fails to build.
  writeFeatures(tree, flags.voice);

  // `invoked` — not merely `owning`. Writing `.devcontainer/post-create.sh` into a project whose
  // postCreateCommand points somewhere else produces a 300-line provisioning script that never runs and
  // never says so: the worst kind of output, because it LOOKS like the setup happened. So the house script
  // only takes that filename when something will actually call it.
  const invoked = owning || !foreignPostCreate || foreignPostCreate.includes('post-create.sh');
  writePostCreate(tree, invoked, owning);

  // The ADOPTION REPORT. An adopted devcontainer diverges from the house spec on every key it already
  // declared, permanently and by design — the merge is additive and never argues with the project's own
  // choices. Until now the only trace of that was a log line that scrolled past, so the divergence grew
  // with nothing to see it. Recording the skipped keys makes it a fact a human (or the SessionStart hook)
  // can look at and decide about. It is a RECORD, never an input: the next run re-reads the files and
  // recomputes the whole thing, exactly as with the layer stamp.
  const record: Json = {
    generator: '@bespunky/nx-tools:devcontainer',
    owned: owning,
    flags,
  };
  if (!owning) {
    record.adopted = {
      note:
        'This devcontainer.json was written by the project, not by this generator, so house settings are ' +
        'only ADDED, never changed. The keys below already had project values and were left alone — apply ' +
        'any of them by hand if you want the house behaviour.',
      skipped,
    };
  }
  tree.write(MARKER, `${JSON.stringify(record, null, 2)}\n`);
}

interface Marker {
  owned?: boolean;
}

/**
 * The project's own `postCreateCommand`, as a string, or `undefined` when it has none (or declares it as an
 * array/object form we shouldn't second-guess — treated as "it has one", which is the cautious direction).
 */
function postCreateCommandOf(tree: Tree): string | undefined {
  const parsed = tryParse(tree.read(DEVCONTAINER, 'utf8') ?? '');
  const value = parsed?.postCreateCommand;
  if (value === undefined) return undefined;
  return typeof value === 'string' ? value : JSON.stringify(value);
}

/** The ownership marker, or `null` when absent/unparseable (both of which mean "we don't own this"). */
function readMarker(tree: Tree): Marker | null {
  if (!tree.exists(MARKER)) return null;
  const parsed = tryParse(tree.read(MARKER, 'utf8') ?? '');
  return parsed ? (parsed as Marker) : null;
}

/**
 * The companion script — `.devcontainer/post-create.sh` — owns all multi-step setup so
 * devcontainer.json's postCreateCommand stays a one-liner. It is self-adapting (its Firebase, Playwright,
 * Angular and voice steps each detect their own trigger at run time), so it ships verbatim, untemplated.
 *
 * TWO conditions must BOTH hold for the house script to take the canonical `post-create.sh` name, and
 * conflating them produced a silent failure each way round:
 *
 *   INVOKED — something will actually run it. Writing a 300-line provisioning script that the project's
 *             postCreateCommand never calls is the worst kind of output: it looks like setup happened.
 *   FREE    — no post-create.sh of somebody else's is already there. Overwriting one would delete their
 *             provisioning with no warning and no undo — worse than the devcontainer.json case, since a
 *             shell script's contents cannot be merged meaningfully.
 *
 * When either fails, the house script goes BESIDE the entry point and the one line needed to chain them is
 * printed for a human to place. Same "detect, don't execute" line the SessionStart hook holds: report the
 * fact, let the person who owns the file make the edit.
 */
function writePostCreate(tree: Tree, invoked: boolean, owning: boolean): void {
  const house = readFileSync(join(__dirname, 'post-create.sh.tpl'), 'utf8');
  const HOUSE_PATH = '.devcontainer/post-create.sh';
  const BESIDE_PATH = '.devcontainer/post-create.bespunky.sh';

  // "Free" means no one ELSE'S script is sitting at that path — which includes the case where the script
  // there is OURS from a previous run.
  //
  // Deriving that from `owning` alone was wrong, and wrong in a way that compounded: `owning` describes
  // devcontainer.json, so on an ADOPTED devcontainer it is permanently false, and the generator could never
  // recognise the post-create.sh it had itself written one run earlier. Result: run N wrote the house
  // script, run N+1 decided it was foreign and wrote a second copy beside it — manufacturing the very
  // duplication the beside-path exists to avoid, and re-manufacturing it on every sync thereafter.
  //
  // The script already announces its own provenance in its header, so ask IT rather than tracking more
  // state: a file we generated says so, a file somebody wrote by hand does not.
  const existingHouseScript = tree.exists(HOUSE_PATH) ? tree.read(HOUSE_PATH, 'utf8') ?? '' : '';
  const free = owning || !tree.exists(HOUSE_PATH) || existingHouseScript.includes(HOUSE_SCRIPT_MARKER);
  if (invoked && free) {
    tree.write(HOUSE_PATH, house);
    // The extension point's other half: create it ONCE so it is discoverable, and never touch it again.
    // An empty seam nobody knows about is not a seam.
    if (!tree.exists(LOCAL_PATH)) tree.write(LOCAL_PATH, LOCAL_STUB);
    return;
  }

  tree.write(BESIDE_PATH, house);
  logger.info(
    `[devcontainer] The house setup is in \`${BESIDE_PATH}\` rather than \`${HOUSE_PATH}\`, because ` +
      (free
        ? `this project's \`postCreateCommand\` runs something else, so a script at the usual name would never execute.`
        : `\`${HOUSE_PATH}\` already exists and this generator did not write it.`) +
      `\n    Chain it by adding this line to whatever your postCreateCommand does run:\n` +
      `    bash .devcontainer/post-create.bespunky.sh`
  );
}

const LOCAL_PATH = '.devcontainer/post-create.local.sh';

const LOCAL_STUB = `#!/usr/bin/env bash
# Project-specific devcontainer setup. THIS FILE IS YOURS.
#
# .devcontainer/post-create.sh is generated by @bespunky/nx-tools and is overwritten on every
# \`scaffold.sh --sync\`. This file is created once and never regenerated, so anything you put here
# survives. It runs LAST, after workspace deps, Claude plugins and every house prerequisite — so you can
# assume a working environment.
#
# Runs in a subshell; a non-zero exit warns rather than failing the container build.
set -euo pipefail

# Example — install a project-specific tool:
# sudo apt-get update -qq && sudo apt-get install -y --no-install-recommends postgresql-client
`;

/**
 * The LOCAL devcontainer features — `.devcontainer/features/<name>/`, referenced from devcontainer.json by
 * the relative id `./features/<name>`.
 *
 * WHY FEATURES AND NOT MORE post-create.sh. A `features` entry survives ADOPTION by construction: the merge
 * above adds a missing sub-key to a foreign `features` map, so the capability installs in a project whose
 * devcontainer this generator does not own. A post-create step survives nothing — that project keeps its own
 * `post-create.sh`, the house script lands beside it as `post-create.bespunky.sh`, and unless a human chains
 * it every capability provisioned there silently never installs. Same detect-don't-execute honesty applies:
 * we can write the file, we cannot make their script call it.
 *
 * WHY LOCAL AND NOT PUBLISHED. A relative-path feature is built from the folder next to devcontainer.json, so
 * there is nothing published, nothing downloaded, and — the constraint that decided it — no second deploy
 * procedure beside the npm payload. The templates ship inside @bespunky/nx-tools and are versioned by it.
 *
 * The feature templates are authored as `.tpl` siblings of this generator (features/<name>/*.tpl) and ship
 * verbatim, untemplated — exactly like post-create.sh.tpl. Each `install.sh` detects its own triggers at run
 * time, so there is no flag to interpolate; the ONE thing the flags decide is whether a feature is written
 * at all.
 */
function writeFeatures(tree: Tree, voice: boolean): void {
  // The OS floor is always-on: it is the apt baseline every house capability assumes.
  writeFeature(tree, 'os-floor');

  // Voice is the one host axis (WSL only), so it is written on demand — and RETIRED when the flag is off.
  if (voice) writeFeature(tree, 'voice');
  else retireFeature(tree, 'voice');
}

/** Write one feature's two files from its `.tpl` siblings of this generator. */
function writeFeature(tree: Tree, name: string): void {
  // Same `__dirname` idiom as post-create.sh.tpl and the shared-browser generator: the scaffold copies the
  // whole nx-tools tree into node_modules and compiles the .ts → .js in place, so the .tpl files travel
  // alongside the compiled generator and `__dirname` is the folder holding them. (`src/**/*.tpl` in the
  // package's `files` is recursive, so the nested features/ templates are published too.)
  const source = (file: string) => readFileSync(join(__dirname, 'features', name, `${file}.tpl`), 'utf8');

  tree.write(`${FEATURES_DIR}/${name}/devcontainer-feature.json`, source('devcontainer-feature.json'));

  // 0o755 is LOAD-BEARING here, unlike the shared-browser CLI's convenience bit: the devcontainer CLI
  // EXECUTES install.sh directly during the image build. Without the exec bit the build fails — at
  // `Rebuild Container`, far from this line. The .json needs no mode; it is only ever read.
  tree.write(`${FEATURES_DIR}/${name}/install.sh`, source('install.sh'), { mode: 0o755 });
}

/**
 * Retire a feature this run does not want: remove its folder AND the devcontainer.json entry that points at
 * it. BOTH HALVES, or neither — and that is the whole reason this is not a one-line `tree.delete`.
 *
 * The merge is strictly additive: it never removes a key, so an entry written by a previous voice-enabled run
 * SURVIVES a run with the flag off, on the owned path as much as the adopted one. Delete only the folder and
 * the surviving entry points at nothing — a hard, immediate build failure on the next Rebuild Container.
 * Leave only the entry and the capability keeps installing while devcontainer.json claims the project no
 * longer has it. So the retirement removes the reference first and the implementation with it.
 *
 * Removing a key from a devcontainer this generator does not own is the one exception to "add, never change",
 * and a narrow one: the `./features/` namespace addresses a folder this generator exclusively writes, so an
 * entry there can only have come from a previous run of this generator. It is our key, in our folder, being
 * withdrawn — not a project choice being overruled.
 */
function retireFeature(tree: Tree, name: string): void {
  const dir = `${FEATURES_DIR}/${name}`;
  const ref = `${FEATURE_REF}/${name}`;

  const text = tree.exists(DEVCONTAINER) ? tree.read(DEVCONTAINER, 'utf8') ?? '' : '';
  const parsed = tryParse(text);
  const features = parsed && isPlainObject(parsed.features) ? (parsed.features as Json) : undefined;
  const referenced = !!features && ref in features;

  if (!referenced && !tree.exists(dir)) return;

  if (referenced) {
    // In-place edit, like every other write to this file — a re-serialize would take out the comments
    // people write between their own features.
    tree.write(
      DEVCONTAINER,
      applyEdits(text, modify(text, ['features', ref], undefined, { formattingOptions: JSONC_FORMAT }))
    );
  }
  if (tree.exists(dir)) tree.delete(dir);

  logger.info(
    `[devcontainer] Retired the \`${name}\` feature: removed \`${dir}\`` +
      (referenced ? ` and its \`${ref}\` entry in \`${DEVCONTAINER}\`.` : ` (nothing referenced it).`) +
      `\n    Re-enable it by re-running with the flag that turns it on.`
  );
}

/**
 * Template -> final JSONC text: expand conditional blocks, substitute placeholders, sync the commas the
 * blocks left behind, and PROVE the result parses.
 */
function render(template: string, name: string, nodeMajor: string, flags: Record<string, boolean>): string {
  // 1) Conditional blocks: {{#flag}}body{{/flag}} -> body if flag truthy, else removed.
  const expanded = template.replace(
    /\{\{#(\w+)\}\}([\s\S]*?)\{\{\/\1\}\}/g,
    (_, flag: string, body: string) => (flags[flag] ? body : '')
  );

  // 2) Simple placeholders. forwardPorts and portsAttributes are COMPUTED rather than written as
  //    conditional template text: they are pure data with no interleaved comments, and computing them is
  //    what keeps the port list and its labels from drifting apart across four flag combinations.
  //    The noVNC band in particular comes from the SHARED band constants, never hand-written here — an
  //    entry missing for a port the allocator can pick is precisely a port that fails silently.
  const content = expanded
    .split('{{name}}')
    .join(name)
    .split('{{nodeMajor}}')
    .join(nodeMajor)
    .split('{{forwardPorts}}')
    .join(forwardPortsJson(flags))
    .split('{{portsAttributes}}')
    .join(portsAttributesJson(flags))
    .split('{{novncBand}}')
    .join(NOVNC_BAND_LABEL);

  const normalized = normalizeCommas(content);

  // 3) PROVE it. Every flag combination has to produce parseable JSONC, and the only moment we can cheaply
  //    find out is now. Without this check a bad block boundary ships a devcontainer.json that fails at
  //    `Rebuild Container`, with an error pointing at a line the author never wrote.
  try {
    parseJson(normalized);
  } catch (error) {
    throw new Error(
      `[devcontainer] The rendered devcontainer.json is not valid JSONC for flags ` +
        `(${Object.entries(flags).filter(([, on]) => on).map(([f]) => f).join(', ') || 'none'}): ` +
        `${(error as Error).message}\n` +
        `This is a bug in devcontainer.json.tpl's conditional blocks, not in the workspace.`
    );
  }

  return normalized;
}

/**
 * Remove the commas conditional blocks orphan: before a closing bracket, after an opening one, and doubled
 * between two removed members. String-aware, so a comma inside a value (a mount spec, a label) is never
 * touched — the reason this is a small parser rather than three regexes.
 */
function normalizeCommas(source: string): string {
  const out: string[] = [];
  let inString = false;
  let inLineComment = false;
  let inBlockComment = false;

  for (let i = 0; i < source.length; i++) {
    const char = source[i];
    const next = source[i + 1];

    if (inLineComment) {
      out.push(char);
      if (char === '\n') inLineComment = false;
      continue;
    }
    if (inBlockComment) {
      out.push(char);
      if (char === '*' && next === '/') {
        out.push(next);
        i++;
        inBlockComment = false;
      }
      continue;
    }
    if (inString) {
      out.push(char);
      if (char === '\\') {
        // Escape: consume the next character verbatim so a \" can't end the string.
        if (next !== undefined) {
          out.push(next);
          i++;
        }
      } else if (char === '"') {
        inString = false;
      }
      continue;
    }

    if (char === '"') {
      inString = true;
      out.push(char);
      continue;
    }
    if (char === '/' && next === '/') {
      inLineComment = true;
      out.push(char);
      continue;
    }
    if (char === '/' && next === '*') {
      inBlockComment = true;
      out.push(char);
      continue;
    }

    if (char === ',') {
      // Drop this comma when the next meaningful character closes the container (dangling), or when the
      // previous meaningful character opened it / was itself a comma (leading or doubled).
      const nextMeaningful = peekMeaningful(source, i + 1);
      const prevMeaningful = lastMeaningful(out);
      if (
        nextMeaningful === ']' ||
        nextMeaningful === '}' ||
        nextMeaningful === ',' ||
        prevMeaningful === '[' ||
        prevMeaningful === '{' ||
        prevMeaningful === ',' ||
        prevMeaningful === undefined
      ) {
        continue;
      }
    }

    out.push(char);
  }

  // Collapse the blank-line runs a removed block leaves behind, so the output reads as if it were written
  // for these flags rather than edited down to them.
  return out.join('').replace(/\n[ \t]*\n[ \t]*\n+/g, '\n\n');
}

/**
 * The next non-whitespace, non-comment character from `start`, or undefined at end of input.
 *
 * Skipping COMMENTS is the part that matters: this file is dense with them, and a member removed by a
 * conditional block routinely leaves its comma separated from the closing bracket by a paragraph of prose.
 * A scan that stopped at the first `/` would call that comma load-bearing and leave `{,}` behind.
 */
function peekMeaningful(source: string, start: number): string | undefined {
  let i = start;
  while (i < source.length) {
    const char = source[i];
    if (char === ' ' || char === '\t' || char === '\n' || char === '\r') {
      i++;
      continue;
    }
    if (char === '/' && source[i + 1] === '/') {
      const end = source.indexOf('\n', i);
      if (end === -1) return undefined;
      i = end + 1;
      continue;
    }
    if (char === '/' && source[i + 1] === '*') {
      const end = source.indexOf('*/', i);
      if (end === -1) return undefined;
      i = end + 2;
      continue;
    }
    return char;
  }
  return undefined;
}

/**
 * The last emitted non-whitespace character.
 *
 * Unlike the forward scan this does NOT skip backwards over comments — and doesn't need to. It exists only
 * to catch a LEADING or DOUBLED comma, where the preceding character is `[`, `{` or `,` directly. If a
 * comment happens to precede the comma, the scan returns some prose character, which matches none of those
 * and so keeps the comma — the safe direction: this pass only ever deletes a comma it is sure about, and
 * anything it wrongly keeps is caught by the parse check.
 */
function lastMeaningful(out: string[]): string | undefined {
  for (let i = out.length - 1; i >= 0; i--) {
    const char = out[i];
    if (char === ' ' || char === '\t' || char === '\n' || char === '\r') continue;
    return char;
  }
  return undefined;
}

interface Port {
  port: number;
  label: string;
  onAutoForward: 'silent' | 'notify' | 'openPreview';
  /**
   * Forward at the SAME host number? Only for ports something OUTSIDE the container dials by a hardcoded
   * address (the Firebase SDK in a host-loaded page). Everything else is left to auto-forward, which is
   * free to remap — and a port that is labelled but not forwarded still gets its `onAutoForward` behaviour.
   */
  forward: boolean;
}

/**
 * The ports this devcontainer cares about — ONE list, from which both `forwardPorts` and `portsAttributes`
 * are derived. They were two hand-maintained lists gated on different flags, which is why `firebase` without
 * `angular` used to forward 4200 and then not label it. One list makes that class of drift unrepresentable.
 */
function ports(flags: Record<string, boolean>): Port[] {
  const list: Port[] = [];

  if (flags.web) {
    list.push({
      port: 80,
      label: 'Worktree domains (pretty <slug>.localhost URLs)',
      onAutoForward: 'silent',
      forward: true,
    });
  }

  // The dev server is labelled whenever there IS one — but only Firebase needs it pinned to the same host
  // port (the SDK inside a host-loaded page dials hardcoded localhost addresses; see the template).
  if (flags.angular || flags.firebase) {
    list.push({
      port: 4200,
      label: flags.angular ? 'Angular Dev Server' : 'Dev Server',
      onAutoForward: 'openPreview',
      forward: !!flags.firebase,
    });
  }

  if (flags.firebase) {
    list.push(
      { port: 4000, label: 'Firebase Emulator UI', onAutoForward: 'notify', forward: true },
      { port: 9099, label: 'Auth Emulator', onAutoForward: 'silent', forward: true },
      { port: 8080, label: 'Firestore Emulator', onAutoForward: 'silent', forward: true },
      { port: 9150, label: 'Firestore WebSocket', onAutoForward: 'silent', forward: true },
      { port: 9199, label: 'Storage Emulator', onAutoForward: 'silent', forward: true },
      { port: 5001, label: 'Functions Emulator', onAutoForward: 'silent', forward: true }
    );
  }

  return list;
}

function forwardPortsJson(flags: Record<string, boolean>): string {
  return `[${ports(flags)
    .filter((entry) => entry.forward)
    .map((entry) => entry.port)
    .join(', ')}]`;
}

function portsAttributesJson(flags: Record<string, boolean>): string {
  const lines = ports(flags).map(
    ({ port, label, onAutoForward }) => `    "${port}": { "label": "${label}", "onAutoForward": "${onAutoForward}" }`
  );

  // The noVNC band is emitted as ONE EXACT KEY PER PORT by the shared band module — never hand-written
  // here, and never as a range (see the template for why a range silently loses `requireLocalPort`).
  if (flags.web) lines.splice(1, 0, novncPortsAttributesJson());

  return `{\n${lines.join(',\n')}\n  }`;
}

/**
 * ADDITIVE merge into a devcontainer.json this generator did not write.
 *
 * The rule is deliberately one-way: add what is missing, never change or remove what is there. A repo that
 * already has a devcontainer has already made choices — its base image, its Node version, its own
 * postCreateCommand — and those choices are almost always load-bearing for a project this generator knows
 * nothing about. Adding an extension it lacks is a courtesy; changing its image is a breakage.
 *
 * The cost is honest and worth naming: an adopted devcontainer does NOT get house updates to keys it
 * already defines. So the skipped keys are REPORTED rather than silently dropped — and returned, so the
 * caller can persist them. The reader can then apply any of them by hand, which is a decision they are
 * equipped to make and this generator is not.
 *
 * Returns the dotted paths that were left as the project had them.
 */
/**
 * Merge the rendered house devcontainer into the one on disk, in place, preserving comments.
 *
 * `mode` is the ONLY difference between owning a devcontainer and adopting one:
 *   - `'assert'` (we own it)  — a key both declare takes the HOUSE value.
 *   - `'adopt'`  (they own it) — a key both declare keeps the PROJECT's value, and is reported.
 *
 * Neither mode ever removes a key the house does not know about, and neither re-serializes the file — so
 * comments, including the ones between array members where people explain why a mount exists, survive both.
 */
function mergeIntoExisting(tree: Tree, rendered: string, mode: 'assert' | 'adopt'): string[] {
  const existingText = tree.read(DEVCONTAINER, 'utf8') ?? '{}';
  const existing = tryParse(existingText);
  const house = tryParse(rendered);

  if (!existing || !house) {
    logger.warn(
      `[devcontainer] \`${DEVCONTAINER}\` exists but could not be parsed as JSONC, so it was left exactly ` +
        `as-is. Fix or remove it and re-run to get the house devcontainer.`
    );
    return [];
  }

  const added: string[] = [];
  const skipped: string[] = [];
  const reasserted: string[] = [];
  let text = existingText;

  const write = (path: (string | number)[], value: unknown, bucket: string[]) => {
    // An EMPTY container is not an addition, it's noise — `"forwardPorts": []` in a repo that forwards
    // nothing tells the reader less than the absent key did.
    //
    // TOP LEVEL ONLY, and the qualifier is load-bearing. That reasoning holds for a key whose CONTENTS are
    // its information (forwardPorts, portsAttributes); it is exactly wrong one level down, where the PATH is
    // the information and `{}` is a legitimate value meaning "defaults". A devcontainer feature is precisely
    // that shape — `"ghcr.io/…/github-cli": {}`, `"./features/os-floor": {}` — so the unqualified guard
    // silently dropped EVERY house feature into a project that already declared a `features` map of its own:
    // the one merge that had to work for an adopted devcontainer, skipped without a word, with the adoption
    // report listing nothing because nothing was even attempted.
    if (path.length === 1 && isEmptyContainer(value)) return;
    text = applyEdits(text, modify(text, path, value, { formattingOptions: JSONC_FORMAT }));
    bucket.push(path.join('.'));
  };

  const edit = (path: (string | number)[], value: unknown) => write(path, value, added);

  /**
   * Both sides declare this key with different values. In `assert` mode the house value wins (and the
   * project's own comment around it still survives — only the value is edited in place); in `adopt` mode
   * the project's stands and the divergence is recorded, permanently, in the marker.
   */
  const conflict = (path: (string | number)[], value: unknown) => {
    if (mode === 'assert') write(path, value, reasserted);
    else skipped.push(path.join('.'));
  };

  /**
   * Append missing array members ONE AT A TIME, in place.
   *
   * Replacing the whole array would re-serialize it — and take out every comment written BETWEEN its
   * members, which in a devcontainer.json is where people explain why a mount exists. jsonc-parser's
   * array insertion splices a single element at an index and leaves the rest of the text untouched.
   */
  const appendMissing = (path: (string | number)[], house: unknown[], current: unknown[]) => {
    const missing = house.filter((item) => !current.some((have) => sameMember(have, item)));
    let at = current.length;
    for (const item of missing) {
      text = applyEdits(
        text,
        modify(text, [...path, at], item, { formattingOptions: JSONC_FORMAT, isArrayInsertion: true })
      );
      added.push(`${path.join('.')}[+${JSON.stringify(item).slice(0, 40)}]`);
      at++;
    }
  };

  for (const [key, value] of Object.entries(house)) {
    if (!(key in existing)) {
      edit([key], value);
      continue;
    }
    // Present already — recurse one useful level into the containers where "missing sub-key" is the
    // common, safe case, and leave scalars strictly alone.
    if (isPlainObject(value) && isPlainObject(existing[key])) {
      mergeObject(key, value, existing[key] as Json, edit, appendMissing, conflict);
    } else if (Array.isArray(value) && Array.isArray(existing[key])) {
      appendMissing([key], value, existing[key] as unknown[]);
    } else if (!sameValue(value, existing[key])) {
      conflict([key], value);
    }
  }

  tree.write(DEVCONTAINER, text);

  if (mode === 'assert') {
    logger.info(
      `[devcontainer] Updated the house-owned \`${DEVCONTAINER}\` in place.\n` +
        `  added:       ${added.length ? added.join(', ') : '(nothing — already complete)'}\n` +
        `  re-asserted: ${reasserted.length ? reasserted.join(', ') : '(nothing — already matching)'}\n` +
        `  (keys this generator does not manage, and every comment, were left untouched)`
    );
  } else {
    logger.info(
      `[devcontainer] Adopted the existing \`${DEVCONTAINER}\` (not generator-written) — merged additively.\n` +
        `  added:      ${added.length ? added.join(', ') : '(nothing — already complete)'}\n` +
        `  left as-is: ${skipped.length ? skipped.join(', ') : '(nothing)'}\n` +
        `  (recorded in \`${MARKER}\` — this project keeps its own values for those keys)`
    );
  }

  return skipped;
}

/** Merge one nested object level: add absent keys, recurse into objects, union arrays, keep scalars. */
function mergeObject(
  prefix: string,
  house: Json,
  existing: Json,
  edit: (path: (string | number)[], value: unknown) => void,
  appendMissing: (path: (string | number)[], house: unknown[], current: unknown[]) => void,
  conflict: (path: (string | number)[], value: unknown) => void
): void {
  for (const [key, value] of Object.entries(house)) {
    const path = [prefix, key];
    if (!(key in existing)) {
      edit(path, value);
      continue;
    }
    if (isPlainObject(value) && isPlainObject(existing[key])) {
      // One more level covers customizations.vscode.{extensions,settings}, which is where the depth is.
      for (const [inner, innerValue] of Object.entries(value)) {
        const innerPath = [...path, inner];
        const have = (existing[key] as Json)[inner];
        if (have === undefined) edit(innerPath, innerValue);
        else if (Array.isArray(innerValue) && Array.isArray(have)) appendMissing(innerPath, innerValue, have);
        else if (isPlainObject(innerValue) && isPlainObject(have)) {
          for (const [leaf, leafValue] of Object.entries(innerValue)) {
            if (!(leaf in (have as Json))) edit([...innerPath, leaf], leafValue);
            else if (!sameValue(leafValue, (have as Json)[leaf])) conflict([...innerPath, leaf], leafValue);
          }
        } else if (!sameValue(innerValue, have)) conflict(innerPath, innerValue);
      }
      continue;
    }
    if (Array.isArray(value) && Array.isArray(existing[key])) {
      appendMissing(path, value, existing[key] as unknown[]);
      continue;
    }
    if (!sameValue(value, existing[key])) conflict(path, value);
  }
}

/**
 * Do the project's value and the house value already AGREE?
 *
 * This is what makes the adoption report mean "where this project DIVERGES from the house" rather than the
 * far less useful "which keys happened to exist". Without it the report grew on the second run: keys the
 * FIRST run added were then present, so they were re-reported as left-as-is — listing settings that had in
 * fact been applied, which is precisely the confusion the report exists to remove. Structural equality,
 * since these are config values (scalars, small arrays and objects), not identities.
 */
function sameValue(a: unknown, b: unknown): boolean {
  return a === b || JSON.stringify(a) === JSON.stringify(b);
}

/** An empty array or empty object — something whose addition would carry no information. */
function isEmptyContainer(value: unknown): boolean {
  if (Array.isArray(value)) return value.length === 0;
  return isPlainObject(value) && Object.keys(value).length === 0;
}

/**
 * Are two array members "the same thing"? Exact equality for scalars; for a MOUNT string, equality of its
 * `target=` — because a mount that targets the same path is the same mount however its source is spelled,
 * and adding a second one for the same target is what breaks a container rather than enriching it.
 */
function sameMember(a: unknown, b: unknown): boolean {
  if (a === b) return true;
  if (typeof a === 'string' && typeof b === 'string') {
    const target = (s: string) => /(?:^|,)target=([^,]+)/.exec(s)?.[1];
    const ta = target(a);
    const tb = target(b);
    if (ta && tb) return ta === tb;
  }
  return JSON.stringify(a) === JSON.stringify(b);
}

const JSONC_FORMAT = { tabSize: 2, insertSpaces: true, eol: '\n' };

function tryParse(source: string): Json | undefined {
  try {
    const parsed: unknown = parseJson(source);
    return isPlainObject(parsed) ? parsed : undefined;
  } catch {
    return undefined;
  }
}

function isPlainObject(value: unknown): value is Json {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}
