#!/usr/bin/env bash
# BeSpunky devcontainer post-create.
#
# Runs ONCE after the container is built (or rebuilt). Owns all multi-step setup
# that doesn't fit cleanly as a devcontainer "feature" — workspace deps, Claude
# Code plugin pre-install, and Firebase prerequisites when this is a Firebase project.
#
# Self-adapting: Firebase steps fire only when `firebase.json` is present at the
# workspace root, so the same script works whether or not --firebase was used at
# scaffold time. Add Firebase later? Re-run --repair --firebase, then rebuild —
# this script picks it up on the next post-create.
#
# Generated by @bespunky/nx-tools:devcontainer. Edit the template in the toolkit,
# not this copy.
set -euo pipefail

# Devcontainer-cli runs postCreateCommand from the workspace root.
WS="$(pwd)"

# --- 1. Workspace deps ---
echo "[post-create] yarn install"
yarn install

# --- 2. Pre-install the BeSpunky claude-toolkit plugins at project scope ---
# So house skills/agents are live the moment the container opens. If the CLI
# isn't reachable (offline rebuild, etc.) we don't fail the build — the project's
# .claude/settings.json declares the marketplace, so Claude on the host offers a
# one-click install on first session instead.
echo "[post-create] pre-installing claude-toolkit plugins"
if claude plugin marketplace add BeSpunky/claude-toolkit \
    && claude plugin install project-starter@claude-toolkit --scope project \
    && claude plugin install engineering@claude-toolkit --scope project; then
  echo "[post-create] claude-toolkit plugins installed at project scope"
else
  echo "[post-create] NOTE: Claude plugin pre-install skipped; .claude/settings.json will offer install on first run"
fi

# --- 3. Firebase prerequisites (auto-detected via firebase.json) ---
# The emulator suite (Firestore / RTDB / Storage) runs on the JVM, so OpenJDK is
# required. We install it via apt — Debian's package mirrors are reliable and
# don't depend on the build phase reaching github.com (which the SDKMAN-based
# `ghcr.io/devcontainers/features/java` feature does, intermittently failing
# under quirky WSL+Docker network paths).
#
# We also install a /etc/profile.d sourcer for the self-extinguishing Firebase
# welcome banner (tools/firebase-welcome.sh in the workspace), so every login
# shell nudges the user toward the cloud-linkage steps until setup is complete.
if [ -f "$WS/firebase.json" ]; then
  echo "[post-create] firebase.json detected — installing OpenJDK (default-jdk-headless) + wiring welcome banner"
  sudo apt-get update -qq
  sudo apt-get install -y --no-install-recommends default-jdk-headless
  echo "[ -f $WS/tools/firebase-welcome.sh ] && source $WS/tools/firebase-welcome.sh" \
    | sudo tee /etc/profile.d/zz-firebase-welcome.sh > /dev/null
  echo "[post-create] Firebase prerequisites ready"
fi

echo "[post-create] done"
