#!/usr/bin/env bash
# BeSpunky devcontainer post-create.
#
# Runs ONCE after the container is built (or rebuilt). Owns all multi-step setup
# that doesn't fit cleanly as a devcontainer "feature" — workspace deps, Claude
# Code plugin pre-install, and Firebase prerequisites when this is a Firebase project.
#
# Self-adapting: Firebase steps fire only when `firebase.json` is present at the
# workspace root, so the same script works whether or not --firebase was used at
# scaffold time. Add Firebase later? Re-run --repair --firebase, then rebuild —
# this script picks it up on the next post-create.
#
# Generated by @bespunky/nx-tools:devcontainer. Edit the template in the toolkit,
# not this copy.
set -euo pipefail

# Devcontainer-cli runs postCreateCommand from the workspace root.
WS="$(pwd)"

# --- 0. Reclaim /home/node/.cache ownership ---
# Docker creates intermediate mount-point directories as root. When the
# devcontainer mounts a volume to /home/node/.cache/ms-playwright (the
# Playwright browser cache), Docker creates the parent /home/node/.cache
# as root:root — so any tool running as `node` that later wants to mkdir
# a sibling under /home/node/.cache hits EACCES (firebase-tools' emulator
# JAR cache is the loud one; yarn/npm caches break silently). This
# chowns just the parent dir, leaving the mounted volume's contents
# untouched. Idempotent: skipped when already node-owned.
if [ -d /home/node/.cache ] && [ "$(stat -c %U /home/node/.cache)" != "node" ]; then
  echo "[post-create] reclaiming /home/node/.cache ownership for node user"
  sudo chown node:node /home/node/.cache
fi

# --- 1. Workspace deps ---
echo "[post-create] yarn install"
yarn install

# --- 2. Pre-install the BeSpunky claude-toolkit plugins at project scope ---
# So house skills/agents are live the moment the container opens. If the CLI
# isn't reachable (offline rebuild, etc.) we don't fail the build — the project's
# .claude/settings.json declares the marketplace, so Claude on the host offers a
# one-click install on first session instead.
echo "[post-create] pre-installing claude-toolkit plugins"
if claude plugin marketplace add BeSpunky/claude-toolkit \
    && claude plugin install project-starter@claude-toolkit --scope project \
    && claude plugin install engineering@claude-toolkit --scope project \
    && claude plugin install workflow@claude-toolkit --scope project \
    && claude plugin install browser-automation@claude-toolkit --scope project \
    && claude plugin install product-ux@claude-toolkit --scope project; then
  echo "[post-create] claude-toolkit plugins installed at project scope"
else
  echo "[post-create] NOTE: Claude plugin pre-install skipped; .claude/settings.json will offer install on first run"
fi

# --- 3. Firebase prerequisites (auto-detected via firebase.json) ---
# The emulator suite (Firestore / RTDB / Storage) runs on the JVM, so OpenJDK is
# required. We install it via apt — Debian's package mirrors are reliable and
# don't depend on the build phase reaching github.com (which the SDKMAN-based
# `ghcr.io/devcontainers/features/java` feature does, intermittently failing
# under quirky WSL+Docker network paths).
#
# We also install a /etc/profile.d sourcer for the self-extinguishing Firebase
# welcome banner (tools/firebase-welcome.sh in the workspace), so every login
# shell nudges the user toward the cloud-linkage steps until setup is complete.
if [ -f "$WS/firebase.json" ]; then
  echo "[post-create] firebase.json detected — installing OpenJDK (default-jdk-headless) + wiring welcome banner"
  sudo apt-get update -qq
  sudo apt-get install -y --no-install-recommends default-jdk-headless
  echo "[ -f $WS/tools/firebase-welcome.sh ] && source $WS/tools/firebase-welcome.sh" \
    | sudo tee /etc/profile.d/zz-firebase-welcome.sh > /dev/null
  echo "[post-create] Firebase prerequisites ready"
fi

# --- 4. Playwright prerequisites (auto-detected via @playwright/test in package.json) ---
# Chromium binary + the apt libs Chromium needs (fonts, libnss3, libatk, …).
# `playwright install --with-deps chromium` does both: it downloads the browser
# into ~/.cache/ms-playwright (mounted as a per-workspace volume by the
# devcontainer generator, so rebuilds reuse the cached browser) and invokes
# sudo internally for the apt step. The typescript-node base image grants
# passwordless sudo to the `node` user, so no prompt.
#
# Self-adapting: fires only when the workspace already declares @playwright/test
# in package.json (the `@bespunky/nx-tools:playwright` generator adds it). So
# the same script works whether or not Playwright was opted in at scaffold time
# — adding `@playwright/test` later and rebuilding picks it up on the next
# post-create.
if grep -q '"@playwright/test"' package.json 2>/dev/null; then
  echo "[post-create] @playwright/test detected — installing Chromium + system deps"
  # Reclaim the Playwright cache VOLUME mount point. The browser cache is a
  # per-workspace Docker volume mounted at /home/node/.cache/ms-playwright, and
  # Docker creates fresh named-volume mount points as root:root. Step 0 chowns the
  # parent /home/node/.cache (so sibling caches like firebase's JAR cache work) but
  # deliberately leaves the volume's contents untouched — so the mount point itself
  # stays root-owned and `playwright install`, running as `node`, hits EACCES the
  # first time it mkdirs inside it (the __dirlock lock dir). Guarded on ownership:
  # runs only on a fresh (empty → instant) volume, no-op on rebuilds where the
  # cache is already node-owned and populated.
  if [ -d /home/node/.cache/ms-playwright ] && [ "$(stat -c %U /home/node/.cache/ms-playwright)" != "node" ]; then
    echo "[post-create] reclaiming /home/node/.cache/ms-playwright volume ownership for node user"
    sudo chown -R node:node /home/node/.cache/ms-playwright
  fi
  # The browser binary is a large download from cdn.playwright.dev. WSL+Docker DNS is
  # intermittently flaky (getaddrinfo ENOTFOUND on an otherwise-working network — apt and the
  # rest of post-create succeed, then this one host fails to resolve), and Playwright's own
  # retries fire too fast to outlast the blip. Without this, a single hiccup would abort the
  # whole post-create (set -e) and leave the container half-provisioned. So retry with backoff,
  # and if it still fails, warn LOUDLY but do NOT fail the build — everything else (deps,
  # plugins, Firebase) is ready and the user can finish this one step once the network settles
  # (same best-effort stance as the claude-toolkit plugin pre-install above).
  pw_ok=0
  for attempt in 1 2 3; do
    if yarn playwright install --with-deps chromium; then pw_ok=1; break; fi
    if [ "$attempt" -lt 3 ]; then
      echo "[post-create] Playwright browser install attempt $attempt/3 failed (often transient WSL/Docker DNS); retrying in $((attempt * 10))s..."
      sleep $((attempt * 10))
    fi
  done
  if [ "$pw_ok" = 1 ]; then
    echo "[post-create] Playwright prerequisites ready"
  else
    echo "[post-create] WARNING: Playwright browser install failed after 3 attempts — likely a transient network/DNS issue."
    echo "[post-create]          The container is otherwise ready; finish this one step once the network settles with:"
    echo "[post-create]            yarn playwright install --with-deps chromium"
  fi
fi

echo "[post-create] done"
