#!/usr/bin/env bash
# BeSpunky devcontainer post-create.
#
# Runs ONCE after the container is built (or rebuilt). Owns all multi-step setup
# that doesn't fit cleanly as a devcontainer "feature" — workspace deps, Claude
# Code plugin pre-install, and Firebase prerequisites when this is a Firebase project.
#
# Self-adapting: Firebase steps fire only when `firebase.json` is present at the
# workspace root, so the same script works whether or not --firebase was used at
# scaffold time. Add Firebase later? Re-run --repair --firebase, then rebuild —
# this script picks it up on the next post-create.
#
# Generated by @bespunky/nx-tools:devcontainer. Edit the template in the toolkit,
# not this copy.
set -euo pipefail

# Devcontainer-cli runs postCreateCommand from the workspace root.
WS="$(pwd)"

# --- 0. Reclaim /home/node/.cache ownership ---
# Docker creates intermediate mount-point directories as root. When the
# devcontainer mounts a volume to /home/node/.cache/ms-playwright (the
# Playwright browser cache), Docker creates the parent /home/node/.cache
# as root:root — so any tool running as `node` that later wants to mkdir
# a sibling under /home/node/.cache hits EACCES (firebase-tools' emulator
# JAR cache is the loud one; yarn/npm caches break silently). This
# chowns just the parent dir, leaving the mounted volume's contents
# untouched. Idempotent: skipped when already node-owned.
if [ -d /home/node/.cache ] && [ "$(stat -c %U /home/node/.cache)" != "node" ]; then
  echo "[post-create] reclaiming /home/node/.cache ownership for node user"
  sudo chown node:node /home/node/.cache
fi

# --- 1. Workspace deps ---
echo "[post-create] yarn install"
yarn install

# --- 2. Pre-install the BeSpunky claude-toolkit plugins at project scope ---
# So house skills/agents are live the moment the container opens. If the CLI
# isn't reachable (offline rebuild, etc.) we don't fail the build — the project's
# .claude/settings.json declares the marketplace, so Claude on the host offers a
# one-click install on first session instead.
echo "[post-create] pre-installing claude-toolkit plugins"
if claude plugin marketplace add BeSpunky/claude-toolkit \
    && claude plugin install bespunky@claude-toolkit --scope project \
    && claude plugin install bespunky-project-starter@claude-toolkit --scope project \
    && claude plugin install bespunky-engineering@claude-toolkit --scope project \
    && claude plugin install bespunky-workflow@claude-toolkit --scope project \
    && claude plugin install bespunky-browser-automation@claude-toolkit --scope project \
    && claude plugin install bespunky-product-ux@claude-toolkit --scope project \
    && claude plugin install bespunky-design-system@claude-toolkit --scope project; then
  echo "[post-create] claude-toolkit plugins installed at project scope"
else
  echo "[post-create] NOTE: Claude plugin pre-install skipped; .claude/settings.json will offer install on first run"
fi

# --- 3. Firebase prerequisites (auto-detected via firebase.json) ---
# The emulator suite (Firestore / RTDB / Storage) runs on the JVM, so OpenJDK is
# required. We install it via apt — Debian's package mirrors are reliable and
# don't depend on the build phase reaching github.com (which the SDKMAN-based
# `ghcr.io/devcontainers/features/java` feature does, intermittently failing
# under quirky WSL+Docker network paths).
#
# We also install a /etc/profile.d sourcer for the self-extinguishing Firebase
# welcome banner (tools/firebase-welcome.sh in the workspace), so every login
# shell nudges the user toward the cloud-linkage steps until setup is complete.
if [ -f "$WS/firebase.json" ]; then
  echo "[post-create] firebase.json detected — installing OpenJDK (default-jdk-headless) + wiring welcome banner"
  sudo apt-get update -qq
  sudo apt-get install -y --no-install-recommends default-jdk-headless
  echo "[ -f $WS/tools/firebase-welcome.sh ] && source $WS/tools/firebase-welcome.sh" \
    | sudo tee /etc/profile.d/zz-firebase-welcome.sh > /dev/null
  echo "[post-create] Firebase prerequisites ready"
fi

# --- 4. Playwright prerequisites (auto-detected via @playwright/test in package.json) ---
# Chromium binary + the apt libs Chromium needs (fonts, libnss3, libatk, …).
# `playwright install --with-deps chromium` does both: it downloads the browser
# into ~/.cache/ms-playwright (mounted as a per-workspace volume by the
# devcontainer generator, so rebuilds reuse the cached browser) and invokes
# sudo internally for the apt step. The typescript-node base image grants
# passwordless sudo to the `node` user, so no prompt.
#
# Self-adapting: fires only when the workspace already declares @playwright/test
# in package.json (the `@bespunky/nx-tools:playwright` generator adds it). So
# the same script works whether or not Playwright was opted in at scaffold time
# — adding `@playwright/test` later and rebuilding picks it up on the next
# post-create.
if grep -q '"@playwright/test"' package.json 2>/dev/null; then
  echo "[post-create] @playwright/test detected — installing Chromium + system deps"
  # Reclaim the Playwright cache VOLUME mount point. The browser cache is a
  # per-workspace Docker volume mounted at /home/node/.cache/ms-playwright, and
  # Docker creates fresh named-volume mount points as root:root. Step 0 chowns the
  # parent /home/node/.cache (so sibling caches like firebase's JAR cache work) but
  # deliberately leaves the volume's contents untouched — so the mount point itself
  # stays root-owned and `playwright install`, running as `node`, hits EACCES the
  # first time it mkdirs inside it (the __dirlock lock dir). Guarded on ownership:
  # runs only on a fresh (empty → instant) volume, no-op on rebuilds where the
  # cache is already node-owned and populated.
  if [ -d /home/node/.cache/ms-playwright ] && [ "$(stat -c %U /home/node/.cache/ms-playwright)" != "node" ]; then
    echo "[post-create] reclaiming /home/node/.cache/ms-playwright volume ownership for node user"
    sudo chown -R node:node /home/node/.cache/ms-playwright
  fi
  # The browser binary is a large download from cdn.playwright.dev. WSL+Docker DNS is
  # intermittently flaky (getaddrinfo ENOTFOUND on an otherwise-working network — apt and the
  # rest of post-create succeed, then this one host fails to resolve), and Playwright's own
  # retries fire too fast to outlast the blip. Without this, a single hiccup would abort the
  # whole post-create (set -e) and leave the container half-provisioned. So retry with backoff,
  # and if it still fails, warn LOUDLY but do NOT fail the build — everything else (deps,
  # plugins, Firebase) is ready and the user can finish this one step once the network settles
  # (same best-effort stance as the claude-toolkit plugin pre-install above).
  pw_ok=0
  for attempt in 1 2 3; do
    if yarn playwright install --with-deps chromium; then pw_ok=1; break; fi
    if [ "$attempt" -lt 3 ]; then
      echo "[post-create] Playwright browser install attempt $attempt/3 failed (often transient WSL/Docker DNS); retrying in $((attempt * 10))s..."
      sleep $((attempt * 10))
    fi
  done
  if [ "$pw_ok" = 1 ]; then
    echo "[post-create] Playwright prerequisites ready"
  else
    echo "[post-create] WARNING: Playwright browser install failed after 3 attempts — likely a transient network/DNS issue."
    echo "[post-create]          The container is otherwise ready; finish this one step once the network settles with:"
    echo "[post-create]            yarn playwright install --with-deps chromium"
  fi
fi

# --- 5. Angular agent skills (auto-detected via @angular/core in package.json) ---
# Angular ships official agent skills (angular-developer, angular-new-app) at
# github.com/angular/skills, authored in Claude's own SKILL.md format (name/description
# frontmatter + a references/ dir of progressive-disclosure docs). We fetch them FRESH
# into .claude/skills/ on every container build rather than vendoring copies, so they
# track upstream Angular with zero maintenance: the skills repo is itself auto-generated
# from angular/angular, so a fork would silently go stale. The committed `.mcp.json`
# (Angular CLI MCP server) is the always-current *knowledge* channel; these skills are
# the always-loaded, triggerable companion. `.claude/skills/` is gitignored (a
# refreshable cache, like node_modules) — the @bespunky/nx-tools:angular-ai generator
# added that ignore rule. Best-effort with retry: a network blip never fails the build
# (same stance as the plugin pre-install and Playwright steps above).
if grep -q '"@angular/core"' package.json 2>/dev/null; then
  echo "[post-create] @angular/core detected — fetching Angular agent skills into .claude/skills/"
  skills_ok=0
  for attempt in 1 2 3; do
    ng_skills_tmp="$(mktemp -d)"
    if git clone --depth 1 --quiet https://github.com/angular/skills "$ng_skills_tmp" 2>/dev/null; then
      mkdir -p "$WS/.claude/skills"
      for s in angular-developer angular-new-app; do
        if [ -d "$ng_skills_tmp/$s" ]; then
          rm -rf "$WS/.claude/skills/$s"
          cp -r "$ng_skills_tmp/$s" "$WS/.claude/skills/$s"
        fi
      done
      rm -rf "$ng_skills_tmp"
      skills_ok=1
      break
    fi
    rm -rf "$ng_skills_tmp"
    if [ "$attempt" -lt 3 ]; then
      echo "[post-create] Angular skills fetch attempt $attempt/3 failed (often transient DNS); retrying in $((attempt * 5))s..."
      sleep $((attempt * 5))
    fi
  done
  if [ "$skills_ok" = 1 ]; then
    echo "[post-create] Angular agent skills ready (.claude/skills/{angular-developer,angular-new-app})"
  else
    echo "[post-create] WARNING: Angular skills fetch failed after 3 attempts — likely a transient network issue."
    echo "[post-create]          The container is otherwise ready; refetch this one step once the network settles with:"
    echo "[post-create]            t=\$(mktemp -d); git clone --depth 1 https://github.com/angular/skills \"\$t\" && mkdir -p .claude/skills && cp -r \"\$t\"/angular-developer \"\$t\"/angular-new-app .claude/skills/ && rm -rf \"\$t\""
  fi
fi

# --- 6. Shared-browser prerequisites (ALWAYS-ON — provisioned in EVERY BeSpunky devcontainer) ---
# The claude-toolkit "shared-browser" capability (tools/shared-browser, started ON DEMAND)
# runs a headed Chromium on a virtual X display and streams it to the human over noVNC on
# :6080. The stack starts lazily, but its OS deps are installed ALWAYS — so any container can
# co-drive a browser with no rebuild. Deps: x11vnc (VNC server) + novnc/websockify (the
# noVNC web client + WS↔TCP bridge) + fluxbox (a minimal WM so Chromium gets a window frame)
# + fonts (liberation + color-emoji so rendered pages and screenshots look right). Also procps
# (sysctl) — the worktree-domains proxy (tools/worktree-domains) lowers this container's
# net.ipv4.ip_unprivileged_port_start so its Node reverse proxy can bind the privileged :80 as
# the non-root `node` user, giving each worktree a pretty http://<slug>.localhost/ domain.
#
# UNCONDITIONAL by design: this fires on every scaffold — it is NOT gated on --firebase,
# @playwright/test, or any other flag (unlike steps 3–5). Best-effort with retry: apt mirrors
# and cdn.playwright.dev are both occasionally flaky over WSL+Docker DNS, so a transient
# failure must only WARN — never abort post-create (set -e) and leave the container
# half-provisioned (same stance as the Playwright and Angular-skills steps above).
echo "[post-create] provisioning shared-browser prerequisites (xvfb/x11vnc/novnc/websockify/fluxbox/fonts + Chromium)"
sb_apt_ok=0
for attempt in 1 2 3; do
  if sudo apt-get update && sudo apt-get install -y xvfb x11vnc novnc websockify fluxbox iproute2 procps curl fonts-liberation fonts-noto-color-emoji; then
    sb_apt_ok=1; break
  fi
  if [ "$attempt" -lt 3 ]; then
    echo "[post-create] shared-browser apt install attempt $attempt/3 failed (often transient WSL/Docker DNS); retrying in $((attempt * 10))s..."
    sleep $((attempt * 10))
  fi
done
if [ "$sb_apt_ok" = 1 ]; then
  echo "[post-create] shared-browser apt deps ready"
else
  echo "[post-create] WARNING: shared-browser apt deps failed after 3 attempts — likely a transient network issue."
  echo "[post-create]          The container is otherwise ready; finish this one step once the network settles with:"
  echo "[post-create]            sudo apt-get update && sudo apt-get install -y xvfb x11vnc novnc websockify fluxbox iproute2 procps curl fonts-liberation fonts-noto-color-emoji"
fi

# Ensure a Playwright Chromium binary exists for the shared browser to launch (the CLI resolves
# it at runtime via whichever of playwright / playwright-core / @playwright/test is installed).
# Step 4 already fetched it when @playwright/test is in package.json — so here we only install
# if it is still MISSING, avoiding a redundant ~150 MB download. Best-effort + retry; a failure
# only warns (the shared-browser CLI's own guard also runs `npx playwright install chromium` on
# first `up` if it is absent, so this is provisioning-ahead, not a hard requirement).
if [ -d /home/node/.cache/ms-playwright ] && \
   find /home/node/.cache/ms-playwright -maxdepth 1 -type d -name 'chromium-*' 2>/dev/null | grep -q .; then
  echo "[post-create] shared-browser: Playwright Chromium already present — skipping install"
else
  echo "[post-create] shared-browser: Playwright Chromium not found — installing"
  sb_pw_ok=0
  for attempt in 1 2 3; do
    if npx --yes playwright install chromium; then sb_pw_ok=1; break; fi
    if [ "$attempt" -lt 3 ]; then
      echo "[post-create] shared-browser Chromium install attempt $attempt/3 failed (often transient DNS); retrying in $((attempt * 10))s..."
      sleep $((attempt * 10))
    fi
  done
  if [ "$sb_pw_ok" = 1 ]; then
    echo "[post-create] shared-browser: Playwright Chromium ready"
  else
    echo "[post-create] WARNING: shared-browser Chromium install failed after 3 attempts — likely a transient network issue."
    echo "[post-create]          The container is otherwise ready; finish this one step once the network settles with:"
    echo "[post-create]            npx playwright install chromium"
  fi
fi

# --- 7. Voice prerequisites (auto-detected via the WSLg audio bridge) ---
# The bespunky-voice plugin speaks (TTS) and listens (STT) through a PulseAudio sink.
# Voice is OPT-IN (scaffold with --voice): the devcontainer generator bridges WSL2's
# WSLg PulseServer (remoteEnv PULSE_SERVER + the /mnt/wslg mount) ONLY when voice was
# requested — /mnt/wslg is WSL-specific, so binding it unconditionally would break
# non-WSL hosts (macOS, Codespaces). So this step self-adapts on that bridge's PRESENCE:
# /mnt/wslg exists in the container IFF --voice put the mount there. When it does, install
# the free espeak-ng TTS floor (+ pulseaudio-utils for `paplay`) and pre-install the plugin,
# so `/voice` speaks the moment the container opens. Piper (the natural-voice upgrade) stays
# a manual, machine-local opt-in via the plugin's install-piper.sh — same stance as the
# claude-toolkit repo's own devcontainer. Best-effort + retry: a transient apt blip only
# warns, never aborts post-create (set -e) and leaves the container half-provisioned
# (same stance as the Playwright, Angular-skills, and shared-browser steps above).
if [ -d /mnt/wslg ]; then
  echo "[post-create] WSLg audio bridge detected (--voice) — provisioning bespunky-voice (espeak-ng + pulseaudio-utils)"
  voice_apt_ok=0
  for attempt in 1 2 3; do
    if sudo apt-get update && sudo apt-get install -y pulseaudio-utils espeak-ng; then
      voice_apt_ok=1; break
    fi
    if [ "$attempt" -lt 3 ]; then
      echo "[post-create] voice apt install attempt $attempt/3 failed (often transient WSL/Docker DNS); retrying in $((attempt * 10))s..."
      sleep $((attempt * 10))
    fi
  done
  if [ "$voice_apt_ok" = 1 ]; then
    echo "[post-create] voice engine ready (espeak-ng floor; run the plugin's install-piper.sh for the neural-voice upgrade)"
  else
    echo "[post-create] WARNING: voice engine install failed after 3 attempts — likely a transient network issue."
    echo "[post-create]          The container is otherwise ready; finish this one step once the network settles with:"
    echo "[post-create]            sudo apt-get update && sudo apt-get install -y pulseaudio-utils espeak-ng"
  fi
  # Pre-install the voice plugin at project scope so /voice is live on open. Best-effort:
  # the marketplace was added in step 2; if that was offline, .claude/settings.json offers
  # install on first run. (The other house plugins are pre-installed unconditionally in
  # step 2; bespunky-voice is gated here because without this WSLg bridge it can't play audio.)
  if claude plugin install bespunky-voice@claude-toolkit --scope project; then
    echo "[post-create] bespunky-voice plugin installed at project scope"
  else
    echo "[post-create] NOTE: bespunky-voice plugin install skipped (CLI offline?) — enable later with /plugin"
  fi
fi

echo "[post-create] done"
