<!-- Generated by @bespunky/nx-tools:design-system. Rewritten on every run — do not hand-edit. -->
# The design system — structure & conventions

This library is the **single source of visual truth** for the workspace. Every colour, space, radius,
type step, elevation, border, duration and easing in the app comes from here. Nothing in a feature
component invents appearance.

It ships with **zero components and zero opinionated styles**, on purpose. What it ships is the
**mechanism** — tokens, a SASS API, and a theme — plus this document, which tells you where things go
when feature work starts producing them.

## The two layers

| Layer | What it is | Where it lives |
| --- | --- | --- |
| **Runtime** — CSS custom properties | What actually ships. Cascades, so a theme change is a **re-binding**, live, with no rebuild and no second stylesheet. | Emitted **once**, by `ds.theme()`, from the app's global stylesheet |
| **Author-time** — the SASS API | Functions, mixins, placeholders. **Zero-output**: `@use`-ing it emits no CSS. Summoned per-file. | `styles/` |

A component reads **semantic** tokens (`color-on-surface`), never a primitive swatch. That is what makes
a re-theme a change to one file instead of a change to a thousand.

## Public vs private — the rule that shapes the layout

Every surface here has a **public API** and an **implementation**, and the two are separated **twice**:

- **At the export level** — a single file *enumerates* what is public: `styles/_index.scss`
  (`@forward … show <exact members>`) for SASS, and `src/index.ts` for TypeScript. **Adding a member does
  not publish it.** Publishing is a deliberate act, performed in the barrel.
- **At the folder level** — the implementation lives in folders whose name starts with **`_`**. The
  underscore says *"not yours"*; the **rest of the name says what the thing is** — `_core`, `_utils`,
  `_parts`, `_material`. Never a folder called `internal`: that names the *access level*, which the `_`
  already carries, and wastes the one chance you had to say what's inside. A
  `@use '…/styles/_core/tokens'` from outside is then visibly reaching past the contract.

**What you export, you must support.** Keep both barrels minimal — a member you never exported is one you
can freely rename, reshape, or delete.

## Layout

```
{{root}}/
├── styles/                          the SASS surface
│   ├── _index.scss                  ★ THE PUBLIC API — @forward … show; the only file anyone outside @use's
│   ├── _core/                       the TOKEN ENGINE (private)
│   │   ├── _tokens.scss             the token maps — THE ONLY FILE ALLOWED TO CONTAIN A LITERAL VALUE
│   │   ├── _functions.scss          token() color() space() radius() … -> var(--{{tokenPrefix}}-*)
│   │   └── _theme.scss              theme() — the one emission; mode() — structural mode branches
│   └── _utils/                      the AUTHORING TOOLKIT (private)
│       ├── _mixins.scss             media() container() focus-ring() elevation() transition() reduced-motion()
│       └── _placeholders.scss       %visually-hidden %reset-button %truncate %overlay-surface
├── src/
│   ├── index.ts                     ★ THE PUBLIC API of the primary entry point ({{importPath}})
│   └── lib/                         the implementation: providers, DsTheme (mode), DsRuntimeTheme.
│                                    ← NO COMPONENTS HERE. Components are secondary entry points (below).
└── <component>/                     one per promoted component — its own SECONDARY ENTRY POINT
    ├── ng-package.json
    └── src/
        ├── index.ts                 ★ THE PUBLIC API of {{importPath}}/<component>
        ├── <component>.component.{ts,html,scss}
        └── _parts/                  sub-components, helpers, types the consumer must not depend on
                                     (name it for what it holds — `_parts`, `_core`, `_material` — never `internal`)
```

Inside a SASS partial you have a third, finer tool: a member named with a **leading `-`** (`-clamp()`) is
private to that *file* and cannot be `@use`d at all, even by a sibling partial.

## Where new things go

**A new token** → `styles/_core/_tokens.scss`.
Mode-independent (a space step, a radius, a duration) → `$base`. Mode-dependent → **every** map in
`$modes`; the build **fails** if a token exists in one mode and not another. That means every **colour**,
and also **elevation** — a shadow is not mode-independent, because a black shadow is invisible on a dark
surface (in dark mode, lift an element with `color-surface-raised` *and* the deeper shadow together).
Name a token for its **meaning** (`color-surface-raised`), not its appearance (`color-gray-100`): a name
that describes a colour cannot survive a re-theme.

**A new component** → a **secondary entry point**, generated, never hand-made:

```bash
nx g @bespunky/nx-tools:ds-component <name>
```

That gives you `{{root}}/<name>/` with its own `ng-package.json`, so it imports as
`{{importPath}}/<name>` and tree-shakes independently. Hand-creating the folder gets you a component
that resolves in dev and vanishes on publish.

**A new mixin / function / placeholder** → the matching partial under `styles/_utils/` (or `styles/_core/`
if it belongs to the token engine itself). It is now usable *inside* the library. To make it **public**, add
its name to the matching `@forward … show` list in `styles/_index.scss` — and only if you're prepared to
support it. If it decides how something *looks*, it does not belong here at all; it belongs in a component.

**Something a component needs but a consumer must not** → a `_`-prefixed folder inside that component's
entry point, named for what it holds (`_parts/`, `_material/`), and left out of its `index.ts`.

## The conventions (these are the rules, not suggestions)

1. **No literal visual values outside `_core/_tokens.scss`.** No raw hex, no magic `px`, no
   `200ms ease` typed by hand. If the value isn't a token, either add the token or you are off-system.
2. **Components read semantic tokens only** — never a primitive, never another component's internals.
3. **Consume the public API, including from inside.** The design system's own components `@use` the same
   `styles` barrel an app does — they do not reach into `_core/` or `_utils/`. If the barrel doesn't expose
   something the library itself needs, that is a **missing public concept**, not a licence to reach past
   it. (Dogfooding the contract is the only way you find out it's wrong before a consumer does.)
4. **The second occurrence of a UI pattern is a promotion, not a copy-paste.** The moment a card, button,
   panel or field appears twice, `nx g @bespunky/nx-tools:ds-component <name>`, migrate **both** sites,
   delete the copies.
5. **When the design system lacks the concept you need, model it here** — add the token, the semantic
   alias, the scale step, the component. Never work around the gap with a local override, an
   `!important`, a `::ng-deep` reach-in, or a one-off `variant` boolean.
6. **`::ng-deep` is banned.** It is "reach into another module's internals", in CSS. A component that
   can't be styled from outside is missing a **token** or a **part** — that is the finding.
7. **Variants are data, not booleans.** `variant: 'primary' | 'danger'` rendered as a host attribute the
   SCSS selects on — not `isPrimary` + `isDanger` + `isBig`, which is four undesigned states.
8. **`ds.theme()` is called exactly once**, from the app's global stylesheet. Everything else is
   zero-output.
9. **The design system never imports from an app.** It is publishable; a reach-back makes it a lie.

## Consuming it

```scss
// any component SCSS, in the app or in here
@use '{{specifier}}' as ds;

:host {
  display: grid;
  gap: ds.space(3);
  padding: ds.space(4);
  color: ds.color('on-surface');
  background: ds.color('surface');
  border: ds.border('width-thin') solid ds.color('border');
  border-radius: ds.radius('md');

  @include ds.media('md') { gap: ds.space(4); }
  @include ds.focus-ring();
}
```

```ts
// switching the mode at runtime — a re-binding of tokens, not a reload
private readonly theme = inject(DsTheme);
toggle() { this.theme.mode.set(this.theme.resolved() === 'dark' ? 'light' : 'dark'); }
```

## Themes (a brand, a tenant palette, a user-selectable skin)

**A theme is a CSS file, not JavaScript.** Generate it — never hand-create it:

```bash
nx g @bespunky/nx-tools:ds-theme acme     # -> themes/acme.theme.scss, built to theme-acme.css
```

Then fill in the overrides. It's authored in **SASS**, which is the whole point: a typo'd token name is a
**build error**, exactly as it is in component SCSS.

```scss
@use '../styles' as ds;
@include ds.theme-overrides(
  $base:  ('radius-md': 10px),
  $light: ('color-primary': #c0392b, 'color-on-primary': #ffffff),
  $dark:  ('color-primary': #ff8a7a, 'color-on-primary': #1c1c20)
);
```

Link it in `index.html` so it applies **before the first paint**:

```html
<link id="{{tokenPrefix}}-theme" rel="stylesheet" href="theme-acme.css">
```

…and swap it at runtime with one line:

```ts
inject(DsRuntimeTheme).use('theme-globex.css');   // whole app re-themes, live
```

**Why a file rather than JavaScript.** A `<link>` in `<head>` is applied before the browser paints, so the
brand never flashes in. Anything JavaScript applies necessarily lands *after* the bundle boots — the user
watches the default theme paint and then snap to the brand, and no service can fix that. You also get
browser caching, revalidation and CDN delivery for nothing, and the design system's compile-time token
guard survives.

**The one exception.** Values that don't exist until runtime — a colour dragged out of a picker, a hex
stored per-tenant in a database — cannot be pre-built into a file. That is `DsRuntimeTheme.setTokens()`.
Use it *only* then: there is no compiler on that path, so an unknown token name silently does nothing.

A theme can only **re-bind** tokens the design system already declares. It cannot introduce new ones —
nothing would be reading them. A theme is a *values* mechanism, not an escape from the token vocabulary.

> **The tokens currently in `_tokens.scss` are PLACEHOLDERS with no design authority.** They exist so the
> library compiles and the app runs on day zero. The design phase — `bespunky-product-ux:stage-the-vision`
> → `realize-the-vision` — replaces that file wholesale with the real visual system. Do not build a look
> on top of them, and do not tweak them into one.
