#!/usr/bin/env bash
# BeSpunky OS floor — the install entrypoint of a LOCAL devcontainer feature.
#
# The devcontainer CLI copies this directory into the image and runs this script during the
# BUILD, once, before anything in the workspace exists. That timing is the whole reason the
# floor moved here from post-create.sh: the packages are a property of the IMAGE, not of the
# checkout, so they belong in the layer that is cached and reused, not in a script that re-runs
# after every rebuild and holds the editor open while apt works.
#
# It runs as ROOT. There is no `sudo` anywhere below — deliberately, not as an omission:
# post-create.sh calls sudo because it runs as the `node` remote user, and copying that habit
# here would depend on a sudo binary and a sudoers rule that a feature has no business assuming
# (a feature must work on a base image that has neither).
#
# Generated by @bespunky/nx-tools:devcontainer. Edit the template in the toolkit, not this copy —
# every `scaffold.sh --sync` regenerates this file and a hand edit here is silently discarded.
set -eu

# apt must never stop to ask a question during a build: there is no terminal to answer on, and a
# package whose postinst opens a dialog would hang the build until the daemon times it out.
export DEBIAN_FRONTEND=noninteractive

# ---------------------------------------------------------------------------------------------
# The package list — ONE variable, grouped BY CAPABILITY.
#
# One variable, because the hand-recovery command printed on failure is DERIVED from it rather
# than retyped. post-create.sh states that rule and earned it: a re-run instruction that has
# drifted from what the step installs is worse than none (`nx serve` used to carry its own
# hand-typed copy of this list and had already drifted).
#
# Accumulated across three assignments rather than declared as an array, so each capability can
# carry its own comment beside its own packages — a reader can tell why any given package is
# here and delete it together with the capability it serves. The accumulation is also POSIX, so
# this file survives being invoked as `sh install.sh` by a CLI or base image that ignores the
# shebang; an array would be a PARSE error there, and sh parses incrementally, so the run would
# die at that line with a bare syntax error before printing any of the warnings below.
# ---------------------------------------------------------------------------------------------

# Shared browser (tools/shared-browser — installed ALWAYS, started ON DEMAND): a headed Chromium
# on a virtual X display, streamed to the human over noVNC on a port ALLOCATED from the 6080-6119
# band (so parallel containers never contend for one host port — the URL is printed by
# `shared-browser up`). xvfb = the display; x11vnc = the VNC server; novnc + websockify = the web
# client and its WS<->TCP bridge; fluxbox = a minimal WM so Chromium gets a window frame; fonts
# (liberation + colour-emoji) so rendered pages and screenshots look right.
OS_FLOOR_PACKAGES="xvfb x11vnc novnc websockify fluxbox fonts-liberation fonts-noto-color-emoji"
# Durable shells. A tmux session outlives the client attached to it, which is the ONLY way an
# interactive shell opened into this container from the outside survives its opener restarting:
# the Docker Engine API has no endpoint to re-attach to an existing exec, so a bare exec's process
# survives but its terminal does not. With tmux that costs a redraw; without it every open shell
# dies. No config file and no /etc/tmux.conf is written on purpose — a caller passes its own
# options explicitly, and a house default set with `set-option -g` would apply SERVER-wide, i.e.
# to whatever the human is running in this container too. Presence on PATH is the whole contract.
OS_FLOOR_PACKAGES="$OS_FLOOR_PACKAGES tmux"
# General utilities the house tooling shells out to. procps supplies `sysctl`, which the
# worktree-domains proxy (tools/worktree-domains) uses to lower this container's
# net.ipv4.ip_unprivileged_port_start so its Node reverse proxy can bind the privileged :80 as the
# non-root `node` user, giving each worktree a pretty http://<slug>.localhost/ domain. iproute2
# supplies `ss` for the port probes; curl for the fetches.
OS_FLOOR_PACKAGES="$OS_FLOOR_PACKAGES iproute2 procps curl"

echo "[os-floor] provisioning the OS floor (shared browser, tmux, utilities)"

# Retry with backoff — 3 attempts, 10s then 20s. Not defensive padding: WSL+Docker DNS is
# intermittently flaky (getaddrinfo failures on an otherwise-working network, where the very next
# attempt succeeds), and apt's own retry gives up far too fast to outlast the blip.
#
# Correct under `set -e` because the command runs as an `if` CONDITION: errexit is suppressed for
# the condition of a compound command, so a failed attempt lands in the loop instead of killing
# the script. Written any other way — a bare command plus `$?` — the first failure would abort
# before the retry it exists for.
floor_apt_ok=0
for attempt in 1 2 3; do
  # $OS_FLOOR_PACKAGES is deliberately UNQUOTED: word-splitting into one argument per package is
  # the point. Safe because every member is a Debian package name — no whitespace, no globs.
  # shellcheck disable=SC2086
  if apt-get update && apt-get install -y $OS_FLOOR_PACKAGES; then
    floor_apt_ok=1; break
  fi
  if [ "$attempt" -lt 3 ]; then
    echo "[os-floor] apt install attempt $attempt/3 failed (often transient WSL/Docker DNS); retrying in $((attempt * 10))s..."
    sleep "$((attempt * 10))"
  fi
done

if [ "$floor_apt_ok" = 1 ]; then
  # No per-package probe here on purpose. `apt-get install -y` exiting 0 IS the check; a line that
  # verified one member of the list and then announced readiness for all of them would be a false
  # assurance — worse than no check, and it singles out a package this feature's whole point is
  # that nothing is special about.
  echo "[os-floor] OS floor ready"
  exit 0
fi

# ---------------------------------------------------------------------------------------------
# THE ONE DESIGN POINT IN THIS FILE: we warn LOUDLY and exit 0 — we never exit non-zero.
#
# A feature's install.sh returning non-zero FAILS THE ENTIRE CONTAINER BUILD. The developer gets
# no container at all: no editor, no shell, no workspace, nothing to fix it from — and the cause
# is usually a DNS blip that would have been gone by the time they read the error. The house
# stance everywhere in post-create.sh is the same one, for the same reason, and it is a real
# tradeoff taken deliberately, not laziness: a half-provisioned container beats no container.
#
# What we give up by exiting 0 is the build-time guarantee — the container comes up believing it
# has a floor it does not have, and the failure resurfaces later and further away (the shared
# browser won't start, worktree-domains can't bind :80). That is why the warning is LOUD, names
# every capability the failure took out, and prints the exact command to finish the job —
# derived from $OS_FLOOR_PACKAGES, never retyped. A silent exit 0 would be the indefensible
# version of this; a loud one hands the developer a working container and a one-line repair.
# ---------------------------------------------------------------------------------------------
echo "[os-floor] ============================================================================"
echo "[os-floor] WARNING: OS floor apt install failed after 3 attempts — likely a transient"
echo "[os-floor]          network/DNS issue. NOT failing the container build: a half-provisioned"
echo "[os-floor]          container you can work in beats no container at all."
echo "[os-floor]"
echo "[os-floor]          EVERYTHING in this one transaction is missing: the shared browser,"
echo "[os-floor]          durable (tmux-backed) terminals, and the worktree-domains :80 proxy +"
echo "[os-floor]          port probes (which need sysctl from procps and ss from iproute2)."
echo "[os-floor]"
echo "[os-floor]          Finish this one step from a shell in the container once the network"
echo "[os-floor]          settles (as root, or prefix with sudo as the 'node' user):"
echo "[os-floor]            apt-get update && apt-get install -y $OS_FLOOR_PACKAGES"
echo "[os-floor] ============================================================================"
exit 0
