// 0.50.0 — refresh a post-create.local.sh that is still an untouched seed from 0.15–0.38.
//
// WHY. 0.48.0 replaced the seeded stub (its example was an apt step, which the image-build rule forbids) only when
// it was byte-for-byte the 0.39–0.47 stub. Two older stubs shipped, differing only in the command line 5 names —
// `scaffold.sh --repair` (0.15.0, 2ace14b) and `scaffold.sh --sync` (0.16.0–0.38.x, 2c58e20) — and the file is
// seeded once and never rewritten, so projects that crossed 0.48.0 still hold them: an untouched house seed teaching
// the forbidden pattern and naming a command that no longer exists, with nothing reported (the apt line is a
// comment). 0.48.0 now knows all three; this rung reaches the projects already past it.
//
// WHAT IT CHANGES: `.devcontainer/post-create.local.sh`, only when it is exactly one of those two stubs → the current
// stub. Anything else is the project's own and is not looked at.
import { type Tree, logger } from '@nx/devkit';
import { LOCAL_STUB } from '../../generators/devcontainer/generator';

const TAG = '[0.50.0 refresh-pre-0.39-local-stub]';
const LOCAL = '.devcontainer/post-create.local.sh';

/** The pre-0.39 seeds, frozen copies (self-contained, like every rung). */
const stub = (command: string) => `#!/usr/bin/env bash
# Project-specific devcontainer setup. THIS FILE IS YOURS.
#
# .devcontainer/post-create.sh is generated by @bespunky/nx-tools and is overwritten on every
# \`${command}\`. This file is created once and never regenerated, so anything you put here
# survives. It runs LAST, after workspace deps, Claude plugins and every house prerequisite — so you can
# assume a working environment.
#
# Runs in a subshell; a non-zero exit warns rather than failing the container build.
set -euo pipefail

# Example — install a project-specific tool:
# sudo apt-get update -qq && sudo apt-get install -y --no-install-recommends postgresql-client
`;
const PRE_0_39_STUBS = ['scaffold.sh --repair', 'scaffold.sh --sync'].map(stub);

export default function refreshPre039LocalStub(tree: Tree): void {
  if (!tree.exists(LOCAL)) return;
  if (!PRE_0_39_STUBS.includes(tree.read(LOCAL, 'utf8') ?? '')) return;
  tree.write(LOCAL, LOCAL_STUB);
  logger.info(
    `${TAG} refreshed ${LOCAL} — it was still the untouched seed from before 0.39, whose apt-get example the image ` +
      `build retired (OS packages go in .devcontainer/os-packages.txt) and whose upgrade command no longer exists.`,
  );
}
