#!/usr/bin/env bash
# tools/setup-gcp.sh — the ONE-TIME cloud setup behind the house deploy workflow (.github/workflows/deploy.yml).
#
# ┌─ A HUMAN RUNS THIS — NOT CLAUDE ─────────────────────────────────────────────────────────────────────────────┐
# │ It grants IAM roles in your Google Cloud project. Claude Code refuses IAM grants to agents BY DESIGN, so an     │
# │ agent must never try to run it (or its gcloud commands) — it hands you this line instead. Review it, then run  │
# │ it yourself, in Claude Code with the `!` prefix (or any terminal):                                               │
# │                                                                                                                  │
# │     ! bash tools/setup-gcp.sh --dry-run                    # every gcloud call it would make, nothing changed   │
# │     ! bash tools/setup-gcp.sh [--environment <name>]       # create / converge                                │
# │     ! bash tools/setup-gcp.sh --rollback [--environment <name>]                                                │
# │                                                                                                                  │
# │ When it finishes it prints the GitHub environment and variables to set — run those (or paste them to Claude). │
# │ Nothing it prints is a secret: keyless auth has no key.                                                         │
# └──────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
#
# Generated by @bespunky/nx-tools (the `ci` layer, Firebase provider) — OWNED: rewritten on every house upgrade from
# the branch model's `ci` bindings. Never hand-edit. When an upgrade changes the environments or branches below it
# prints a HUMAN_STEP: re-run this, because the cloud side cannot be regenerated.
#
# WHAT IT CREATES, per environment (idempotent — every resource is described before it is created, and re-running
# converges the provider's condition and the role set to what this file says):
#   - Workload Identity Federation: a pool `github-actions` and an OIDC provider `gh-<environment>` that trusts a
#     GitHub token ONLY from this repository, ONLY in this GitHub environment, and ONLY for the branches below.
#     No service-account key exists anywhere.
#   - A service account `github-deployer`, which the workflow impersonates through that provider.
#   - The least-privilege roles a `firebase deploy` of what firebase.json declares needs — each justified below.
#
# Flags: --environment <name> (required when the model binds several) · --project <gcp-project-id> (default: the
# environment's .firebaserc alias, resolved) · --repo <owner/repo> (default: the origin remote) · --dry-run · --rollback
set -euo pipefail

# ── the environments, from the branch model (rendered — do not edit) ─────────────────────────────────────────────
# environment <TAB> firebase target (.firebaserc alias or project id) <TAB> its branches <TAB> CEL condition on the token's ref
ENVIRONMENTS="$(cat <<'TABLE'
__ENVIRONMENTS__
TABLE
)"

POOL=github-actions
SA_NAME=github-deployer

die() { printf '\n✗ %s\n' "$*" >&2; exit 1; }
say() { printf '%s\n' "$*"; }

ENVIRONMENT="" PROJECT="" REPO="" DRY=0 ROLLBACK=0
while [ $# -gt 0 ]; do
  case "$1" in
    --environment) ENVIRONMENT="${2:?--environment needs a name}"; shift 2 ;;
    --environment=*) ENVIRONMENT="${1#*=}"; shift ;;
    --project) PROJECT="${2:?--project needs an id}"; shift 2 ;;
    --project=*) PROJECT="${1#*=}"; shift ;;
    --repo) REPO="${2:?--repo needs owner/repo}"; shift 2 ;;
    --repo=*) REPO="${1#*=}"; shift ;;
    --dry-run) DRY=1; shift ;;
    --rollback) ROLLBACK=1; shift ;;
    -h|--help) sed -n '2,32p' "$0"; exit 0 ;;
    *) die "unknown argument: $1 (see --help)" ;;
  esac
done

cd "$(git rev-parse --show-toplevel 2>/dev/null || pwd)"

# ── which environment ───────────────────────────────────────────────────────────────────────────────────────────
NAMES="$(printf '%s\n' "$ENVIRONMENTS" | cut -f1)"
if [ -z "$ENVIRONMENT" ]; then
  [ "$(printf '%s\n' "$NAMES" | wc -l)" -eq 1 ] || die "the branch model binds several environments — choose one: --environment <$(printf '%s' "$NAMES" | paste -sd'|')>"
  ENVIRONMENT="$NAMES"
fi
ROW="$(printf '%s\n' "$ENVIRONMENTS" | awk -F'\t' -v e="$ENVIRONMENT" '$1 == e')"
[ -n "$ROW" ] || die "no environment '$ENVIRONMENT' in the branch model (known: $(printf '%s' "$NAMES" | paste -sd' '))"
TARGET="$(printf '%s' "$ROW" | cut -f2)"
BRANCHES="$(printf '%s' "$ROW" | cut -f3)"
REFS="$(printf '%s' "$ROW" | cut -f4)"

# ── which project, which repository ─────────────────────────────────────────────────────────────────────────────
if [ -z "$PROJECT" ]; then
  PROJECT="$(node -e 'try{const p=JSON.parse(require("fs").readFileSync(".firebaserc","utf8")).projects||{};process.stdout.write(p[process.argv[1]]||"")}catch{}' "$TARGET" 2>/dev/null || true)"
  [ -n "$PROJECT" ] || PROJECT="$TARGET"
fi
if [ -z "$REPO" ]; then
  REPO="$(git remote get-url origin 2>/dev/null | sed -E 's#^(git@|ssh://git@|https://)([^/:]+)[/:]##; s#\.git$##')"
  [ -n "$REPO" ] || die "no origin remote to read owner/repo from — pass --repo <owner/repo>"
fi
case "$REPO" in */*) ;; *) die "--repo must be owner/repo (got '$REPO')" ;; esac
PROVIDER="$(printf 'gh-%s' "$ENVIRONMENT" | tr 'A-Z_.' 'a-z--' | cut -c1-32)"
SA="$SA_NAME@$PROJECT.iam.gserviceaccount.com"

# ── what firebase.json deploys decides the roles ───────────────────────────────────────────────────────────────
USES="$(node -e '
  const fs=require("fs");let f={};try{f=JSON.parse(fs.readFileSync("firebase.json","utf8"))}catch{}
  const out=[];const fns=[].concat(f.functions||[]);
  if(fns.length){out.push("functions");
    const grep=(re)=>fns.some(({source})=>{try{return require("child_process").execFileSync("grep",["-rqsE",re,source||"."],{stdio:"ignore"}),true}catch{return false}});
    if(grep("defineSecret|secrets:"))out.push("secrets");
    if(grep("onSchedule"))out.push("schedule");
    if(grep("firebase-functions/(v2/)?(firestore|storage|pubsub|eventarc|database|alerts|remoteConfig|testLab)"))out.push("events");}
  if(f.firestore&&f.firestore.rules)out.push("firestore-rules");
  if(f.firestore&&f.firestore.indexes)out.push("firestore-indexes");
  if(f.storage)out.push("storage");
  if(f.hosting)out.push("hosting");
  if(f.extensions)out.push("extensions");
  process.stdout.write(out.join(" "));' 2>/dev/null || true)"
uses() { case " $USES " in *" $1 "*) return 0 ;; *) return 1 ;; esac; }

# ROLE <TAB> WHY — every role the deployer holds, and the reason it is the least that works.
ROLES="roles/serviceusage.serviceUsageConsumer	the Firebase CLI calls Google APIs as this project and checks they are enabled
roles/firebase.viewer	the CLI reads the project's Firebase config (it bakes FIREBASE_CONFIG into Functions and resolves the default resources)"
APIS="iam.googleapis.com iamcredentials.googleapis.com sts.googleapis.com cloudresourcemanager.googleapis.com serviceusage.googleapis.com firebase.googleapis.com"
role() { ROLES="$ROLES
$1	$2"; }
if uses functions; then
  role roles/cloudfunctions.developer 'create and update the functions (not delete-protected IAM, not admin)'
  role roles/run.admin 'gen-2 functions ARE Cloud Run services: the CLI sets the invoker policy of public HTTPS functions, which only run.admin may'
  role roles/artifactregistry.reader 'the CLI inspects the gcf-artifacts repository the function images live in'
  APIS="$APIS cloudfunctions.googleapis.com cloudbuild.googleapis.com artifactregistry.googleapis.com run.googleapis.com"
fi
uses secrets && role roles/secretmanager.viewer 'the CLI resolves each defineSecret to its current version (it never reads the value)'
uses schedule && role roles/cloudscheduler.admin 'onSchedule functions deploy a Cloud Scheduler job each'
uses events && role roles/eventarc.developer 'event-triggered gen-2 functions deploy an Eventarc trigger each' && APIS="$APIS eventarc.googleapis.com pubsub.googleapis.com"
uses firestore-rules && role roles/firebaserules.admin 'publish firestore.rules (a rules release)' && APIS="$APIS firebaserules.googleapis.com firestore.googleapis.com"
uses firestore-indexes && role roles/datastore.indexAdmin 'create and update the composite indexes in firestore.indexes.json'
uses storage && role roles/firebaserules.admin 'publish storage.rules (a rules release)' && role roles/firebasestorage.viewer 'the CLI looks up the default bucket the rules attach to' && APIS="$APIS firebaserules.googleapis.com firebasestorage.googleapis.com"
uses hosting && role roles/firebasehosting.admin "publish Firebase Hosting releases (not App Hosting: that is Firebase's own rollout)"
uses extensions && role roles/firebaseextensions.viewer 'the CLI reads the installed extension instances it reconciles'
ROLES="$(printf '%s\n' "$ROLES" | awk -F'\t' '!seen[$1]++')"

# ── running gcloud ────────────────────────────────────────────────────────────────────────────────────────────────
HAVE_GCLOUD=0
if command -v gcloud >/dev/null && gcloud auth list --filter=status:ACTIVE --format='value(account)' 2>/dev/null | grep -q .; then HAVE_GCLOUD=1; fi
[ "$HAVE_GCLOUD" = 1 ] || [ "$DRY" = 1 ] || die "gcloud is not installed or not logged in — run: gcloud auth login  (as an account that may grant IAM in $PROJECT)"
act() {   # a change: printed, and run unless --dry-run
  printf '  + gcloud %s\n' "$*"
  [ "$DRY" = 1 ] || gcloud "$@" --quiet >/dev/null
}
exists() { # for a removal: does it exist? (a dry run without gcloud assumes yes, so it shows every step)
  if [ "$HAVE_GCLOUD" = 1 ]; then gcloud "$@" >/dev/null 2>&1; else [ "$DRY" = 1 ]; fi
}
probe() { # a read: runs whenever gcloud can (also in --dry-run), so a dry run shows only what would change
  [ "$HAVE_GCLOUD" = 1 ] && gcloud "$@" 2>/dev/null
}

NUMBER="$(probe projects describe "$PROJECT" --format='value(projectNumber)' || true)"
[ -n "$NUMBER" ] || { [ "$DRY" = 1 ] && NUMBER='<PROJECT_NUMBER>'; } || die "cannot read project $PROJECT — does it exist, and may this account see it?"
POOL_ID="projects/$NUMBER/locations/global/workloadIdentityPools/$POOL"
PRINCIPAL="principalSet://iam.googleapis.com/$POOL_ID/attribute.repository/$REPO"
CONDITION="assertion.repository == '$REPO' && assertion.environment == '$ENVIRONMENT' && ($REFS)"
RUNTIME_SAS="$NUMBER-compute@developer.gserviceaccount.com $PROJECT@appspot.gserviceaccount.com"

say "Environment $ENVIRONMENT → GCP project $PROJECT ($REPO; deploys from: $BRANCHES)"
say "firebase.json deploys: ${USES:-nothing the CLI needs roles for}"
[ "$DRY" = 1 ] && say "(dry run — nothing is changed)"

if [ "$ROLLBACK" = 1 ]; then
  say "Rolling back:"
  while IFS="$(printf '\t')" read -r r _; do act projects remove-iam-policy-binding "$PROJECT" --member="serviceAccount:$SA" --role="$r" --condition=None || true; done <<<"$ROLES"
  for runtime in $RUNTIME_SAS; do exists iam service-accounts describe "$runtime" --project="$PROJECT" && act iam service-accounts remove-iam-policy-binding "$runtime" --project="$PROJECT" --member="serviceAccount:$SA" --role=roles/iam.serviceAccountUser || true; done
  if uses functions && uses secrets; then act projects remove-iam-policy-binding "$PROJECT" --member="serviceAccount:$NUMBER-compute@developer.gserviceaccount.com" --role=roles/secretmanager.secretAccessor --condition=None || true; fi
  exists iam service-accounts describe "$SA" --project="$PROJECT" && act iam service-accounts delete "$SA" --project="$PROJECT" || true
  exists iam workload-identity-pools providers describe "$PROVIDER" --project="$PROJECT" --location=global --workload-identity-pool="$POOL" \
    && act iam workload-identity-pools providers delete "$PROVIDER" --project="$PROJECT" --location=global --workload-identity-pool="$POOL" || true
  say "Left in place: the pool '$POOL' (other environments may share it; delete it with gcloud iam workload-identity-pools delete $POOL --location=global --project=$PROJECT) and the enabled APIs."
  say "On GitHub, remove the variables GCP_WORKLOAD_IDENTITY_PROVIDER and GCP_DEPLOY_SERVICE_ACCOUNT from the '$ENVIRONMENT' environment."
  exit 0
fi

say "APIs:"
act services enable $(printf '%s\n' $APIS | awk '!seen[$0]++') --project="$PROJECT"

say "Workload Identity Federation:"
state="$(probe iam workload-identity-pools describe "$POOL" --project="$PROJECT" --location=global --format='value(state)' || true)"
case "$state" in
  ACTIVE) say "  = pool $POOL exists" ;;
  DELETED) act iam workload-identity-pools undelete "$POOL" --project="$PROJECT" --location=global ;;
  *) act iam workload-identity-pools create "$POOL" --project="$PROJECT" --location=global --display-name="GitHub Actions" ;;
esac
MAPPING='google.subject=assertion.sub,attribute.repository=assertion.repository,attribute.ref=assertion.ref,attribute.environment=assertion.environment'
state="$(probe iam workload-identity-pools providers describe "$PROVIDER" --project="$PROJECT" --location=global --workload-identity-pool="$POOL" --format='value(state)' || true)"
case "$state" in
  DELETED) act iam workload-identity-pools providers undelete "$PROVIDER" --project="$PROJECT" --location=global --workload-identity-pool="$POOL"; state=ACTIVE ;;
esac
if [ "$state" = ACTIVE ]; then
  # Converge: the condition follows the branch model every time this runs.
  act iam workload-identity-pools providers update-oidc "$PROVIDER" --project="$PROJECT" --location=global --workload-identity-pool="$POOL" \
    --attribute-mapping="$MAPPING" --attribute-condition="$CONDITION"
else
  act iam workload-identity-pools providers create-oidc "$PROVIDER" --project="$PROJECT" --location=global --workload-identity-pool="$POOL" \
    --display-name="GitHub $ENVIRONMENT" --issuer-uri=https://token.actions.githubusercontent.com \
    --attribute-mapping="$MAPPING" --attribute-condition="$CONDITION"
fi

say "Service account:"
if probe iam service-accounts describe "$SA" --project="$PROJECT" >/dev/null; then say "  = $SA exists"; else
  act iam service-accounts create "$SA_NAME" --project="$PROJECT" --display-name="GitHub Actions deployer"
fi
# Only GitHub tokens of THIS repository (and, through the provider's condition, this environment and these branches)
# may impersonate it.
act iam service-accounts add-iam-policy-binding "$SA" --project="$PROJECT" --role=roles/iam.workloadIdentityUser --member="$PRINCIPAL"

say "Roles (least privilege for what firebase.json deploys):"
while IFS="$(printf '\t')" read -r r why; do
  say "  # $r — $why"
  act projects add-iam-policy-binding "$PROJECT" --member="serviceAccount:$SA" --role="$r" --condition=None
done <<<"$ROLES"
if uses functions; then
  # Deploying a function means running it AS its runtime service account: actAs on THAT account, not project-wide.
  for runtime in $RUNTIME_SAS; do
    if [ "$DRY" = 1 ] || probe iam service-accounts describe "$runtime" --project="$PROJECT" >/dev/null; then
      say "  # roles/iam.serviceAccountUser on $runtime — deploy functions that run as it"
      act iam service-accounts add-iam-policy-binding "$runtime" --project="$PROJECT" --member="serviceAccount:$SA" --role=roles/iam.serviceAccountUser
    fi
  done
  if uses secrets; then
    # The functions read their secrets at run time. Granted once to the RUNTIME account, so a deploy that introduces
    # a new secret never has to change IAM (which would need secretmanager.admin on the deployer).
    say "  # roles/secretmanager.secretAccessor for the functions' runtime account — read their secrets at run time"
    act projects add-iam-policy-binding "$PROJECT" --member="serviceAccount:$NUMBER-compute@developer.gserviceaccount.com" --role=roles/secretmanager.secretAccessor --condition=None
  fi
fi

say ""
say "Done. Now on GitHub (run these, or paste this block back to Claude — none of it is secret):"
say "  gh api --method PUT repos/$REPO/environments/$ENVIRONMENT >/dev/null"
say "  gh variable set GCP_WORKLOAD_IDENTITY_PROVIDER --env $ENVIRONMENT --repo $REPO --body '$POOL_ID/providers/$PROVIDER'"
say "  gh variable set GCP_DEPLOY_SERVICE_ACCOUNT --env $ENVIRONMENT --repo $REPO --body '$SA'"
say "Optionally restrict the environment to its branches (Settings → Environments → $ENVIRONMENT → Deployment branches): $BRANCHES"
say "The first deploy: Actions → Deploy → Run workflow on the branch, scope = all."
