#!/usr/bin/env bash
# tools/setup-gcp.sh — the ONE-TIME cloud setup behind the house deploy workflow (__WORKFLOW__).
#
# ┌─ A HUMAN RUNS THIS — NOT CLAUDE ─────────────────────────────────────────────────────────────────────────────┐
# │ It grants IAM roles in your Google Cloud project. Claude Code refuses IAM grants to agents BY DESIGN, so an     │
# │ agent must never try to run it (or its gcloud commands) — it hands you this line instead. Review it, then run  │
# │ it yourself, in Claude Code with the `!` prefix (or any terminal with node, git, gcloud and ideally gh):        │
# │                                                                                                                  │
# │     ! bash tools/setup-gcp.sh --dry-run [--environment <name>]   # every change it would make, nothing changed │
# │     ! bash tools/setup-gcp.sh [--environment <name>]             # create / converge                          │
# │     ! bash tools/setup-gcp.sh --rollback --environment <name>    # undo exactly what it recorded               │
# │                                                                                                                  │
# │ It ends by printing the GitHub commands to run (environment protection + two variables). Nothing it prints is  │
# │ a secret: keyless auth has no key. COMMIT the record it writes (__RECORD_DIR__/<environment>.tsv).            │
# └──────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
#
# Generated by @bespunky/nx-tools (the `ci` layer, Firebase provider) — OWNED: rewritten on every house upgrade from
# the branch model's `ci` bindings. Never hand-edit. When an upgrade changes the environments or branches below it
# prints a HUMAN_STEP: re-run this, because the cloud side cannot be regenerated.
#
# WHAT IT CREATES, per environment — everything owned by the house, nothing shared:
#   - a Workload Identity POOL of its own (`gh-<environment>-<n>`, unique to this repository and environment) with ONE
#     OIDC provider, `github`, that accepts a GitHub token only when ALL of these hold: this repository (by its
#     immutable id), this GitHub environment, a `push` or `workflow_dispatch` event, THIS workflow file at the ref
#     being deployed, and one of the branches below. The pool is the house's alone, so no other provider can ever
#     reach the service account through it.
#   - a SERVICE ACCOUNT of its own (`deploy-<environment>-<n>`), impersonable only through that pool by this
#     repository. No service-account key exists anywhere.
#   - the least-privilege roles a `firebase deploy` of what firebase.json declares needs — each justified below — and
#     the grants the deployed functions need at RUN time (their secrets, event delivery), so a deploy never has to
#     change IAM.
#
# THE RECORD. Every resource it creates and every grant it ADDS (one that was not there before) is recorded in
# __RECORD_DIR__/<environment>.tsv as it happens. Re-running converges: what is recorded but no longer needed (a
# feature dropped from firebase.json) is removed. --rollback removes only what the record lists — never a grant
# that was there before, never anything another environment uses — and the deployed functions' runtime grants are
# LEFT IN PLACE (rolling back CI must not break production), with the command to remove each printed. Commit the record:
# whoever rolls back next, on whatever machine, needs it.
#
# Flags: --environment <name> (required when the model binds several) · --project <gcp-project-id> (default: the
# environment's .firebaserc alias, resolved) · --repo <owner/repo> (default: the origin remote) · --repo-id <id>
# (default: `gh api repos/<owner/repo>`) · --dry-run · --rollback
set -Eeuo pipefail

# ── the environments, from the branch model (rendered — do not edit) ─────────────────────────────────────────────
# environment <TAB> firebase target (.firebaserc alias or project id) <TAB> its branches <TAB> CEL test on the token's
# ref <TAB> active | retired (no binding names it any more: --rollback only)
ENVIRONMENTS="$(cat <<'TABLE'
__ENVIRONMENTS__
TABLE
)"
WORKFLOW='__WORKFLOW__'
RECORD_DIR='__RECORD_DIR__'
VAR_PROVIDER='__VAR_PROVIDER__'
VAR_SERVICE_ACCOUNT='__VAR_SERVICE_ACCOUNT__'
TAB="$(printf '\t')"

die() { printf '\n✗ %s\n' "$*" >&2; exit 1; }
say() { printf '%s\n' "$*"; }

ENVIRONMENT="" PROJECT="" REPO="" REPO_ID="" DRY=0 ROLLBACK=0
while [ $# -gt 0 ]; do
  case "$1" in
    --environment) ENVIRONMENT="${2:?--environment needs a name}"; shift 2 ;;
    --environment=*) ENVIRONMENT="${1#*=}"; shift ;;
    --project) PROJECT="${2:?--project needs an id}"; shift 2 ;;
    --project=*) PROJECT="${1#*=}"; shift ;;
    --repo) REPO="${2:?--repo needs owner/repo}"; shift 2 ;;
    --repo=*) REPO="${1#*=}"; shift ;;
    --repo-id) REPO_ID="${2:?--repo-id needs the numeric id}"; shift 2 ;;
    --repo-id=*) REPO_ID="${1#*=}"; shift ;;
    --dry-run) DRY=1; shift ;;
    --rollback) ROLLBACK=1; shift ;;
    -h|--help) sed -n '2,48p' "$0"; exit 0 ;;
    *) die "unknown argument: $1 (see --help)" ;;
  esac
done

# node reads firebase.json, .firebaserc and the functions' sources — without it the role set would silently be
# empty, so it is required, never optional.
command -v node >/dev/null || die "node is required (it reads firebase.json and .firebaserc to decide the roles) — run this where the project's Node is installed, e.g. in its devcontainer"
cd "$(git rev-parse --show-toplevel 2>/dev/null || pwd)"

# ── which environment ───────────────────────────────────────────────────────────────────────────────────────────
ACTIVE="$(printf '%s\n' "$ENVIRONMENTS" | awk -F'\t' '$5 == "active" { print $1 }')"
if [ -z "$ENVIRONMENT" ]; then
  [ "$(printf '%s\n' "$ACTIVE" | grep -c .)" -eq 1 ] || die "choose an environment: --environment <$(printf '%s\n' "$ENVIRONMENTS" | cut -f1 | paste -sd'|' -)>"
  ENVIRONMENT="$ACTIVE"
fi
ROW="$(printf '%s\n' "$ENVIRONMENTS" | awk -F'\t' -v e="$ENVIRONMENT" '$1 == e')"
[ -n "$ROW" ] || die "no environment '$ENVIRONMENT' in the branch model (known: $(printf '%s\n' "$ENVIRONMENTS" | cut -f1 | paste -sd' ' -))"
TARGET="$(printf '%s' "$ROW" | cut -f2)"
BRANCHES="$(printf '%s' "$ROW" | cut -f3)"
REFS="$(printf '%s' "$ROW" | cut -f4)"
STATUS="$(printf '%s' "$ROW" | cut -f5)"
[ "$STATUS" = active ] || [ "$ROLLBACK" = 1 ] || die "no line deploys into '$ENVIRONMENT' any more — it can only be rolled back: bash tools/setup-gcp.sh --rollback --environment $ENVIRONMENT"

# ── the record: what this script created and added for this environment ─────────────────────────────────────────
#   project <id> · repo-id <id> · pool <id> · provider <pool> <id> · service-account <email>
#   grant <deploy|runtime> <project|sa:<email>|secret:<name>> <role> <member>
RECORD="$RECORD_DIR/$ENVIRONMENT.tsv"
recorded() { [ -f "$RECORD" ] && awk -F'\t' -v k="$1" '$1 == k' "$RECORD"; return 0; }
record() { # append a line (never in a dry run)
  [ "$DRY" = 1 ] && return 0
  if [ ! -f "$RECORD" ]; then
    mkdir -p "$RECORD_DIR"
    printf '# What tools/setup-gcp.sh created and added for the %s environment — rollback undoes exactly this.\n# Written by the script as it goes; COMMIT it. Never hand-edit.\n' "$ENVIRONMENT" > "$RECORD"
    # Born with what everything in it is relative to: where, and for which repository.
    printf 'project\t%s\nrepo-id\t%s\n' "$PROJECT" "$REPO_ID" >> "$RECORD"
  fi
  (IFS="$TAB"; printf '%s\n' "$*") >> "$RECORD"
}
unrecord() { # drop one exact line
  [ "$DRY" = 1 ] && return 0
  local line; line="$(IFS="$TAB"; printf '%s' "$*")"
  awk -v l="$line" '$0 != l' "$RECORD" > "$RECORD.tmp" && mv "$RECORD.tmp" "$RECORD"
}
R_PROJECT="$(recorded project | cut -f2)"
R_REPO_ID="$(recorded repo-id | cut -f2)"

# ── which project ───────────────────────────────────────────────────────────────────────────────────────────────
if [ -n "$R_PROJECT" ]; then
  [ -z "$PROJECT" ] || [ "$PROJECT" = "$R_PROJECT" ] || die "'$ENVIRONMENT' was set up in project $R_PROJECT (its record says so) — roll it back there first: bash tools/setup-gcp.sh --rollback --environment $ENVIRONMENT"
fi
PROJECT="${PROJECT:-$R_PROJECT}"
if [ -z "$PROJECT" ]; then
  RESOLVED="$(node -e '
    const fs = require("fs"); const target = process.argv[1];
    if (!fs.existsSync(".firebaserc")) { process.stdout.write("id\t" + target); process.exit(0); }
    const projects = (JSON.parse(fs.readFileSync(".firebaserc", "utf8")).projects) || {};
    if (projects[target]) process.stdout.write("alias\t" + projects[target]);
    else if (Object.values(projects).includes(target)) process.stdout.write("id\t" + target);
    else process.stdout.write("none\t");' "$TARGET")" || die ".firebaserc could not be read as JSON"
  case "$RESOLVED" in
    alias"$TAB"*) PROJECT="${RESOLVED#*"$TAB"}" ;;
    id"$TAB"*) PROJECT="${RESOLVED#*"$TAB"}" ;;
    *) die "the binding's Firebase target '$TARGET' is neither an alias nor a project id in .firebaserc — add it (npx firebase use --add) or pass --project <gcp-project-id>" ;;
  esac
fi
if [ -n "$R_PROJECT" ] && [ "$PROJECT" != "$R_PROJECT" ]; then
  die "'$ENVIRONMENT' was set up in project $R_PROJECT, and its target now resolves to $PROJECT — roll it back first (bash tools/setup-gcp.sh --rollback --environment $ENVIRONMENT), then set it up again"
fi

# ── which repository: its name (for the commands printed) and its immutable id (for the trust condition) ──────
if [ -z "$REPO" ]; then
  REPO="$(git remote get-url origin 2>/dev/null | sed -E 's#^(git@|ssh://git@|https://)([^/:]+)[/:]##; s#\.git$##')"
  [ -n "$REPO" ] || die "no origin remote to read owner/repo from — pass --repo <owner/repo>"
fi
case "$REPO" in */*) ;; *) die "--repo must be owner/repo (got '$REPO')" ;; esac
if [ -z "$REPO_ID" ]; then REPO_ID="$R_REPO_ID"; fi
if [ -z "$REPO_ID" ] && command -v gh >/dev/null; then REPO_ID="$(gh api "repos/$REPO" --jq .id 2>/dev/null || true)"; fi
if [ -z "$REPO_ID" ]; then
  if [ "$DRY" = 1 ]; then REPO_ID='<REPO_ID>'; else die "cannot read $REPO's numeric id (the trust condition pins it — a name can be re-registered) — log gh in (gh auth login) or pass --repo-id \$(gh api repos/$REPO --jq .id)"; fi
fi
[ -z "$R_REPO_ID" ] || [ "$REPO_ID" = "$R_REPO_ID" ] || die "the record says '$ENVIRONMENT' trusts repository id $R_REPO_ID, not $REPO_ID — roll it back first"

# ── the house's names: unique to this repository + environment, so two repos (or two environments) never share ──
SLUG="$(printf '%s' "$ENVIRONMENT" | tr 'A-Z_.' 'a-z--')"
SUFFIX="000000$(printf '%s/%s' "$REPO_ID" "$ENVIRONMENT" | cksum | cut -d' ' -f1)"; SUFFIX="${SUFFIX: -6}"
POOL="$(recorded pool | cut -f2)"; POOL="${POOL:-gh-${SLUG:0:18}-$SUFFIX}"
PROVIDER=github
SA="$(recorded service-account | cut -f2)"; SA="${SA:-deploy-${SLUG:0:15}-$SUFFIX@$PROJECT.iam.gserviceaccount.com}"
SA_ID="${SA%%@*}"

# ── what firebase.json deploys decides the roles ───────────────────────────────────────────────────────────────
# USES <TAB> SECRETS: the features, then the secret names the functions declare (defineSecret("X") / secrets: [..]).
# shellcheck disable=SC2016 # a node program: its $ and backticks are JavaScript's
SCAN="$(node -e '
  const fs = require("fs"), path = require("path");
  const f = fs.existsSync("firebase.json") ? JSON.parse(fs.readFileSync("firebase.json", "utf8")) : {};
  const out = [], secrets = new Set(), fns = [].concat(f.functions || []);
  const files = (dir) => { const all = []; const walk = (d) => { for (const e of fs.readdirSync(d, { withFileTypes: true })) {
    if (e.name === "node_modules" || e.name.startsWith(".")) continue; const p = path.join(d, e.name);
    if (e.isDirectory()) walk(p); else if (/\.(c|m)?[jt]sx?$/.test(e.name)) all.push(fs.readFileSync(p, "utf8")); } };
    if (fs.existsSync(dir)) walk(dir); return all; };
  if (fns.length) {
    out.push("functions");
    const src = fns.flatMap(({ source }) => files(source || "functions")).join("\n");
    for (const m of src.matchAll(/defineSecret\(\s*["\x27`]([A-Za-z0-9_-]+)["\x27`]/g)) secrets.add(m[1]);
    for (const m of src.matchAll(/secrets\s*:\s*\[([^\]]*)\]/g)) for (const s of m[1].matchAll(/["\x27`]([A-Za-z0-9_-]+)["\x27`]/g)) secrets.add(s[1]);
    if (secrets.size) out.push("secrets");
    if (/onSchedule/.test(src)) out.push("schedule");
    if (/firebase-functions\/(v2\/)?(firestore|storage|pubsub|eventarc|database|alerts|remoteConfig|testLab)/.test(src)) out.push("events");
    if (/firebase-functions\/(v2\/)?storage/.test(src)) out.push("storage-events");
  }
  if (f.firestore && f.firestore.rules) out.push("firestore-rules");
  if (f.firestore && f.firestore.indexes) out.push("firestore-indexes");
  if (f.storage) out.push("storage");
  if (f.hosting) out.push("hosting");
  if (f.extensions) out.push("extensions");
  process.stdout.write(out.join(" ") + "\t" + [...secrets].join(" "));')" || die "could not read firebase.json or the functions' sources (above) — fix that first; the roles depend on them"
USES="${SCAN%%"$TAB"*}"
SECRETS="${SCAN#*"$TAB"}"
uses() { case " $USES " in *" $1 "*) return 0 ;; *) return 1 ;; esac; }

# ── running gcloud ────────────────────────────────────────────────────────────────────────────────────────────────
HAVE_GCLOUD=0
if command -v gcloud >/dev/null && gcloud auth list --filter=status:ACTIVE --format='value(account)' 2>/dev/null | grep -q .; then HAVE_GCLOUD=1; fi
[ "$HAVE_GCLOUD" = 1 ] || [ "$DRY" = 1 ] || die "gcloud is not installed or not logged in — run: gcloud auth login  (as an account that may grant IAM in $PROJECT)"
act() {   # a change: printed, and run unless --dry-run
  printf '  + gcloud'; printf ' %q' "$@"; printf '\n'
  [ "$DRY" = 1 ] || gcloud "$@" --quiet >/dev/null
}
probe() { # a read: runs whenever gcloud can (also in --dry-run), so a dry run shows only what would change
  [ "$HAVE_GCLOUD" = 1 ] && gcloud "$@" 2>/dev/null
}
trap 'printf "\n✗ stopped at a failing step (above). What was done so far is recorded in %s — fix the cause and re-run: it converges.\n" "$RECORD" >&2' ERR

NUMBER="$(probe projects describe "$PROJECT" --format='value(projectNumber)' || true)"
[ -n "$NUMBER" ] || { [ "$DRY" = 1 ] && NUMBER='<PROJECT_NUMBER>'; } || die "cannot read project $PROJECT — does it exist, and may this account see it?"
COMPUTE="$NUMBER-compute@developer.gserviceaccount.com"
APPSPOT="$PROJECT@appspot.gserviceaccount.com"
POOL_ID="projects/$NUMBER/locations/global/workloadIdentityPools/$POOL"
PRINCIPAL="principalSet://iam.googleapis.com/$POOL_ID/attribute.repository_id/$REPO_ID"
MAPPING='google.subject=assertion.sub,attribute.repository_id=assertion.repository_id,attribute.environment=assertion.environment,attribute.ref=assertion.ref'
CONDITION="assertion.repository_id == '$REPO_ID' && assertion.environment == '$ENVIRONMENT' && assertion.event_name in ['push', 'workflow_dispatch'] && assertion.workflow_ref == '$REPO/$WORKFLOW@' + assertion.ref && ($REFS)"

# One IAM grant: (deploy | runtime) (project | sa:<email> | secret:<name>) <role> <member>.
policy_members() { # the members holding <role> on a resource, one per line
  local kind="${1%%:*}" name="${1#*:}" role="$2"
  case "$kind" in
    project) probe projects get-iam-policy "$PROJECT" --flatten='bindings[].members' --filter="bindings.role=$role" --format='value(bindings.members)' ;;
    sa) probe iam service-accounts get-iam-policy "$name" --project="$PROJECT" --flatten='bindings[].members' --filter="bindings.role=$role" --format='value(bindings.members)' ;;
    secret) probe secrets get-iam-policy "$name" --project="$PROJECT" --flatten='bindings[].members' --filter="bindings.role=$role" --format='value(bindings.members)' ;;
  esac
}
change_binding() { # add | remove
  local verb="$1" resource="$2" role="$3" member="$4" kind="${2%%:*}" name="${2#*:}"
  case "$kind" in
    project) act projects "$verb-iam-policy-binding" "$PROJECT" --member="$member" --role="$role" --condition=None ;;
    sa) act iam service-accounts "$verb-iam-policy-binding" "$name" --project="$PROJECT" --member="$member" --role="$role" ;;
    secret) act secrets "$verb-iam-policy-binding" "$name" --project="$PROJECT" --member="$member" --role="$role" ;;
  esac
}
WANTED=""
grant() { # class resource role member why
  local class="$1" resource="$2" role="$3" member="$4" why="$5"
  WANTED="$WANTED$class$TAB$resource$TAB$role$TAB$member
"
  local on="$resource"; [ "$resource" = project ] && on="project $PROJECT"
  say "  # $role on $on → $member — $why"
  if policy_members "$resource" "$role" | grep -qxF "$member"; then
    if recorded grant | grep -qxF "grant$TAB$class$TAB$resource$TAB$role$TAB$member"; then say "    = granted (recorded)"; else say "    = already granted, not by this script — left alone, never rolled back"; fi
    return 0
  fi
  change_binding add "$resource" "$role" "$member"
  recorded grant | grep -qxF "grant$TAB$class$TAB$resource$TAB$role$TAB$member" || record grant "$class" "$resource" "$role" "$member"
}

say "Environment $ENVIRONMENT → GCP project $PROJECT ($REPO, id $REPO_ID; deploys from: $BRANCHES)"
say "firebase.json deploys: ${USES:-nothing the CLI needs roles for}${SECRETS:+ (secrets: $SECRETS)}"
[ "$DRY" = 1 ] && say "(dry run — nothing is changed)"

# ═══ ROLLBACK: exactly what the record lists ════════════════════════════════════════════════════════════════════
if [ "$ROLLBACK" = 1 ]; then
  [ -f "$RECORD" ] || die "no record of a setup for '$ENVIRONMENT' ($RECORD) — this script created nothing it knows of, so it removes nothing. (A record that was never committed: restore it from the machine that ran setup.)"
  say "Rolling back what $RECORD lists:"
  KEPT=""
  while IFS="$TAB" read -r _ class resource role member; do
    if [ "$class" = runtime ]; then
      # Rolling back CI must not break what is deployed: the functions still need these at run time.
      KEPT="$KEPT$resource$TAB$role$TAB$member
"
    elif policy_members "$resource" "$role" | grep -qxF "$member" || { [ "$DRY" = 1 ] && [ "$HAVE_GCLOUD" = 0 ]; }; then
      change_binding remove "$resource" "$role" "$member"
    else
      say "  = $role on $resource → $member is already gone"
    fi
  done < <(recorded grant | awk '{ l[NR] = $0 } END { for (i = NR; i > 0; i--) print l[i] }')
  if [ -n "$(recorded service-account)" ]; then
    if probe iam service-accounts describe "$SA" --project="$PROJECT" >/dev/null || { [ "$DRY" = 1 ] && [ "$HAVE_GCLOUD" = 0 ]; }; then act iam service-accounts delete "$SA" --project="$PROJECT"; else say "  = $SA is already gone"; fi
  fi
  if [ -n "$(recorded pool)" ]; then
    # Deleting the house's pool takes its one provider with it.
    if [ "$(probe iam workload-identity-pools describe "$POOL" --project="$PROJECT" --location=global --format='value(state)' || true)" = ACTIVE ] || { [ "$DRY" = 1 ] && [ "$HAVE_GCLOUD" = 0 ]; }; then
      act iam workload-identity-pools delete "$POOL" --project="$PROJECT" --location=global
    else say "  = pool $POOL is already gone"; fi
  fi
  [ "$DRY" = 1 ] || rm -f "$RECORD"
  if [ -n "$KEPT" ]; then
    say ""
    say "LEFT IN PLACE — grants setup added for the deployed functions' RUN time (removing them would break what is"
    say "deployed in $PROJECT). They are no longer recorded; once nothing deployed uses them, remove each by hand:"
    while IFS="$TAB" read -r resource role member; do
      [ -n "$resource" ] || continue
      case "$resource" in
        project) say "  gcloud projects remove-iam-policy-binding $PROJECT --member='$member' --role=$role --condition=None" ;;
        sa:*) say "  gcloud iam service-accounts remove-iam-policy-binding ${resource#sa:} --project=$PROJECT --member='$member' --role=$role" ;;
        secret:*) say "  gcloud secrets remove-iam-policy-binding ${resource#secret:} --project=$PROJECT --member='$member' --role=$role" ;;
      esac
    done <<<"$KEPT"
  fi
  say ""
  say "Also left in place: the enabled APIs (other things may use them)."
  say "On GitHub (run these, or paste them to Claude):"
  say "  gh variable delete $VAR_PROVIDER --env $ENVIRONMENT --repo $REPO"
  say "  gh variable delete $VAR_SERVICE_ACCOUNT --env $ENVIRONMENT --repo $REPO"
  if [ "$STATUS" = retired ]; then say "Then commit the record's removal ($RECORD) — the next upgrade drops '$ENVIRONMENT' from this script."
  else say "Then commit the record's removal ($RECORD)."; fi
  exit 0
fi

# ═══ SETUP / CONVERGE ═══════════════════════════════════════════════════════════════════════════════════════════
record_once() { [ -n "$(recorded "$1")" ] || record "$@"; }

APIS=(iam.googleapis.com iamcredentials.googleapis.com sts.googleapis.com cloudresourcemanager.googleapis.com serviceusage.googleapis.com firebase.googleapis.com)
if uses functions; then APIS+=(cloudfunctions.googleapis.com cloudbuild.googleapis.com artifactregistry.googleapis.com run.googleapis.com); fi
if uses secrets; then APIS+=(secretmanager.googleapis.com); fi
if uses schedule; then APIS+=(cloudscheduler.googleapis.com); fi
if uses events; then APIS+=(eventarc.googleapis.com pubsub.googleapis.com); fi
if uses firestore-rules || uses storage; then APIS+=(firebaserules.googleapis.com); fi
if uses firestore-rules; then APIS+=(firestore.googleapis.com); fi
if uses storage; then APIS+=(firebasestorage.googleapis.com); fi
say "APIs:"
act services enable "${APIS[@]}" --project="$PROJECT"

say "Workload Identity Federation (the house's own pool — nothing else in it):"
state="$(probe iam workload-identity-pools describe "$POOL" --project="$PROJECT" --location=global --format='value(state)' || true)"
# A soft-deleted pool of this name is this repository's own (the name is derived from its id), rolled back: it is
# restored, and the provider check below still refuses anything in it the house did not create.
if [ -z "$(recorded pool)" ] && [ "$state" = ACTIVE ]; then
  die "a pool '$POOL' already exists in $PROJECT, and $RECORD does not list it — the house trusts only a pool it created. If it is this repository's from a setup whose record was lost, restore the record from git; otherwise delete or rename that pool"
fi
case "$state" in
  ACTIVE) say "  = pool $POOL" ;;
  DELETED) act iam workload-identity-pools undelete "$POOL" --project="$PROJECT" --location=global ;;
  *) act iam workload-identity-pools create "$POOL" --project="$PROJECT" --location=global --display-name="GitHub $ENVIRONMENT (house)" --description="Created by tools/setup-gcp.sh for $REPO ($ENVIRONMENT). Managed by its record; do not add providers." ;;
esac
record_once pool "$POOL"
OTHERS="$(probe iam workload-identity-pools providers list --project="$PROJECT" --location=global --workload-identity-pool="$POOL" --format='value(name.basename())' | grep -vx "$PROVIDER" || true)"
[ -z "$OTHERS" ] || die "the house pool $POOL holds providers it did not create ($(printf '%s' "$OTHERS" | paste -sd' ' -)) — any of them could reach the deployer. Delete them, then re-run"
state="$(probe iam workload-identity-pools providers describe "$PROVIDER" --project="$PROJECT" --location=global --workload-identity-pool="$POOL" --format='value(state)' || true)"
case "$state" in
  DELETED) act iam workload-identity-pools providers undelete "$PROVIDER" --project="$PROJECT" --location=global --workload-identity-pool="$POOL"; state=ACTIVE ;;
esac
if [ "$state" = ACTIVE ]; then
  # Converge: the trust condition follows the branch model every time this runs.
  act iam workload-identity-pools providers update-oidc "$PROVIDER" --project="$PROJECT" --location=global --workload-identity-pool="$POOL" \
    --attribute-mapping="$MAPPING" --attribute-condition="$CONDITION"
else
  act iam workload-identity-pools providers create-oidc "$PROVIDER" --project="$PROJECT" --location=global --workload-identity-pool="$POOL" \
    --display-name="GitHub Actions" --issuer-uri=https://token.actions.githubusercontent.com \
    --attribute-mapping="$MAPPING" --attribute-condition="$CONDITION"
fi
record_once provider "$POOL" "$PROVIDER"
say "  trusts: $CONDITION"

say "Service account (the house's own, for $ENVIRONMENT only):"
if probe iam service-accounts describe "$SA" --project="$PROJECT" >/dev/null; then
  [ -n "$(recorded service-account)" ] || die "a service account $SA already exists, and $RECORD does not list it — the house deploys only as an account it created. Restore the record from git, or delete that account"
  say "  = $SA"
else
  act iam service-accounts create "$SA_ID" --project="$PROJECT" --display-name="GitHub deploy: $ENVIRONMENT" --description="Created by tools/setup-gcp.sh for $REPO ($ENVIRONMENT)."
fi
record_once service-account "$SA"

say "Grants:"
DEPLOYER="serviceAccount:$SA"
# Only GitHub tokens of THIS repository, through the house pool (and so through its provider's condition), may
# impersonate the deployer.
grant deploy "sa:$SA" roles/iam.workloadIdentityUser "$PRINCIPAL" 'the deploy job impersonates the deployer through the house pool'
grant deploy project roles/serviceusage.serviceUsageConsumer "$DEPLOYER" 'the Firebase CLI calls Google APIs as this project and checks they are enabled'
grant deploy project roles/firebase.viewer "$DEPLOYER" 'the CLI reads the project'\''s Firebase config (it bakes FIREBASE_CONFIG into Functions and resolves the default resources)'
if uses functions; then
  grant deploy project roles/cloudfunctions.admin "$DEPLOYER" 'create and update functions; a NEW HTTPS function needs cloudfunctions.functions.setIamPolicy (the CLI'\''s checkHttpIam), which only the admin role carries'
  grant deploy project roles/run.admin "$DEPLOYER" 'gen-2 functions ARE Cloud Run services: the CLI sets their invoker policy (run.services.setIamPolicy)'
  grant deploy project roles/artifactregistry.reader "$DEPLOYER" 'the CLI inspects the gcf-artifacts repository the function images live in'
  # Deploying a function means running it AS its runtime service account: actAs on THAT account, not project-wide.
  # Both, deliberately: compute is what 2nd-gen functions run as, and the Firebase CLI's pre-deploy check
  # (checkServiceAccountIam) demands actAs on the App Engine default account EVEN WHEN the functions run as compute —
  # confirmed by a house project's first CI deploy, which failed without it. A project with no App Engine account
  # needs no grant: the CLI's check passes when the account does not exist.
  grant deploy "sa:$COMPUTE" roles/iam.serviceAccountUser "$DEPLOYER" 'deploy functions that run as it'
  if [ "$DRY" = 1 ] && [ "$HAVE_GCLOUD" = 0 ] || probe iam service-accounts describe "$APPSPOT" --project="$PROJECT" >/dev/null; then
    grant deploy "sa:$APPSPOT" roles/iam.serviceAccountUser "$DEPLOYER" 'the Firebase CLI'\''s functions pre-deploy check requires it, even for functions that run as compute'
  else
    say "  # $APPSPOT does not exist — no App Engine account, so the CLI's pre-deploy check needs nothing on it"
  fi
fi
if uses secrets; then grant deploy project roles/secretmanager.viewer "$DEPLOYER" 'the CLI checks each defineSecret has a version and reads the secret'\''s policy (never the value)'; fi
if uses schedule; then grant deploy project roles/cloudscheduler.admin "$DEPLOYER" 'onSchedule functions deploy a Cloud Scheduler job each'; fi
if uses events; then grant deploy project roles/eventarc.developer "$DEPLOYER" 'event-triggered gen-2 functions deploy an Eventarc trigger each'; fi
if uses firestore-rules || uses storage; then grant deploy project roles/firebaserules.admin "$DEPLOYER" 'publish firestore.rules / storage.rules (a rules release)'; fi
if uses firestore-indexes; then grant deploy project roles/datastore.indexAdmin "$DEPLOYER" 'create and update the composite indexes in firestore.indexes.json'; fi
if uses storage; then grant deploy project roles/firebasestorage.viewer "$DEPLOYER" 'the CLI looks up the default bucket the rules attach to'; fi
if uses hosting; then grant deploy project roles/firebasehosting.admin "$DEPLOYER" "publish Firebase Hosting releases (not App Hosting: that is Firebase's own rollout)"; fi
if uses extensions; then grant deploy project roles/firebaseextensions.viewer "$DEPLOYER" 'the CLI reads the installed extension instances it reconciles'; fi

# RUN-TIME grants — what the deployed functions need. The CLI would otherwise add them DURING a deploy (which would
# need IAM admin on the deployer): granted here, ahead of it, the deployer never changes IAM.
SKIPPED=""
if uses functions; then
  for secret in $SECRETS; do
    if [ "$DRY" = 1 ] && [ "$HAVE_GCLOUD" = 0 ] || probe secrets describe "$secret" --project="$PROJECT" >/dev/null; then
      grant runtime "secret:$secret" roles/secretmanager.secretAccessor "serviceAccount:$COMPUTE" "the functions read $secret at run time (granted on THIS secret only — the CLI checks the secret's own policy)"
    else
      SKIPPED="$SKIPPED  - secret $secret does not exist in $PROJECT yet: push it (nx run <functions>:push-secrets, or npx firebase functions:secrets:set $secret -P $TARGET), then re-run this
"
    fi
  done
  if uses events; then
    grant runtime project roles/iam.serviceAccountTokenCreator "serviceAccount:service-$NUMBER@gcp-sa-pubsub.iam.gserviceaccount.com" 'Pub/Sub mints the tokens that push events to the functions'
    grant runtime project roles/run.invoker "serviceAccount:$COMPUTE" 'Eventarc invokes the event-triggered functions as the compute account'
    grant runtime project roles/eventarc.eventReceiver "serviceAccount:$COMPUTE" 'the compute account receives the Eventarc events'
  fi
  if uses storage-events; then grant runtime project roles/pubsub.publisher "serviceAccount:service-$NUMBER@gs-project-accounts.iam.gserviceaccount.com" 'Cloud Storage publishes the bucket events storage-triggered functions listen to'; fi
fi

# CONVERGE: a recorded grant this run no longer wants (a feature dropped from firebase.json) is removed.
while IFS="$TAB" read -r _ class resource role member; do
  printf '%s' "$WANTED" | grep -qxF "$class$TAB$resource$TAB$role$TAB$member" && continue
  say "  - $role on $resource → $member (recorded, no longer needed)"
  change_binding remove "$resource" "$role" "$member"
  unrecord grant "$class" "$resource" "$role" "$member"
done < <(recorded grant)

# The CLI ends a functions deploy by setting up an image cleanup policy, and under --non-interactive it FAILS when
# none exists (after deploying). Set it once, here, wherever a gcf-artifacts repository already exists.
if uses functions; then
  REPOS="$(probe artifacts repositories list --project="$PROJECT" --filter='name~/repositories/gcf-artifacts$' --format='value(name)' || true)"
  if [ -n "$REPOS" ]; then
    for repo in $REPOS; do
      location="$(printf '%s' "$repo" | sed -E 's#.*/locations/([^/]+)/.*#\1#')"
      say "  + npx firebase functions:artifacts:setpolicy --project $PROJECT --location $location --force"
      [ "$DRY" = 1 ] || npx --no-install firebase functions:artifacts:setpolicy --project "$PROJECT" --location "$location" --force >/dev/null \
        || SKIPPED="$SKIPPED  - the image cleanup policy in $location (the project's firebase CLI failed, above): npx firebase functions:artifacts:setpolicy --project $PROJECT --location $location --force
"
    done
  else
    say "  # no gcf-artifacts repository yet (no function deployed). If the first CI deploy ends on 'could not set up cleanup policy',"
    say "  #   run: npx firebase functions:artifacts:setpolicy --project $PROJECT --location <region>   — then re-run the workflow."
  fi
fi
trap - ERR

# ── what the human does on GitHub ───────────────────────────────────────────────────────────────────────────────
GH_USER_ID=""
if command -v gh >/dev/null; then GH_USER_ID="$(gh api user --jq .id 2>/dev/null || true)"; fi
case "$GH_USER_ID" in ''|*[!0-9]*) GH_USER_ID='<your GitHub user id: gh api user --jq .id>' ;; esac
POLICIES=""
IFS=',' read -r -a LINES <<<"$BRANCHES"
for line in "${LINES[@]}"; do
  POLICIES="$POLICIES  gh api --method POST repos/$REPO/environments/$ENVIRONMENT/deployment-branch-policies -f name='$line' -f type=branch
"
done
say ""
if [ -n "$SKIPPED" ]; then
  say "INCOMPLETE — these were skipped, and a deploy needs them:"
  printf '%s' "$SKIPPED"
  say "Everything else is done (and recorded in $RECORD). Fix the above, then re-run."
  exit 1
fi
if [ "$DRY" = 1 ]; then say "Dry run complete — nothing was changed. A real run then prints these GitHub steps:"
else say "Done. Commit $RECORD — rollback undoes exactly what it lists. Then, on GitHub (run these, or paste them to Claude):"; fi
say "  # 1. The environment, deployable ONLY from its bound branches, and only after a reviewer approves. (Required reviewers"
say "  #    need a public repository, or GitHub Pro/Team+ for a private one — without them, drop the reviewers field.)"
say "  echo '{\"deployment_branch_policy\": {\"protected_branches\": false, \"custom_branch_policies\": true}, \"reviewers\": [{\"type\": \"User\", \"id\": $GH_USER_ID}]}' | gh api --method PUT repos/$REPO/environments/$ENVIRONMENT --input -"
printf '%s' "$POLICIES"
say "  # 2. Its cloud identity (not secrets):"
say "  gh variable set $VAR_PROVIDER --env $ENVIRONMENT --repo $REPO --body '$POOL_ID/providers/$PROVIDER'"
say "  gh variable set $VAR_SERVICE_ACCOUNT --env $ENVIRONMENT --repo $REPO --body '$SA'"
say "The first deploy: Actions → Deploy → Run workflow on the branch, scope = all."
