// THE DEPLOY WORKFLOW — rendered from the branch model's `ci` bindings and the active deploy providers.
//
// Code, not a template: its trigger list, its line → environment table and its authentication steps are all
// DERIVED (from the projection and from the providers the active layers contribute), and a template with that many
// holes is a program written in a worse language. What it does, step by step, is explained in its own comments —
// the generated file is read by the people whose deploys it runs.
import type { CiDeployProvider } from '../../layers/descriptor';
import type { PackageManager } from '../_utils/package-manager';

/** The actions the workflow uses — one place to move a major. */
export const ACTIONS = {
  checkout: 'actions/checkout@v4',
  setupNode: 'actions/setup-node@v4',
  nxSetShas: 'nrwl/nx-set-shas@v4',
} as const;

/** The `ci` layer's marker — its evidence, and the record of what the house owns. */
export const MARKER = '.bespunky/ci.json';

/** The path of the owned workflow. */
export const WORKFLOW = '.github/workflows/deploy.yml';

/** One wired line: a branch name or glob, the environment it deploys into, and the args its deploy targets get. */
export interface WiredLine {
  branch: string;
  environment: string;
  args: string[];
}

export interface WorkflowInput {
  lines: readonly WiredLine[];
  providers: readonly CiDeployProvider[];
  /** How Nx is invoked on the runner (`yarn nx`, `npx nx`, `pnpm nx`, `./nx`). */
  nx: string;
  /** The package manager (a node host), or undefined on the Nx wrapper host (nothing to install). */
  packageManager?: PackageManager;
  /** Yarn 2+ (`yarn install --immutable`) rather than classic (`--frozen-lockfile`). */
  yarnBerry: boolean;
  /** The file the project declares its Node in (_utils/node-version `nodeVersionFile`) — setup-node reads each kind. */
  nodeVersionFile: string;
}

/** The install a CI runner does: exactly the lockfile, never an update of it. */
function installStep(pm: PackageManager | undefined, berry: boolean): string[] {
  if (!pm) return [];
  const command = { npm: 'npm ci', pnpm: 'pnpm install --frozen-lockfile', yarn: berry ? 'yarn install --immutable' : 'yarn install --frozen-lockfile' }[pm];
  return [
    ...(pm === 'npm' ? [] : ['      # The package manager at the version package.json declares (`packageManager`), through Node\'s corepack.', '      - run: corepack enable']),
    `      - run: ${command}`,
  ];
}

const quote = (value: string) => `'${value.replace(/'/g, "''")}'`;

export function renderWorkflow(input: WorkflowInput): string {
  const branches = [...new Set(input.lines.map((line) => line.branch))];
  // bash `case` arms, most specific first (exact names before globs) — a name the model binds wins over a pattern
  // that happens to match it.
  const arms = [...input.lines]
    .sort((a, b) => Number(a.branch.includes('*')) - Number(b.branch.includes('*')))
    .map((line) => {
      const pattern = line.branch.includes('*') ? line.branch : `'${line.branch}'`;
      return `            ${pattern}) echo "environment=${line.environment}"; echo "args=${line.args.join(' ')}" ;;`;
    });
  const auth = input.providers.map((provider) => provider.authSteps().replace(/^(?=.)/gm, '      ')).join('');

  return [
    '# Generated by @bespunky/nx-tools (the `ci` layer) — OWNED: rewritten on every house upgrade. Never hand-edit it.',
    '#   WHEN it deploys and WHERE (which lines → which environment) is the branch model: the `ci` deploy bindings in',
    '#   .bespunky/branches.json — change them through the branch-and-release skill, then upgrade.',
    '#   WHAT ships, and how, is each project\'s `deploy` target — change the targets.',
    '# HOUSE.md → "Continuous deployment (CI)" explains the whole loop, and the one-time cloud setup a human runs.',
    'name: Deploy',
    '',
    'on:',
    '  push:',
    '    branches:',
    ...branches.map((branch) => `      - ${quote(branch)}`),
    '  workflow_dispatch:',
    '    inputs:',
    '      scope:',
    "        description: 'affected = what changed since the last successful deploy of this branch; all = every project with a deploy target (the first deploy, or a recovery)'",
    '        type: choice',
    '        options: [affected, all]',
    '        default: affected',
    '',
    '# One deploy per branch at a time, and never cancelled: a cancelled deploy is a half-deployed environment. A push',
    '# that arrives meanwhile waits, then deploys everything since the last SUCCESSFUL run (nx-set-shas) — so a failed',
    '# deploy is retried by the next push, and nothing is skipped.',
    'concurrency:',
    '  group: deploy-${{ github.ref }}',
    '  cancel-in-progress: false',
    '',
    'permissions:',
    '  contents: read',
    '',
    'jobs:',
    '  resolve:',
    '    name: Resolve the environment',
    '    runs-on: ubuntu-latest',
    '    outputs:',
    '      environment: ${{ steps.binding.outputs.environment }}',
    '      args: ${{ steps.binding.outputs.args }}',
    '    steps:',
    '      # The branch model\'s `ci` bindings: which environment this branch deploys into, and what each deploy',
    '      # provider\'s targets are told about it.',
    '      - id: binding',
    '        shell: bash',
    '        run: |',
    '          {',
    '          case "$GITHUB_REF_NAME" in',
    ...arms,
    '            *) echo "::error::Branch $GITHUB_REF_NAME has no ci deploy binding in the branch model (.bespunky/branches.json) — nothing deploys from it." >&2; exit 1 ;;',
    '          esac',
    '          } >> "$GITHUB_OUTPUT"',
    '',
    '  deploy:',
    '    name: Deploy to ${{ needs.resolve.outputs.environment }}',
    '    needs: resolve',
    '    runs-on: ubuntu-latest',
    '    # A GitHub environment per deployment environment: its variables (the cloud identity) and its protection rules.',
    '    environment: ${{ needs.resolve.outputs.environment }}',
    '    permissions:',
    '      contents: read',
    '      actions: read # nx-set-shas reads this workflow\'s previous runs',
    '      id-token: write # keyless cloud auth: GitHub\'s OIDC token, exchanged by Workload Identity Federation',
    '    steps:',
    `      - uses: ${ACTIONS.checkout}`,
    '        with:',
    '          fetch-depth: 0 # affected needs the history back to the last successful deploy',
    '      # Node from the project\'s one declaration of it — the same file the devcontainer reads.',
    `      - uses: ${ACTIONS.setupNode}`,
    '        with:',
    `          node-version-file: ${input.nodeVersionFile}`,
    ...installStep(input.packageManager, input.yarnBerry),
    '      # The base is the last SUCCESSFUL run of this workflow on this branch (not the previous commit).',
    `      - uses: ${ACTIONS.nxSetShas}`,
    '        with:',
    '          main-branch-name: ${{ github.ref_name }}',
    auth.trimEnd(),
    '      - name: Deploy',
    '        shell: bash',
    '        env:',
    "          SCOPE: ${{ inputs.scope || 'affected' }}",
    '          DEPLOY_ARGS: ${{ needs.resolve.outputs.args }}',
    '        run: |',
    '          if [ "$SCOPE" = all ]; then',
    `            ${input.nx} run-many -t deploy --outputStyle=static $DEPLOY_ARGS`,
    '          else',
    `            ${input.nx} affected -t deploy --base="$NX_BASE" --head="$NX_HEAD" --outputStyle=static $DEPLOY_ARGS`,
    '          fi',
    '',
  ]
    .filter((line) => line !== '')
    .join('\n')
    .replace(/\n(on:|# One deploy|permissions:|jobs:|  deploy:)/g, '\n\n$1') + '\n';
}
